-- =============================================================================
-- bomb_racks_patch.sql
-- Parche idempotente: 5 racks de bombas (type=BombLauncher en scunpacked) que
-- no estaban en el seed original de missile_launchers (que solo ingestaba
-- type=MissileLauncher). Incluye el CST-313 Castillo de Behring.
-- =============================================================================
-- Aplicación: idempotente via ON CONFLICT DO NOTHING. Podes correr en cualquier
-- entorno sin riesgo — si ya existen por UUID, se saltean.
-- =============================================================================

insert into missile_launchers (
  id, class_name, item_name, name, description, size, grade, mass, width, height, length,
  manufacturer_id, missile_count, missiles_label, durability_health, ports
) values
('c9686715-884f-456a-afbe-054107c8c54a', 'BMBRCK_S03_BEHR_Single_S03', 'bmbrck_s03_behr_single_s03', 'CST-313 "Castillo"', 'Designed to fit a wide variety of ships, the CST-313 "Castillo" bomb rack is able to store a single S3 bomb and makes for a good alternative on ships that can support a S3 missile rack.', 3, 1, 20, 0.15, 0.15, 0.15, '65a5d887-3b21-4046-a718-6912c0c7c3be', NULL, '1xS3', 200, '"[{\"PortName\":\"missile_01_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":3,\"MinSize\":3,\"MaxSize\":3,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false}]"'::jsonb),
('549964bb-a674-41ba-86d5-55a6d3c25931', 'MRCK_S03_TEMP_BOMB', 'mrck_s03_temp_bomb', 'MSD-313 Missile Rack', 'Behring''s MSD-313 "Marsden" is a complete ordnance storage and deployment system that can be mounted on any compatible size 3 hardpoint for the reliable and effective launch of one S3 missile.', 3, 1, 20, 0.15, 0.15, 0.15, '65a5d887-3b21-4046-a718-6912c0c7c3be', NULL, '1xS3', 200, '"[{\"PortName\":\"missile_01_attach\",\"DisplayName\":\"@port_NameMissileRackSlot01\",\"Size\":10,\"MinSize\":1,\"MaxSize\":10,\"Types\":[\"Bomb.UNDEFINED\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"UNDEFINED\"]}],\"Uneditable\":false}]"'::jsonb),
('7a8d5207-e203-4bbc-8cec-6956b4129a7e', 'BMBRCK_CRUS_Spirit_A1', 'bmbrck_crus_spirit_a1', 'MSD-313 Missile Rack', 'Behring''s MSD-313 "Marsden" is a complete ordnance storage and deployment system that can be mounted on any compatible size 3 hardpoint for the reliable and effective launch of one S3 missile.', 5, 1, 20, 0.15, 0.15, 0.15, '65a5d887-3b21-4046-a718-6912c0c7c3be', NULL, '1xS3', 200, '"[{\"PortName\":\"missile_01_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_02_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_03_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_04_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_05_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_06_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_07_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_08_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_09_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_10_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":5,\"MinSize\":5,\"MaxSize\":5,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false}]"'::jsonb),
('4394a178-7e74-4943-9538-2139f65839fd', 'BMBRCK_CRUS_STARL_Left', 'bmbrck_crus_starl_left', 'MSD-313 Missile Rack', 'Behring''s MSD-313 "Marsden" is a complete ordnance storage and deployment system that can be mounted on any compatible size 3 hardpoint for the reliable and effective launch of one S3 missile.', 10, 1, 20, 0.15, 0.15, 0.15, '65a5d887-3b21-4046-a718-6912c0c7c3be', NULL, '1xS3', 3600, '"[{\"PortName\":\"missile_01_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":10,\"MinSize\":10,\"MaxSize\":10,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_02_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":10,\"MinSize\":10,\"MaxSize\":10,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false}]"'::jsonb),
('8352da44-4b63-4a4b-8397-734dfb11698b', 'BMBRCK_CRUS_STARL_Right', 'bmbrck_crus_starl_right', 'MSD-313 Missile Rack', 'Behring''s MSD-313 "Marsden" is a complete ordnance storage and deployment system that can be mounted on any compatible size 3 hardpoint for the reliable and effective launch of one S3 missile.', 10, 1, 20, 0.15, 0.15, 0.15, '65a5d887-3b21-4046-a718-6912c0c7c3be', NULL, '1xS3', 3600, '"[{\"PortName\":\"missile_01_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":10,\"MinSize\":10,\"MaxSize\":10,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false},{\"PortName\":\"missile_02_attach\",\"DisplayName\":\"@LOC_EMPTY\",\"Size\":10,\"MinSize\":10,\"MaxSize\":10,\"Types\":[\"Bomb.Utility\"],\"CompatibleTypes\":[{\"Type\":\"Bomb\",\"SubTypes\":[\"Utility\"]}],\"Uneditable\":false}]"'::jsonb)
on conflict (id) do nothing;
