-- =============================================================================
-- Seed: commodity_prices (auto-generated from Commodities SCU.csv)
-- =============================================================================

-- Clear existing data before re-seeding
TRUNCATE commodity_prices;

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('AGRI', 'HUR-L1', 'Stanton', 'buy', 9213),
('AGRI', 'Levski', 'Nyx', 'buy', 9035),
('AGRI', 'ArcCorp 141', 'Stanton', 'buy', 9028),
('AGRI', 'Shubin SMCa-8', 'Stanton', 'buy', 8943),
('AGRI', 'Shubin SMCa-6', 'Stanton', 'buy', 8895),
('AGRI', 'Endgame', 'Pyro', 'buy', 7655),
('AGRI', 'Brio''s Breaker', 'Stanton', 'sell', 7200),
('AGRI', 'Devlin Scrap', 'Stanton', 'sell', 7200),
('AGRI', 'Samson & Son''s', 'Stanton', 'sell', 7200),
('AGRI', 'GrimHEX', 'Stanton', 'sell', 8200),
('AGRI', 'Checkmate', 'Pyro', 'sell', 9200),
('AGRI', 'Megumi', 'Pyro', 'sell', 9200),
('AGRI', 'Orbituary', 'Pyro', 'sell', 9200),
('AGRI', 'Patch City', 'Pyro', 'sell', 9200),
('AGRI', 'Rat''s Nest', 'Pyro', 'sell', 9200),
('AGRI', 'Ruin Station', 'Pyro', 'sell', 9200),
('AGRI', 'Starlight Service', 'Pyro', 'sell', 9200),
('AGRI', 'PSS Alpha', 'Nyx', 'sell', 10000),
('AGRI', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 10000),
('AGRI', 'CRU-L1', 'Stanton', 'sell', 10000),
('AGRI', 'CRU-L4', 'Stanton', 'sell', 10000),
('AGRI', 'CRU-L5', 'Stanton', 'sell', 10000),
('AGRI', 'HUR-L3', 'Stanton', 'sell', 10000),
('AGRI', 'HUR-L4', 'Stanton', 'sell', 10000),
('AGRI', 'HUR-L5', 'Stanton', 'sell', 10000),
('AGRI', 'CBD Lorville', 'Stanton', 'sell', 10000),
('AGRI', 'TDD Area 18', 'Stanton', 'sell', 10000),
('AGRI', 'TDD Orison', 'Stanton', 'sell', 10000),
('AGRI', 'TDD New Babbage', 'Stanton', 'sell', 10000),
('AGRI', 'ARC-L3', 'Stanton', 'sell', 10667),
('AGRI', 'Rod''s Fuel', 'Pyro', 'sell', 10750),
('AGRI', 'ARC-L4', 'Stanton', 'sell', 11154),
('AGRS', 'Port Tressler', 'Stanton', 'buy', 1150),
('AGRS', 'Deakins Research', 'Stanton', 'buy', 1122),
('AGRS', 'Hickes Research', 'Stanton', 'buy', 1122),
('AGRS', 'Rayari Anvik', 'Stanton', 'buy', 1122),
('AGRS', 'Rayari Kaltag', 'Stanton', 'buy', 1115),
('AGRS', 'Checkmate', 'Pyro', 'buy', 1108),
('AGRS', 'Terra Gateway (Stanton)', 'Stanton', 'buy', 1091),
('AGRS', 'GrimHEX', 'Stanton', 'sell', 1100),
('AGRS', 'Ruin Station', 'Pyro', 'sell', 1300),
('AGRS', 'Starlight Service', 'Pyro', 'sell', 1300),
('AGRS', 'CBD Lorville', 'Stanton', 'sell', 1300),
('AGRS', 'TDD Area 18', 'Stanton', 'sell', 1300),
('AGRS', 'TDD Orison', 'Stanton', 'sell', 1300),
('AGRS', 'TDD New Babbage', 'Stanton', 'sell', 1300),
('AGRS', 'Gaslight', 'Pyro', 'sell', 1400),
('AGRS', 'Terra Mills', 'Stanton', 'sell', 1400),
('AGRS', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 1480),
('AGRS', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 1500),
('AGRS', 'Shepherd''s Rest', 'Pyro', 'sell', 1500),
('AGRS', 'Seraphim', 'Stanton', 'sell', 1500),
('AGRS', 'Levski', 'Nyx', 'sell', 1600),
('ALUM', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 3586),
('ALUM', 'Seraphim', 'Stanton', 'buy', 3439),
('ALUM', 'Pyro Gateway (Nyx)', 'Nyx', 'buy', 3272),
('ALUM', 'Stanton Gateway (Pyro)', 'Pyro', 'buy', 3231),
('ALUM', 'Shubin SM0-18', 'Stanton', 'buy', 3162),
('ALUM', 'HDMS-Anderson', 'Stanton', 'buy', 3106),
('ALUM', 'HDMS-Bezdek', 'Stanton', 'buy', 3106),
('ALUM', 'HDMS-Lathan', 'Stanton', 'buy', 3106),
('ALUM', 'HDMS-Norgaard', 'Stanton', 'buy', 3106),
('ALUM', 'HDMS-Ryder', 'Stanton', 'buy', 3106),
('ALUM', 'HDMS-Woodruff', 'Stanton', 'buy', 3106),
('ALUM', 'Shubin SM0-10', 'Stanton', 'buy', 3091),
('ALUM', 'Shubin SM0-13', 'Stanton', 'buy', 3051),
('ALUM', 'Shubin SM0-22', 'Stanton', 'buy', 3039),
('ALUM', 'Rod''s Fuel', 'Pyro', 'buy', 2882),
('ALUM', 'Megumi', 'Pyro', 'buy', 2772),
('ALUM', 'CRU-L4 Locker', 'Stanton', 'sell', 2900),
('ALUM', 'CRU-L5 Maintenance', 'Stanton', 'sell', 2900),
('ALUM', 'GrimHEX', 'Stanton', 'sell', 3100),
('ALUM', 'Levski', 'Nyx', 'sell', 3300),
('ALUM', 'Endgame', 'Pyro', 'sell', 3600),
('ALUM', 'Gaslight', 'Pyro', 'sell', 3600),
('ALUM', 'Orbituary', 'Pyro', 'sell', 3600),
('ALUM', 'Rat''s Nest', 'Pyro', 'sell', 3600),
('ALUM', 'Ruin Station', 'Pyro', 'sell', 3600),
('ALUM', 'Starlight Service', 'Pyro', 'sell', 3600),
('ALUM', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 3800),
('ALUM', 'CBD Lorville', 'Stanton', 'sell', 3800),
('ALUM', 'TDD Area 18', 'Stanton', 'sell', 3800),
('ALUM', 'TDD Orison', 'Stanton', 'sell', 3800),
('ALUM', 'TDD New Babbage', 'Stanton', 'sell', 3800),
('ALUM', 'Everus Harbor', 'Stanton', 'sell', 4188),
('ALUM', 'Port Tressler', 'Stanton', 'sell', 4425),
('ALUM', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 4436),
('AMIP', 'Ashland', 'Pyro', 'buy', 17432),
('AMIP', 'GrimHEX', 'Stanton', 'sell', 23000),
('AMIP', 'Seraphim', 'Stanton', 'sell', 23100),
('AMIP', 'Fallow Field', 'Pyro', 'sell', 24000),
('AMIP', 'The Golden Riviera', 'Pyro', 'sell', 24000),
('AMIP', 'Deakins Research', 'Stanton', 'sell', 24000),
('AMIP', 'Rayari Anvik', 'Stanton', 'sell', 24000),
('AMIP', 'Rayari Cantwell', 'Stanton', 'sell', 24000),
('AMIP', 'Rayari Kaltag', 'Stanton', 'sell', 24000),
('AMIP', 'Rayari McGrath', 'Stanton', 'sell', 24000),
('ARGO', 'Pyro Gateway (Nyx)', 'Nyx', 'buy', 320),
('ARGO', 'Stanton Gateway (Pyro)', 'Pyro', 'buy', 316),
('ARGO', 'Megumi', 'Pyro', 'buy', 300),
('ARGO', 'GrimHEX', 'Stanton', 'sell', 360),
('ARGO', 'Checkmate', 'Pyro', 'sell', 420),
('ARGO', 'Gaslight', 'Pyro', 'sell', 420),
('ARGO', 'Orbituary', 'Pyro', 'sell', 420),
('ARGO', 'Ruin Station', 'Pyro', 'sell', 420),
('ARGO', 'CBD Lorville', 'Stanton', 'sell', 440),
('ARGO', 'TDD Area 18', 'Stanton', 'sell', 440),
('ARGO', 'TDD Orison', 'Stanton', 'sell', 440),
('ARGO', 'TDD New Babbage', 'Stanton', 'sell', 440),
('ARGO', 'Levski', 'Nyx', 'sell', 490),
('ARGO', 'Everus Harbor', 'Stanton', 'sell', 490),
('ARGO', 'Seraphim', 'Stanton', 'sell', 550);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('ASLA', 'Levski', 'Nyx', 'sell', 5100),
('ASLA', 'Ruin Station', 'Pyro', 'sell', 5100),
('ASLA', 'GrimHEX', 'Stanton', 'sell', 5100),
('ASLA', 'CBD Lorville', 'Stanton', 'sell', 5100),
('ASLA', 'TDD Orison', 'Stanton', 'sell', 5100),
('ASLA', 'TDD New Babbage', 'Stanton', 'sell', 5100),
('ASLA', 'TDD Area 18', 'Stanton', 'sell', 5115),
('ASTA', 'MIC-L1', 'Stanton', 'buy', 2991),
('ASTA', 'MIC-L2', 'Stanton', 'buy', 2959),
('ASTA', 'HDMS-Ryder', 'Stanton', 'buy', 2898),
('ASTA', 'HDMS-Woodruff', 'Stanton', 'buy', 2898),
('ASTA', 'ARC-L3', 'Stanton', 'buy', 2887),
('ASTA', 'ArcCorp 157', 'Stanton', 'buy', 2882),
('ASTA', 'Shubin SM0-13', 'Stanton', 'buy', 2773),
('ASTA', 'ArcCorp 056', 'Stanton', 'buy', 2760),
('ASTA', 'ArcCorp 061', 'Stanton', 'buy', 2760),
('ASTA', 'Shubin SM0-10', 'Stanton', 'buy', 2760),
('ASTA', 'Shubin SM0-18', 'Stanton', 'buy', 2760),
('ASTA', 'Shubin SM0-22', 'Stanton', 'buy', 2760),
('ASTA', 'Brio''s Breaker', 'Stanton', 'sell', 2500),
('ASTA', 'Devlin Scrap', 'Stanton', 'sell', 2500),
('ASTA', 'Samson & Son''s', 'Stanton', 'sell', 2500),
('ASTA', 'GrimHEX', 'Stanton', 'sell', 2800),
('ASTA', 'Seraphim', 'Stanton', 'sell', 3400),
('ASTA', 'Levski', 'Nyx', 'sell', 3500),
('ASTA', 'CBD Lorville', 'Stanton', 'sell', 3500),
('ASTA', 'Rayari Cantwell', 'Stanton', 'sell', 3500),
('ASTA', 'Rayari McGrath', 'Stanton', 'sell', 3500),
('ASTA', 'TDD Area 18', 'Stanton', 'sell', 3500),
('ASTA', 'TDD Orison', 'Stanton', 'sell', 3500),
('ASTA', 'TDD New Babbage', 'Stanton', 'sell', 3500),
('ASTA', 'Deakins Research', 'Stanton', 'sell', 3600),
('ASTA', 'Rayari Anvik', 'Stanton', 'sell', 3600),
('ASTA', 'Rayari Kaltag', 'Stanton', 'sell', 3600),
('ASTA', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 3700),
('ASTA', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 3700),
('ASTA', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 3700),
('ASTA', 'ARC-L1', 'Stanton', 'sell', 3820),
('ASTA', 'CRU-L1', 'Stanton', 'sell', 3843),
('ASTA', 'ARC-L2', 'Stanton', 'sell', 3873),
('ASTA', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 4033),
('ATLA', 'Chawla''s Beach', 'Pyro', 'buy', 79878),
('ATLA', 'Rustville', 'Pyro', 'buy', 75018),
('ATLA', 'GrimHEX', 'Stanton', 'sell', 80000),
('ATLA', 'CBD Lorville', 'Stanton', 'sell', 89000),
('ATLA', 'TDD Area 18', 'Stanton', 'sell', 89000),
('ATLA', 'TDD Orison', 'Stanton', 'sell', 89000),
('ATLA', 'TDD New Babbage', 'Stanton', 'sell', 89000),
('ATLA', 'Seer''s Canyon', 'Pyro', 'sell', 94000),
('ATLA', 'Bueno Ravine', 'Pyro', 'sell', 96000),
('ATLA', 'Levski', 'Nyx', 'sell', 97286),
('ATLA', 'HDMS-Oparei', 'Stanton', 'sell', 100000),
('ATLA', 'HDMS-Edmond', 'Stanton', 'sell', 105000),
('AUTR', 'The Golden Riviera', 'Pyro', 'buy', 5679),
('AUTR', 'Rat''s Nest', 'Pyro', 'buy', 5153),
('AUTR', 'Megumi', 'Pyro', 'sell', 6180),
('AUTR', 'Checkmate', 'Pyro', 'sell', 6200),
('AUTR', 'Orbituary', 'Pyro', 'sell', 6200),
('AUTR', 'Ruin Station', 'Pyro', 'sell', 6200),
('AUTR', 'Ashland', 'Pyro', 'sell', 6200),
('AUTR', 'Fallow Field', 'Pyro', 'sell', 6200),
('AUTR', 'Starlight Service', 'Pyro', 'sell', 6350),
('AUTR', 'Gaslight', 'Pyro', 'sell', 6386),
('AUTR', 'Endgame', 'Pyro', 'sell', 6400),
('AUTR', 'Patch City', 'Pyro', 'sell', 6400),
('AUTR', 'Rod''s Fuel', 'Pyro', 'sell', 6400),
('AUTR', 'GrimHEX', 'Stanton', 'sell', 6500),
('AUTR', 'Brio''s Breaker', 'Stanton', 'sell', 6900),
('AUTR', 'Devlin Scrap', 'Stanton', 'sell', 6900),
('AUTR', 'Reclamation Orinth', 'Stanton', 'sell', 6900),
('AUTR', 'Samson & Son''s', 'Stanton', 'sell', 6900),
('AUTR', 'CRU-L4 Locker', 'Stanton', 'sell', 7100),
('BERA', 'Levski', 'Nyx', 'sell', 120000),
('BERA', 'Brio''s Breaker', 'Stanton', 'sell', 120000),
('BERA', 'CBD Lorville', 'Stanton', 'sell', 120000),
('BERA', 'TDD Area 18', 'Stanton', 'sell', 120000),
('BERA', 'TDD Orison', 'Stanton', 'sell', 120000),
('BERA', 'TDD New Babbage', 'Stanton', 'sell', 120000),
('BERA', 'Baijini Point', 'Stanton', 'sell', 150000),
('BERA', 'Everus Harbor', 'Stanton', 'sell', 150000),
('BERA', 'Port Tressler', 'Stanton', 'sell', 150000),
('BERA', 'Seraphim', 'Stanton', 'sell', 150000),
('BERA', 'HDMS-Anderson', 'Stanton', 'sell', 170000),
('BERA', 'HDMS-Bezdek', 'Stanton', 'sell', 170000),
('BERA', 'HDMS-Edmond', 'Stanton', 'sell', 170000),
('BERA', 'HDMS-Norgaard', 'Stanton', 'sell', 170000),
('BERA', 'HDMS-Oparei', 'Stanton', 'sell', 170000),
('BERA', 'HDMS-Ryder', 'Stanton', 'sell', 170000),
('BERA', 'HDMS-Woodruff', 'Stanton', 'sell', 170000),
('BERY', 'Levski', 'Nyx', 'buy', 16013),
('BERY', 'CRU-L5 Maintenance', 'Stanton', 'sell', 15000),
('BERY', 'Reclamation Orinth', 'Stanton', 'sell', 15000),
('BERY', 'GrimHEX', 'Stanton', 'sell', 16000),
('BERY', 'Checkmate', 'Pyro', 'sell', 19000),
('BERY', 'Gaslight', 'Pyro', 'sell', 19000),
('BERY', 'Megumi', 'Pyro', 'sell', 19000),
('BERY', 'Orbituary', 'Pyro', 'sell', 19000),
('BERY', 'Rat''s Nest', 'Pyro', 'sell', 19000),
('BERY', 'Ruin Station', 'Pyro', 'sell', 19000),
('BERY', 'Starlight Service', 'Pyro', 'sell', 19000),
('BERY', 'PSS Theta', 'Nyx', 'sell', 20000),
('BERY', 'CRU-L5', 'Stanton', 'sell', 20000),
('BERY', 'MIC-L5', 'Stanton', 'sell', 20000),
('BERY', 'CBD Lorville', 'Stanton', 'sell', 20000),
('BERY', 'TDD Area 18', 'Stanton', 'sell', 20000),
('BERY', 'TDD Orison', 'Stanton', 'sell', 20000),
('BERY', 'TDD New Babbage', 'Stanton', 'sell', 20000),
('BERY', 'Endgame', 'Pyro', 'sell', 21000),
('BERY', 'HUR-L1', 'Stanton', 'sell', 22000),
('BERY', 'HUR-L4', 'Stanton', 'sell', 22000),
('BERY', 'HUR-L5', 'Stanton', 'sell', 22000),
('BERY', 'HUR-L3', 'Stanton', 'sell', 23000),
('BERY', 'Rod''s Fuel', 'Pyro', 'sell', 23250);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('BEXA', 'HDMS-Stanhope', 'Stanton', 'buy', 26933),
('BEXA', 'HDMS-Pinewood', 'Stanton', 'buy', 26824),
('BEXA', 'HDMS-Hadley', 'Stanton', 'buy', 26683),
('BEXA', 'HDMS-Thedus', 'Stanton', 'buy', 26352),
('BEXA', 'Bueno Ravine', 'Pyro', 'buy', 25371),
('BEXA', 'Fallow Field', 'Pyro', 'buy', 24793),
('BEXA', 'CRU-L5 Maintenance', 'Stanton', 'sell', 24000),
('BEXA', 'GrimHEX', 'Stanton', 'sell', 26000),
('BEXA', 'Levski', 'Nyx', 'sell', 27000),
('BEXA', 'Brio''s Breaker', 'Stanton', 'sell', 27000),
('BEXA', 'CBD Lorville', 'Stanton', 'sell', 28000),
('BEXA', 'TDD Orison', 'Stanton', 'sell', 28750),
('BEXA', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 29000),
('BEXA', 'TDD Area 18', 'Stanton', 'sell', 29000),
('BEXA', 'TDD New Babbage', 'Stanton', 'sell', 29000),
('BEXA', 'Endgame', 'Pyro', 'sell', 30000),
('BEXA', 'Rod''s Fuel', 'Pyro', 'sell', 30000),
('BEXA', 'The Golden Riviera', 'Pyro', 'sell', 32000),
('BEXA', 'Rat''s Nest', 'Pyro', 'sell', 32500),
('BEXA', 'Sacren''s Plot', 'Pyro', 'sell', 32500),
('BIOP', 'Rayari Kaltag', 'Stanton', 'buy', 6679),
('BIOP', 'Rayari Anvik', 'Stanton', 'buy', 6665),
('BIOP', 'The Golden Riviera', 'Pyro', 'buy', 6538),
('BIOP', 'Deakins Research', 'Stanton', 'buy', 6538),
('BIOP', 'Shepherd''s Rest', 'Pyro', 'sell', 5700),
('BIOP', 'GrimHEX', 'Stanton', 'sell', 6500),
('BIOP', 'Ruin Station', 'Pyro', 'sell', 6900),
('BIOP', 'CBD Lorville', 'Stanton', 'sell', 7300),
('BIOP', 'TDD Area 18', 'Stanton', 'sell', 7300),
('BIOP', 'TDD Orison', 'Stanton', 'sell', 7300),
('BIOP', 'TDD New Babbage', 'Stanton', 'sell', 7300),
('BIOP', 'Terra Mills', 'Stanton', 'sell', 7500),
('BIOP', 'Megumi', 'Pyro', 'sell', 7700),
('BIOP', 'Rat''s Nest', 'Pyro', 'sell', 7700),
('BIOP', 'Starlight Service', 'Pyro', 'sell', 7700),
('BIOP', 'Ashland', 'Pyro', 'sell', 7700),
('BIOP', 'Fallow Field', 'Pyro', 'sell', 7700),
('BIOP', 'Sacren''s Plot', 'Pyro', 'sell', 7700),
('BIOP', 'Chawla''s Beach', 'Pyro', 'sell', 8100),
('BIOP', 'Rustville', 'Pyro', 'sell', 8100),
('BIOP', 'Rayari Cantwell', 'Stanton', 'sell', 8200),
('BIOP', 'Rayari McGrath', 'Stanton', 'sell', 8283),
('BIOP', 'Levski', 'Nyx', 'sell', 8500),
('BIOP', 'Checkmate', 'Pyro', 'sell', 8600),
('BIOP', 'Orbituary', 'Pyro', 'sell', 8600),
('CARB', 'Baijini Point', 'Stanton', 'buy', 283),
('CARB', 'Everus Harbor', 'Stanton', 'buy', 274),
('CARB', 'Checkmate', 'Pyro', 'buy', 235),
('CARB', 'Orbituary', 'Pyro', 'buy', 235),
('CARB', 'Gaslight', 'Pyro', 'sell', 300),
('CARB', 'Megumi', 'Pyro', 'sell', 330),
('CARB', 'Ruin Station', 'Pyro', 'sell', 330),
('CARB', 'GrimHEX', 'Stanton', 'sell', 330),
('CARB', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 350),
('CARB', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 350),
('CARB', 'CBD Lorville', 'Stanton', 'sell', 350),
('CARB', 'TDD Area 18', 'Stanton', 'sell', 350),
('CARB', 'TDD Orison', 'Stanton', 'sell', 350),
('CARB', 'TDD New Babbage', 'Stanton', 'sell', 350),
('CARB', 'Levski', 'Nyx', 'sell', 370),
('CARB', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 380),
('CARB', 'Port Tressler', 'Stanton', 'sell', 380),
('CARB', 'Seraphim', 'Stanton', 'sell', 380),
('CARB', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 430),
('CHLO', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 1448),
('CHLO', 'Deakins Research', 'Stanton', 'buy', 1314),
('CHLO', 'Seraphim', 'Stanton', 'buy', 1248),
('CHLO', 'HDMS-Hahn', 'Stanton', 'buy', 1204),
('CHLO', 'HDMS-Perlman', 'Stanton', 'buy', 1204),
('CHLO', 'Shubin SAL-5', 'Stanton', 'buy', 1204),
('CHLO', 'Samson & Son''s', 'Stanton', 'sell', 1100),
('CHLO', 'GrimHEX', 'Stanton', 'sell', 1200),
('CHLO', 'CRU-L5 Maintenance', 'Stanton', 'sell', 1300),
('CHLO', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 1400),
('CHLO', 'Ruin Station', 'Pyro', 'sell', 1400),
('CHLO', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 1400),
('CHLO', 'Levski', 'Nyx', 'sell', 1500),
('CHLO', 'Port Tressler', 'Stanton', 'sell', 1500),
('CHLO', 'CBD Lorville', 'Stanton', 'sell', 1500),
('CHLO', 'TDD Area 18', 'Stanton', 'sell', 1500),
('CHLO', 'TDD Orison', 'Stanton', 'sell', 1500),
('CHLO', 'TDD New Babbage', 'Stanton', 'sell', 1500),
('CHLO', 'Rayari Cantwell', 'Stanton', 'sell', 1700),
('CHLO', 'Rayari McGrath', 'Stanton', 'sell', 1700),
('CHLO', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 1825),
('CMAT', 'Seer''s Canyon', 'Pyro', 'buy', 11813),
('CMAT', 'Chawla''s Beach', 'Pyro', 'buy', 11693),
('CMAT', 'Rustville', 'Pyro', 'buy', 11693),
('CMAT', 'Levski', 'Nyx', 'buy', 11481),
('CMAT', 'CRU-L5 Maintenance', 'Stanton', 'sell', 11000),
('CMAT', 'GrimHEX', 'Stanton', 'sell', 12000),
('CMAT', 'Reclamation Orinth', 'Stanton', 'sell', 12000),
('CMAT', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 14000),
('CMAT', 'Checkmate', 'Pyro', 'sell', 14000),
('CMAT', 'Megumi', 'Pyro', 'sell', 14000),
('CMAT', 'Orbituary', 'Pyro', 'sell', 14000),
('CMAT', 'Ruin Station', 'Pyro', 'sell', 14000),
('CMAT', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 14000),
('CMAT', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 14000),
('CMAT', 'Dunboro', 'Stanton', 'sell', 14000),
('CMAT', 'Pickers Field', 'Stanton', 'sell', 14000),
('CMAT', 'Rappel', 'Stanton', 'sell', 14000),
('CMAT', 'TDD Orison', 'Stanton', 'sell', 14750),
('CMAT', 'ARC-L1', 'Stanton', 'sell', 15000),
('CMAT', 'ARC-L3', 'Stanton', 'sell', 15000),
('CMAT', 'CRU-L4', 'Stanton', 'sell', 15000),
('CMAT', 'Everus Harbor', 'Stanton', 'sell', 15000),
('CMAT', 'HUR-L3', 'Stanton', 'sell', 15000),
('CMAT', 'HUR-L4', 'Stanton', 'sell', 15000),
('CMAT', 'MIC-L1', 'Stanton', 'sell', 15000),
('CMAT', 'MIC-L2', 'Stanton', 'sell', 15000),
('CMAT', 'MIC-L4', 'Stanton', 'sell', 15000),
('CMAT', 'MIC-L5', 'Stanton', 'sell', 15000),
('CMAT', 'Port Tressler', 'Stanton', 'sell', 15000),
('CMAT', 'CBD Lorville', 'Stanton', 'sell', 15000),
('CMAT', 'TDD Area 18', 'Stanton', 'sell', 15000),
('CMAT', 'TDD New Babbage', 'Stanton', 'sell', 15000),
('CMAT', 'HUR-L1', 'Stanton', 'sell', 15600),
('CMAT', 'ARC-L4', 'Stanton', 'sell', 16091);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('COBA', 'Shubin SMCa-6', 'Stanton', 'buy', 19616),
('COBA', 'Shubin SM0-18', 'Stanton', 'buy', 19595),
('COBA', 'Shubin SM0-10', 'Stanton', 'buy', 19407),
('COBA', 'Shubin SM0-22', 'Stanton', 'buy', 19266),
('COBA', 'Shubin SMCa-8', 'Stanton', 'buy', 19147),
('COBA', 'Shubin SM0-13', 'Stanton', 'buy', 19140),
('COBA', 'HDMS-Edmond', 'Stanton', 'buy', 18849),
('COBA', 'Starlight Service', 'Pyro', 'buy', 18573),
('COBA', 'HDMS-Oparei', 'Stanton', 'buy', 18270),
('COBA', 'Bueno Ravine', 'Pyro', 'buy', 18208),
('COBA', 'GrimHEX', 'Stanton', 'sell', 18000),
('COBA', 'Ashland', 'Pyro', 'sell', 20000),
('COBA', 'CBD Lorville', 'Stanton', 'sell', 20000),
('COBA', 'TDD Area 18', 'Stanton', 'sell', 20000),
('COBA', 'TDD Orison', 'Stanton', 'sell', 20000),
('COBA', 'TDD New Babbage', 'Stanton', 'sell', 20000),
('COBA', 'The Golden Riviera', 'Pyro', 'sell', 22000),
('COBA', 'Shubin SCD-1', 'Stanton', 'sell', 22000),
('COBA', 'Rod''s Fuel', 'Pyro', 'sell', 22500),
('COBA', 'Levski', 'Nyx', 'sell', 23000),
('COMP', 'Fallow Field', 'Pyro', 'buy', 31422),
('COMP', 'PSS Delta', 'Nyx', 'buy', 30560),
('COMP', 'PSS Lambda', 'Nyx', 'buy', 30364),
('COMP', 'PSS Alpha', 'Nyx', 'buy', 29752),
('COMP', 'PSS Theta', 'Nyx', 'buy', 29442),
('COMP', 'Rayari Kaltag', 'Stanton', 'buy', 28613),
('COMP', 'Rayari Anvik', 'Stanton', 'buy', 28332),
('COMP', 'ARC-L1', 'Stanton', 'sell', 27000),
('COMP', 'ARC-L2', 'Stanton', 'sell', 27000),
('COMP', 'ARC-L3', 'Stanton', 'sell', 27000),
('COMP', 'ARC-L4', 'Stanton', 'sell', 27000),
('COMP', 'ARC-L5', 'Stanton', 'sell', 27000),
('COMP', 'CRU-L1', 'Stanton', 'sell', 27000),
('COMP', 'CRU-L4', 'Stanton', 'sell', 27000),
('COMP', 'CRU-L5', 'Stanton', 'sell', 27000),
('COMP', 'HUR-L2', 'Stanton', 'sell', 27000),
('COMP', 'HUR-L3', 'Stanton', 'sell', 27000),
('COMP', 'HUR-L4', 'Stanton', 'sell', 27000),
('COMP', 'HUR-L5', 'Stanton', 'sell', 27000),
('COMP', 'MIC-L1', 'Stanton', 'sell', 27000),
('COMP', 'MIC-L2', 'Stanton', 'sell', 27000),
('COMP', 'Ruin Station', 'Pyro', 'sell', 28000),
('COMP', 'GrimHEX', 'Stanton', 'sell', 28000),
('COMP', 'CBD Lorville', 'Stanton', 'sell', 28000),
('COMP', 'TDD Area 18', 'Stanton', 'sell', 28000),
('COMP', 'TDD Orison', 'Stanton', 'sell', 28000),
('COMP', 'TDD New Babbage', 'Stanton', 'sell', 28000),
('COMP', 'MIC-L3', 'Stanton', 'sell', 30000),
('COMP', 'MIC-L4', 'Stanton', 'sell', 30000),
('COMP', 'MIC-L5', 'Stanton', 'sell', 30000),
('COMP', 'Ashland', 'Pyro', 'sell', 33000),
('COMP', 'Chawla''s Beach', 'Pyro', 'sell', 33000),
('COMP', 'Rustville', 'Pyro', 'sell', 33000),
('COMP', 'Sacren''s Plot', 'Pyro', 'sell', 33000),
('COMP', 'Seer''s Canyon', 'Pyro', 'sell', 33000),
('COMP', 'The Golden Riviera', 'Pyro', 'sell', 33000),
('COMP', 'HUR-L1', 'Stanton', 'sell', 34000),
('COMP', 'HDMS-Edmond', 'Stanton', 'sell', 34000),
('COMP', 'HDMS-Anderson', 'Stanton', 'sell', 35000),
('COMP', 'HDMS-Norgaard', 'Stanton', 'sell', 35000),
('COMP', 'HDMS-Oparei', 'Stanton', 'sell', 35000),
('COMP', 'Levski', 'Nyx', 'sell', 36429),
('COMP', 'Shubin SM0-10', 'Stanton', 'sell', 37000),
('COMP', 'Shubin SM0-13', 'Stanton', 'sell', 37000),
('COMP', 'Shubin SM0-18', 'Stanton', 'sell', 37000),
('COMP', 'Shubin SM0-22', 'Stanton', 'sell', 37000),
('COPP', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 3722),
('COPP', 'Port Tressler', 'Stanton', 'buy', 3496),
('COPP', 'Seraphim', 'Stanton', 'buy', 3459),
('COPP', 'Shubin SCD-1', 'Stanton', 'buy', 3413),
('COPP', 'Rayari Deltana', 'Stanton', 'buy', 3347),
('COPP', 'Shubin SM0-10', 'Stanton', 'buy', 3325),
('COPP', 'Shubin SM0-13', 'Stanton', 'buy', 3325),
('COPP', 'Shubin SM0-18', 'Stanton', 'buy', 3325),
('COPP', 'Shubin SM0-22', 'Stanton', 'buy', 3325),
('COPP', 'Orbituary', 'Pyro', 'buy', 3103),
('COPP', 'Megumi', 'Pyro', 'buy', 2906),
('COPP', 'Brio''s Breaker', 'Stanton', 'sell', 2400),
('COPP', 'Reclamation Orinth', 'Stanton', 'sell', 2800),
('COPP', 'CRU-L4 Locker', 'Stanton', 'sell', 3000),
('COPP', 'CRU-L5 Maintenance', 'Stanton', 'sell', 3000),
('COPP', 'GrimHEX', 'Stanton', 'sell', 3200),
('COPP', 'Levski', 'Nyx', 'sell', 3400),
('COPP', 'Ruin Station', 'Pyro', 'sell', 3400),
('COPP', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 3700),
('COPP', 'Patch City', 'Pyro', 'sell', 3700),
('COPP', 'Starlight Service', 'Pyro', 'sell', 3700),
('COPP', 'CBD Lorville', 'Stanton', 'sell', 3700),
('COPP', 'TDD Area 18', 'Stanton', 'sell', 3700),
('COPP', 'TDD Orison', 'Stanton', 'sell', 3700),
('COPP', 'TDD New Babbage', 'Stanton', 'sell', 3700),
('COPP', 'Baijini Point', 'Stanton', 'sell', 3900),
('COPP', 'Rat''s Nest', 'Pyro', 'sell', 4200),
('COPP', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 4220),
('COPP', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 4350),
('COPP', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 4583),
('COPP', 'Rod''s Fuel', 'Pyro', 'sell', 4675),
('CORU', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 3330),
('CORU', 'Baijini Point', 'Stanton', 'buy', 3199),
('CORU', 'Levski', 'Nyx', 'buy', 2970),
('CORU', 'Shubin SMCa-6', 'Stanton', 'buy', 2966),
('CORU', 'Shubin SCD-1', 'Stanton', 'buy', 2795),
('CORU', 'Shubin SMCa-8', 'Stanton', 'buy', 2640),
('CORU', 'Shubin SAL-5', 'Stanton', 'buy', 2508),
('CORU', 'CRU-L5 Maintenance', 'Stanton', 'sell', 2100),
('CORU', 'Reclamation Orinth', 'Stanton', 'sell', 2600),
('CORU', 'GrimHEX', 'Stanton', 'sell', 3000),
('CORU', 'Checkmate', 'Pyro', 'sell', 3500),
('CORU', 'Endgame', 'Pyro', 'sell', 3500),
('CORU', 'Gaslight', 'Pyro', 'sell', 3500),
('CORU', 'Rat''s Nest', 'Pyro', 'sell', 3500),
('CORU', 'Ruin Station', 'Pyro', 'sell', 3500),
('CORU', 'Starlight Service', 'Pyro', 'sell', 3500),
('CORU', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 3700),
('CORU', 'CBD Lorville', 'Stanton', 'sell', 3700),
('CORU', 'TDD Area 18', 'Stanton', 'sell', 3700),
('CORU', 'TDD Orison', 'Stanton', 'sell', 3700),
('CORU', 'TDD New Babbage', 'Stanton', 'sell', 3700),
('CORU', 'Everus Harbor', 'Stanton', 'sell', 4000),
('CORU', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 4100),
('CORU', 'Orbituary', 'Pyro', 'sell', 4400),
('CORU', 'Rod''s Fuel', 'Pyro', 'sell', 4400);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('CSIL', 'Shepherd''s Rest', 'Pyro', 'buy', 19255),
('CSIL', 'Sacren''s Plot', 'Pyro', 'buy', 18998),
('CSIL', 'Terra Mills', 'Stanton', 'buy', 18617),
('CSIL', 'GrimHEX', 'Stanton', 'sell', 18000),
('CSIL', 'Levski', 'Nyx', 'sell', 20000),
('CSIL', 'CBD Lorville', 'Stanton', 'sell', 20000),
('CSIL', 'TDD Area 18', 'Stanton', 'sell', 20000),
('CSIL', 'TDD Orison', 'Stanton', 'sell', 20000),
('CSIL', 'TDD New Babbage', 'Stanton', 'sell', 20000),
('CSIL', 'Endgame', 'Pyro', 'sell', 20833),
('CSIL', 'Patch City', 'Pyro', 'sell', 21000),
('CSIL', 'Rod''s Fuel', 'Pyro', 'sell', 21000),
('CSIL', 'Starlight Service', 'Pyro', 'sell', 21000),
('CSIL', 'Gaslight', 'Pyro', 'sell', 22143),
('CSIL', 'Rat''s Nest', 'Pyro', 'sell', 24286),
('DEGR', 'PSS Theta', 'Nyx', 'buy', 49870),
('DEGR', 'Shepherd''s Rest', 'Pyro', 'buy', 45639),
('DEGR', 'Levski', 'Nyx', 'sell', 53000),
('DEGR', 'GrimHEX', 'Stanton', 'sell', 53000),
('DEGR', 'CBD Lorville', 'Stanton', 'sell', 53000),
('DEGR', 'TDD Area 18', 'Stanton', 'sell', 53000),
('DEGR', 'TDD Orison', 'Stanton', 'sell', 53000),
('DEGR', 'TDD New Babbage', 'Stanton', 'sell', 53000),
('DEGR', 'Ashland', 'Pyro', 'sell', 57000),
('DEGR', 'The Golden Riviera', 'Pyro', 'sell', 58500),
('DEGR', 'Fallow Field', 'Pyro', 'sell', 59000),
('DEGR', 'ARC-L2', 'Stanton', 'sell', 62900),
('DEGR', 'PSS Lambda', 'Nyx', 'sell', 63000),
('DEGR', 'ARC-L4', 'Stanton', 'sell', 63000),
('DEGR', 'CRU-L4', 'Stanton', 'sell', 63000),
('DEGR', 'HUR-L3', 'Stanton', 'sell', 63000),
('DEGR', 'MIC-L4', 'Stanton', 'sell', 63000),
('DEGR', 'Port Tressler', 'Stanton', 'sell', 63000),
('DEGR', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 63000),
('DEGR', 'HUR-L5', 'Stanton', 'sell', 66250),
('DEGR', 'MIC-L1', 'Stanton', 'sell', 67125),
('DIAM', 'HUR-L4', 'Stanton', 'buy', 6770),
('DIAM', 'Bueno Ravine', 'Pyro', 'buy', 6561),
('DIAM', 'MIC-L2', 'Stanton', 'buy', 6487),
('DIAM', 'Rat''s Nest', 'Pyro', 'buy', 5871),
('DIAM', 'Reclamation Orinth', 'Stanton', 'sell', 5900),
('DIAM', 'Sacren''s Plot', 'Pyro', 'sell', 6200),
('DIAM', 'GrimHEX', 'Stanton', 'sell', 6200),
('DIAM', 'Starlight Service', 'Pyro', 'sell', 7300),
('DIAM', 'TDD Area 18', 'Stanton', 'sell', 7400),
('DIAM', 'Levski', 'Nyx', 'sell', 7700),
('DIAM', 'CBD Lorville', 'Stanton', 'sell', 7700),
('DIAM', 'Dunboro', 'Stanton', 'sell', 7700),
('DIAM', 'Pickers Field', 'Stanton', 'sell', 7700),
('DIAM', 'Rappel', 'Stanton', 'sell', 7700),
('DIAM', 'TDD Orison', 'Stanton', 'sell', 7700),
('DIAM', 'TDD New Babbage', 'Stanton', 'sell', 7700),
('DIAM', 'Rod''s Fuel', 'Pyro', 'sell', 7950),
('DIAM', 'ARC-L5', 'Stanton', 'sell', 8260),
('DIAM', 'HUR-L1', 'Stanton', 'sell', 8550),
('DIST', 'Terra Gateway (Stanton)', 'Stanton', 'buy', 1696),
('DIST', 'Rayari Kaltag', 'Stanton', 'buy', 1583),
('DIST', 'Deakins Research', 'Stanton', 'buy', 1574),
('DIST', 'Hickes Research', 'Stanton', 'buy', 1574),
('DIST', 'Rayari Anvik', 'Stanton', 'buy', 1574),
('DIST', 'Checkmate', 'Pyro', 'buy', 1468),
('DIST', 'Gaslight', 'Pyro', 'buy', 1323),
('DIST', 'CRU-L5 Maintenance', 'Stanton', 'sell', 1500),
('DIST', 'GrimHEX', 'Stanton', 'sell', 1600),
('DIST', 'Rod''s Fuel', 'Pyro', 'sell', 1800),
('DIST', 'Ruin Station', 'Pyro', 'sell', 1800),
('DIST', 'ArcCorp 045', 'Stanton', 'sell', 1800),
('DIST', 'ArcCorp 048', 'Stanton', 'sell', 1800),
('DIST', 'ArcCorp 056', 'Stanton', 'sell', 1800),
('DIST', 'ArcCorp 061', 'Stanton', 'sell', 1800),
('DIST', 'Rayari Cantwell', 'Stanton', 'sell', 1800),
('DIST', 'Rayari Deltana', 'Stanton', 'sell', 1800),
('DIST', 'Rayari McGrath', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SAL-2', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SAL-5', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SCD-1', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SM0-10', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SM0-13', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SM0-18', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SM0-22', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SMCa-6', 'Stanton', 'sell', 1800),
('DIST', 'Shubin SMCa-8', 'Stanton', 'sell', 1800),
('DIST', 'Baijini Point', 'Stanton', 'sell', 1850),
('DIST', 'Levski', 'Nyx', 'sell', 1900),
('DIST', 'ARC-L1', 'Stanton', 'sell', 1900),
('DIST', 'ARC-L2', 'Stanton', 'sell', 1900),
('DIST', 'ARC-L3', 'Stanton', 'sell', 1900),
('DIST', 'ARC-L4', 'Stanton', 'sell', 1900),
('DIST', 'ARC-L5', 'Stanton', 'sell', 1900),
('DIST', 'CRU-L1', 'Stanton', 'sell', 1900),
('DIST', 'CRU-L4', 'Stanton', 'sell', 1900),
('DIST', 'CRU-L5', 'Stanton', 'sell', 1900),
('DIST', 'HUR-L1', 'Stanton', 'sell', 1900),
('DIST', 'HUR-L2', 'Stanton', 'sell', 1900),
('DIST', 'HUR-L3', 'Stanton', 'sell', 1900),
('DIST', 'HUR-L4', 'Stanton', 'sell', 1900),
('DIST', 'HUR-L5', 'Stanton', 'sell', 1900),
('DIST', 'MIC-L1', 'Stanton', 'sell', 1900),
('DIST', 'MIC-L2', 'Stanton', 'sell', 1900),
('DIST', 'MIC-L3', 'Stanton', 'sell', 1900),
('DIST', 'MIC-L4', 'Stanton', 'sell', 1900),
('DIST', 'ArcCorp 141', 'Stanton', 'sell', 1900),
('DIST', 'ArcCorp 157', 'Stanton', 'sell', 1900),
('DIST', 'CBD Lorville', 'Stanton', 'sell', 1900),
('DIST', 'TDD Area 18', 'Stanton', 'sell', 1900),
('DIST', 'TDD Orison', 'Stanton', 'sell', 1900),
('DIST', 'TDD New Babbage', 'Stanton', 'sell', 1900),
('DIST', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 2000),
('DIST', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 2011),
('DIST', 'MIC-L5', 'Stanton', 'sell', 2100);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('DYMA', 'HDMS-Edmond', 'Stanton', 'buy', 22943),
('DYMA', 'HDMS-Oparei', 'Stanton', 'buy', 22943),
('DYMA', 'PSS Delta', 'Nyx', 'buy', 22483),
('DYMA', 'Shubin SAL-5', 'Stanton', 'buy', 22335),
('DYMA', 'PSS Alpha', 'Nyx', 'buy', 22203),
('DYMA', 'PSS Lambda', 'Nyx', 'buy', 22160),
('DYMA', 'PSS Theta', 'Nyx', 'buy', 21433),
('DYMA', 'Seer''s Canyon', 'Pyro', 'buy', 21027),
('DYMA', 'Rustville', 'Pyro', 'buy', 17480),
('DYMA', 'Ruin Station', 'Pyro', 'sell', 21000),
('DYMA', 'GrimHEX', 'Stanton', 'sell', 21000),
('DYMA', 'CBD Lorville', 'Stanton', 'sell', 23000),
('DYMA', 'TDD Area 18', 'Stanton', 'sell', 23000),
('DYMA', 'TDD Orison', 'Stanton', 'sell', 23000),
('DYMA', 'TDD New Babbage', 'Stanton', 'sell', 23000),
('DYMA', 'The Golden Riviera', 'Pyro', 'sell', 24000),
('DYMA', 'Levski', 'Nyx', 'sell', 26222),
('DYMA', 'Bueno Ravine', 'Pyro', 'sell', 27000),
('DYNF', 'Port Tressler', 'Stanton', 'buy', 1754),
('DYNF', 'Patch City', 'Pyro', 'buy', 1664),
('DYNF', 'Checkmate', 'Pyro', 'buy', 1609),
('DYNF', 'Starlight Service', 'Pyro', 'buy', 1384),
('DYNF', 'GrimHEX', 'Stanton', 'sell', 1600),
('DYNF', 'Levski', 'Nyx', 'sell', 1900),
('DYNF', 'Megumi', 'Pyro', 'sell', 1900),
('DYNF', 'Ruin Station', 'Pyro', 'sell', 1900),
('DYNF', 'CBD Lorville', 'Stanton', 'sell', 1900),
('DYNF', 'TDD Area 18', 'Stanton', 'sell', 1900),
('DYNF', 'TDD Orison', 'Stanton', 'sell', 1900),
('DYNF', 'TDD New Babbage', 'Stanton', 'sell', 1900),
('DYNF', 'Baijini Point', 'Stanton', 'sell', 2000),
('DYNF', 'Endgame', 'Pyro', 'sell', 2080),
('DYNF', 'Seraphim', 'Stanton', 'sell', 2317),
('ETAM', 'Fallow Field', 'Pyro', 'buy', 19588),
('ETAM', 'The Golden Riviera', 'Pyro', 'buy', 18514),
('ETAM', 'Ashland', 'Pyro', 'buy', 18286),
('ETAM', 'GrimHEX', 'Stanton', 'sell', 21000),
('ETAM', 'Starlight Service', 'Pyro', 'sell', 22500),
('ETAM', 'Rod''s Fuel', 'Pyro', 'sell', 22750),
('ETAM', 'Gaslight', 'Pyro', 'sell', 22857),
('ETAM', 'Endgame', 'Pyro', 'sell', 23000),
('ETAM', 'Rat''s Nest', 'Pyro', 'sell', 23000),
('ETAM', 'Reclamation Orinth', 'Stanton', 'sell', 24000),
('ETAM', 'Brio''s Breaker', 'Stanton', 'sell', 26000),
('ETAM', 'Devlin Scrap', 'Stanton', 'sell', 26000),
('ETAM', 'CRU-L4 Locker', 'Stanton', 'sell', 26000),
('ETAM', 'Samson & Son''s', 'Stanton', 'sell', 26500),
('FEYN', 'Levski', 'Nyx', 'sell', 270000),
('FEYN', 'CBD Lorville', 'Stanton', 'sell', 270000),
('FEYN', 'TDD Area 18', 'Stanton', 'sell', 270000),
('FEYN', 'TDD New Babbage', 'Stanton', 'sell', 270000),
('FEYN', 'Brio''s Breaker', 'Stanton', 'sell', 280000),
('FEYN', 'TDD Orison', 'Stanton', 'sell', 340000),
('FEYN', 'Baijini Point', 'Stanton', 'sell', 350000),
('FEYN', 'Everus Harbor', 'Stanton', 'sell', 350000),
('FEYN', 'Port Tressler', 'Stanton', 'sell', 350000),
('FEYN', 'Seraphim', 'Stanton', 'sell', 350000),
('FEYN', 'HDMS-Hadley', 'Stanton', 'sell', 380000),
('FEYN', 'HDMS-Stanhope', 'Stanton', 'sell', 380000),
('FEYN', 'HDMS-Thedus', 'Stanton', 'sell', 380000),
('FEYN', 'HDMS-Pinewood', 'Stanton', 'sell', 384500),
('FEYN', 'HDMS-Anderson', 'Stanton', 'sell', 390000),
('FEYN', 'HDMS-Bezdek', 'Stanton', 'sell', 390000),
('FEYN', 'HDMS-Edmond', 'Stanton', 'sell', 390000),
('FEYN', 'HDMS-Norgaard', 'Stanton', 'sell', 390000),
('FEYN', 'HDMS-Oparei', 'Stanton', 'sell', 390000),
('FEYN', 'HDMS-Woodruff', 'Stanton', 'sell', 390000),
('FEYN', 'HDMS-Ryder', 'Stanton', 'sell', 394500),
('FFOO', 'Rayari Kaltag', 'Stanton', 'buy', 23137),
('FFOO', 'Terra Mills', 'Stanton', 'buy', 23100),
('FFOO', 'Shepherd''s Rest', 'Pyro', 'buy', 23092),
('FFOO', 'Rayari Anvik', 'Stanton', 'buy', 22698),
('FFOO', 'GrimHEX', 'Stanton', 'sell', 21000),
('FFOO', 'Ruin Station', 'Pyro', 'sell', 24000),
('FFOO', 'CBD Lorville', 'Stanton', 'sell', 24000),
('FFOO', 'TDD Area 18', 'Stanton', 'sell', 24000),
('FFOO', 'TDD Orison', 'Stanton', 'sell', 24000),
('FFOO', 'TDD New Babbage', 'Stanton', 'sell', 24000),
('FFOO', 'Ashland', 'Pyro', 'sell', 25000),
('FFOO', 'Bueno Ravine', 'Pyro', 'sell', 25000),
('FFOO', 'Chawla''s Beach', 'Pyro', 'sell', 25000),
('FFOO', 'Fallow Field', 'Pyro', 'sell', 25000),
('FFOO', 'Rustville', 'Pyro', 'sell', 25000),
('FFOO', 'Sacren''s Plot', 'Pyro', 'sell', 25000),
('FFOO', 'Seer''s Canyon', 'Pyro', 'sell', 25000),
('FFOO', 'The Golden Riviera', 'Pyro', 'sell', 25000),
('FFOO', 'Levski', 'Nyx', 'sell', 26000),
('FFOO', 'HDMS-Pinewood', 'Stanton', 'sell', 27000),
('FFOO', 'HDMS-Stanhope', 'Stanton', 'sell', 27000),
('FFOO', 'HDMS-Thedus', 'Stanton', 'sell', 27500),
('FFOO', 'HDMS-Hadley', 'Stanton', 'sell', 28000),
('FLUO', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 1142),
('FLUO', 'Patch City', 'Pyro', 'buy', 1124),
('FLUO', 'Seraphim', 'Stanton', 'buy', 1115),
('FLUO', 'Rat''s Nest', 'Pyro', 'buy', 1114),
('FLUO', 'Starlight Service', 'Pyro', 'buy', 1082),
('FLUO', 'Gaslight', 'Pyro', 'buy', 1069),
('FLUO', 'Rayari Deltana', 'Stanton', 'buy', 973),
('FLUO', 'GrimHEX', 'Stanton', 'sell', 1000),
('FLUO', 'Brio''s Breaker', 'Stanton', 'sell', 1000),
('FLUO', 'Devlin Scrap', 'Stanton', 'sell', 1000),
('FLUO', 'CRU-L5 Maintenance', 'Stanton', 'sell', 1000),
('FLUO', 'Levski', 'Nyx', 'sell', 1200),
('FLUO', 'Checkmate', 'Pyro', 'sell', 1200),
('FLUO', 'Megumi', 'Pyro', 'sell', 1200),
('FLUO', 'Orbituary', 'Pyro', 'sell', 1200),
('FLUO', 'Ruin Station', 'Pyro', 'sell', 1200),
('FLUO', 'CBD Lorville', 'Stanton', 'sell', 1200),
('FLUO', 'TDD Area 18', 'Stanton', 'sell', 1200),
('FLUO', 'TDD Orison', 'Stanton', 'sell', 1200),
('FLUO', 'TDD New Babbage', 'Stanton', 'sell', 1200),
('FLUO', 'Everus Harbor', 'Stanton', 'sell', 1300),
('FLUO', 'Rayari Cantwell', 'Stanton', 'sell', 1300),
('FLUO', 'Rayari McGrath', 'Stanton', 'sell', 1300),
('FLUO', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 1400),
('FLUO', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 1470),
('FLUO', 'Port Tressler', 'Stanton', 'sell', 1488),
('FLUO', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 1500);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('FOAM', 'Hickes Research', 'Stanton', 'buy', 5341),
('FOAM', 'Deakins Research', 'Stanton', 'buy', 5329),
('FOAM', 'GrimHEX', 'Stanton', 'sell', 5100),
('FOAM', 'Rayari Cantwell', 'Stanton', 'sell', 6000),
('FOAM', 'Rayari Deltana', 'Stanton', 'sell', 6000),
('FOAM', 'Rayari McGrath', 'Stanton', 'sell', 6000),
('FOAM', 'CBD Lorville', 'Stanton', 'sell', 6100),
('FOAM', 'TDD Area 18', 'Stanton', 'sell', 6100),
('FOAM', 'TDD Orison', 'Stanton', 'sell', 6100),
('FOAM', 'TDD New Babbage', 'Stanton', 'sell', 6100),
('FOAM', 'ARC-L3', 'Stanton', 'sell', 6300),
('FOAM', 'ARC-L5', 'Stanton', 'sell', 6300),
('FOAM', 'HUR-L1', 'Stanton', 'sell', 6300),
('FOAM', 'Levski', 'Nyx', 'sell', 6400),
('FOAM', 'CRU-L4', 'Stanton', 'sell', 6900),
('FOAM', 'HUR-L4', 'Stanton', 'sell', 6950),
('FOAM', 'MIC-L4', 'Stanton', 'sell', 7000),
('FOAM', 'CRU-L1', 'Stanton', 'sell', 7008),
('GLAC', 'Levski', 'Nyx', 'sell', 80000),
('GLAC', 'CBD Lorville', 'Stanton', 'sell', 80000),
('GLAC', 'TDD Area 18', 'Stanton', 'sell', 80000),
('GLAC', 'TDD New Babbage', 'Stanton', 'sell', 80000),
('GLAC', 'Brio''s Breaker', 'Stanton', 'sell', 82000),
('GLAC', 'Baijini Point', 'Stanton', 'sell', 100000),
('GLAC', 'Everus Harbor', 'Stanton', 'sell', 100000),
('GLAC', 'Port Tressler', 'Stanton', 'sell', 100000),
('GLAC', 'Seraphim', 'Stanton', 'sell', 100000),
('GLAC', 'TDD Orison', 'Stanton', 'sell', 100000),
('GLAC', 'HDMS-Anderson', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Bezdek', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Hadley', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Norgaard', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Pinewood', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Ryder', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Stanhope', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Thedus', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Woodruff', 'Stanton', 'sell', 110000),
('GLAC', 'HDMS-Edmond', 'Stanton', 'sell', 120000),
('GLAC', 'HDMS-Oparei', 'Stanton', 'sell', 120000),
('GOLD', 'HDMS-Perlman', 'Stanton', 'buy', 30127),
('GOLD', 'ARC-L3', 'Stanton', 'buy', 29877),
('GOLD', 'HDMS-Bezdek', 'Stanton', 'buy', 29569),
('GOLD', 'HDMS-Lathan', 'Stanton', 'buy', 29517),
('GOLD', 'HDMS-Hahn', 'Stanton', 'buy', 29112),
('GOLD', 'Shubin SCD-1', 'Stanton', 'buy', 28540),
('GOLD', 'CRU-L5', 'Stanton', 'buy', 28520),
('GOLD', 'HDMS-Anderson', 'Stanton', 'buy', 28434),
('GOLD', 'HDMS-Norgaard', 'Stanton', 'buy', 28033),
('GOLD', 'Rod''s Fuel', 'Pyro', 'buy', 27550),
('GOLD', 'CRU-L4 Locker', 'Stanton', 'sell', 23000),
('GOLD', 'Samson & Son''s', 'Stanton', 'sell', 23000),
('GOLD', 'Fallow Field', 'Pyro', 'sell', 26000),
('GOLD', 'Sacren''s Plot', 'Pyro', 'sell', 26000),
('GOLD', 'GrimHEX', 'Stanton', 'sell', 26000),
('GOLD', 'Levski', 'Nyx', 'sell', 28000),
('GOLD', 'Ashland', 'Pyro', 'sell', 29000),
('GOLD', 'The Golden Riviera', 'Pyro', 'sell', 29000),
('GOLD', 'CBD Lorville', 'Stanton', 'sell', 32000),
('GOLD', 'TDD Orison', 'Stanton', 'sell', 32000),
('GOLD', 'TDD New Babbage', 'Stanton', 'sell', 32000),
('GOLD', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 33000),
('GOLD', 'TDD Area 18', 'Stanton', 'sell', 33000),
('GOLD', 'ARC-L1', 'Stanton', 'sell', 33600),
('GOLD', 'Rat''s Nest', 'Pyro', 'sell', 34000),
('GOLM', 'Shepherd''s Rest', 'Pyro', 'buy', 51982),
('GOLM', 'Levski', 'Nyx', 'sell', 54000),
('GOLM', 'Ruin Station', 'Pyro', 'sell', 54000),
('GOLM', 'GrimHEX', 'Stanton', 'sell', 54000),
('GOLM', 'CBD Lorville', 'Stanton', 'sell', 54000),
('GOLM', 'TDD Area 18', 'Stanton', 'sell', 54000),
('GOLM', 'TDD Orison', 'Stanton', 'sell', 54000),
('GOLM', 'TDD New Babbage', 'Stanton', 'sell', 54000),
('GOLM', 'Seraphim', 'Stanton', 'sell', 64000),
('GOLM', 'The Golden Riviera', 'Pyro', 'sell', 69000),
('GOLM', 'Fallow Field', 'Pyro', 'sell', 69500),
('GOLM', 'Ashland', 'Pyro', 'sell', 71000),
('HELI', 'Seraphim', 'Stanton', 'buy', 829),
('HELI', 'Checkmate', 'Pyro', 'buy', 734),
('HELI', 'Ruin Station', 'Pyro', 'buy', 725),
('HELI', 'CRU-L4 Locker', 'Stanton', 'sell', 770),
('HELI', 'CRU-L5 Maintenance', 'Stanton', 'sell', 770),
('HELI', 'GrimHEX', 'Stanton', 'sell', 870),
('HELI', 'Endgame', 'Pyro', 'sell', 1000),
('HELI', 'Gaslight', 'Pyro', 'sell', 1000),
('HELI', 'Rod''s Fuel', 'Pyro', 'sell', 1000),
('HELI', 'TDD Orison', 'Stanton', 'sell', 1000),
('HELI', 'Levski', 'Nyx', 'sell', 1100),
('HELI', 'CBD Lorville', 'Stanton', 'sell', 1100),
('HELI', 'TDD Area 18', 'Stanton', 'sell', 1100),
('HELI', 'TDD New Babbage', 'Stanton', 'sell', 1100),
('HELI', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 1300),
('HEPH', 'Baijini Point', 'Stanton', 'buy', 4525),
('HEPH', 'Bueno Ravine', 'Pyro', 'buy', 4517),
('HEPH', 'Pyro Gateway (Nyx)', 'Nyx', 'buy', 4277),
('HEPH', 'HUR-L2', 'Stanton', 'buy', 4241),
('HEPH', 'Terra Gateway (Stanton)', 'Stanton', 'buy', 4236),
('HEPH', 'Stanton Gateway (Pyro)', 'Pyro', 'buy', 4214),
('HEPH', 'Shubin SAL-5', 'Stanton', 'buy', 3929),
('HEPH', 'Rod''s Fuel', 'Pyro', 'buy', 3703),
('HEPH', 'Samson & Son''s', 'Stanton', 'sell', 3000),
('HEPH', 'CRU-L4 Locker', 'Stanton', 'sell', 3400),
('HEPH', 'GrimHEX', 'Stanton', 'sell', 3900),
('HEPH', 'Levski', 'Nyx', 'sell', 4100),
('HEPH', 'Gaslight', 'Pyro', 'sell', 4557),
('HEPH', 'Everus Harbor', 'Stanton', 'sell', 4563),
('HEPH', 'Checkmate', 'Pyro', 'sell', 4600),
('HEPH', 'Endgame', 'Pyro', 'sell', 4600),
('HEPH', 'Megumi', 'Pyro', 'sell', 4600),
('HEPH', 'Orbituary', 'Pyro', 'sell', 4600),
('HEPH', 'Patch City', 'Pyro', 'sell', 4600),
('HEPH', 'Rat''s Nest', 'Pyro', 'sell', 4600),
('HEPH', 'Ruin Station', 'Pyro', 'sell', 4600),
('HEPH', 'Starlight Service', 'Pyro', 'sell', 4600),
('HEPH', 'CRU-L5', 'Stanton', 'sell', 4600),
('HEPH', 'ARC-L4', 'Stanton', 'sell', 4720),
('HEPH', 'ARC-L5', 'Stanton', 'sell', 4800),
('HEPH', 'CRU-L1', 'Stanton', 'sell', 4800),
('HEPH', 'HUR-L5', 'Stanton', 'sell', 4800),
('HEPH', 'CBD Lorville', 'Stanton', 'sell', 4800),
('HEPH', 'TDD Area 18', 'Stanton', 'sell', 4800),
('HEPH', 'TDD Orison', 'Stanton', 'sell', 4800),
('HEPH', 'CRU-L4', 'Stanton', 'sell', 5275),
('HEPH', 'TDD New Babbage', 'Stanton', 'sell', 5320),
('HEPH', 'MIC-L5', 'Stanton', 'sell', 5483),
('HEPH', 'MIC-L4', 'Stanton', 'sell', 5533);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('HFBA', 'GrimHEX', 'Stanton', 'buy', 890),
('HFBA', 'Endgame', 'Pyro', 'buy', 416),
('HFBA', 'Gaslight', 'Pyro', 'buy', 416),
('HFBA', 'Patch City', 'Pyro', 'buy', 416),
('HFBA', 'Rod''s Fuel', 'Pyro', 'buy', 416),
('HFBA', 'Starlight Service', 'Pyro', 'buy', 416),
('HFBA', 'Rat''s Nest', 'Pyro', 'buy', 400),
('HFBA', 'Checkmate', 'Pyro', 'sell', 470),
('HFBA', 'Megumi', 'Pyro', 'sell', 470),
('HFBA', 'Orbituary', 'Pyro', 'sell', 470),
('HFBA', 'Ruin Station', 'Pyro', 'sell', 470),
('HFBA', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 490),
('HFBA', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 490),
('HFBA', 'Port Tressler', 'Stanton', 'sell', 490),
('HFBA', 'Seraphim', 'Stanton', 'sell', 490),
('HFBA', 'Ashland', 'Pyro', 'sell', 520),
('HFBA', 'The Golden Riviera', 'Pyro', 'sell', 520),
('HFBA', 'Fallow Field', 'Pyro', 'sell', 580),
('HYDR', 'Seraphim', 'Stanton', 'buy', 824),
('HYDR', 'Terra Gateway (Stanton)', 'Stanton', 'buy', 813),
('HYDR', 'Endgame', 'Pyro', 'buy', 752),
('HYDR', 'Gaslight', 'Pyro', 'buy', 705),
('HYDR', 'GrimHEX', 'Stanton', 'sell', 850),
('HYDR', 'Levski', 'Nyx', 'sell', 1000),
('HYDR', 'Patch City', 'Pyro', 'sell', 1000),
('HYDR', 'Ruin Station', 'Pyro', 'sell', 1000),
('HYDR', 'CRU-L1', 'Stanton', 'sell', 1000),
('HYDR', 'CRU-L4', 'Stanton', 'sell', 1000),
('HYDR', 'CRU-L5', 'Stanton', 'sell', 1000),
('HYDR', 'HUR-L5', 'Stanton', 'sell', 1000),
('HYDR', 'MIC-L1', 'Stanton', 'sell', 1000),
('HYDR', 'MIC-L2', 'Stanton', 'sell', 1000),
('HYDR', 'MIC-L3', 'Stanton', 'sell', 1000),
('HYDR', 'MIC-L4', 'Stanton', 'sell', 1000),
('HYDR', 'MIC-L5', 'Stanton', 'sell', 1000),
('HYDR', 'CBD Lorville', 'Stanton', 'sell', 1000),
('HYDR', 'TDD Area 18', 'Stanton', 'sell', 1000),
('HYDR', 'TDD Orison', 'Stanton', 'sell', 1000),
('HYDR', 'TDD New Babbage', 'Stanton', 'sell', 1000),
('HYDR', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 1100),
('HYDR', 'Orbituary', 'Pyro', 'sell', 1100),
('HYDR', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 1100),
('HYDR', 'Baijini Point', 'Stanton', 'sell', 1100),
('HYDR', 'Everus Harbor', 'Stanton', 'sell', 1100),
('HYDR', 'HUR-L1', 'Stanton', 'sell', 1100),
('HYDR', 'HUR-L2', 'Stanton', 'sell', 1100),
('HYDR', 'HUR-L3', 'Stanton', 'sell', 1100),
('HYDR', 'HUR-L4', 'Stanton', 'sell', 1100),
('HYDR', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 1100),
('HYDR', 'Checkmate', 'Pyro', 'sell', 1200),
('HYDR', 'Port Tressler', 'Stanton', 'sell', 1200),
('IODI', 'ArcCorp 061', 'Stanton', 'buy', 10568),
('IODI', 'Deakins Research', 'Stanton', 'buy', 10363),
('IODI', 'ArcCorp 056', 'Stanton', 'buy', 10249),
('IODI', 'Hickes Research', 'Stanton', 'buy', 9708),
('IODI', 'CRU-L5 Maintenance', 'Stanton', 'sell', 9500),
('IODI', 'GrimHEX', 'Stanton', 'sell', 10000),
('IODI', 'CBD Lorville', 'Stanton', 'sell', 11000),
('IODI', 'TDD Area 18', 'Stanton', 'sell', 11000),
('IODI', 'TDD Orison', 'Stanton', 'sell', 11000),
('IODI', 'TDD New Babbage', 'Stanton', 'sell', 11000),
('IODI', 'PSS Alpha', 'Nyx', 'sell', 12000),
('IODI', 'PSS Delta', 'Nyx', 'sell', 12000),
('IODI', 'PSS Lambda', 'Nyx', 'sell', 12000),
('IODI', 'PSS Theta', 'Nyx', 'sell', 12000),
('IODI', 'Seraphim', 'Stanton', 'sell', 12000),
('IODI', 'Rayari Cantwell', 'Stanton', 'sell', 12000),
('IODI', 'Rayari Deltana', 'Stanton', 'sell', 12000),
('IODI', 'Rayari McGrath', 'Stanton', 'sell', 12000),
('IODI', 'Levski', 'Nyx', 'sell', 12857),
('IRON', 'Pyro Gateway (Nyx)', 'Nyx', 'buy', 2910),
('IRON', 'Stanton Gateway (Pyro)', 'Pyro', 'buy', 2903),
('IRON', 'Everus Harbor', 'Stanton', 'buy', 2893),
('IRON', 'Shubin SMCa-6', 'Stanton', 'buy', 2891),
('IRON', 'Shubin SMCa-8', 'Stanton', 'buy', 2866),
('IRON', 'HDMS-Ryder', 'Stanton', 'buy', 2782),
('IRON', 'HDMS-Norgaard', 'Stanton', 'buy', 2773),
('IRON', 'HDMS-Bezdek', 'Stanton', 'buy', 2768),
('IRON', 'HDMS-Anderson', 'Stanton', 'buy', 2765),
('IRON', 'HDMS-Pinewood', 'Stanton', 'buy', 2762),
('IRON', 'HDMS-Hadley', 'Stanton', 'buy', 2755),
('IRON', 'HDMS-Lathan', 'Stanton', 'buy', 2752),
('IRON', 'HDMS-Woodruff', 'Stanton', 'buy', 2717),
('IRON', 'HDMS-Thedus', 'Stanton', 'buy', 2710),
('IRON', 'HDMS-Edmond', 'Stanton', 'buy', 2708),
('IRON', 'HDMS-Oparei', 'Stanton', 'buy', 2708),
('IRON', 'HDMS-Stanhope', 'Stanton', 'buy', 2708),
('IRON', 'Checkmate', 'Pyro', 'buy', 2667),
('IRON', 'Bueno Ravine', 'Pyro', 'buy', 2640),
('IRON', 'Orbituary', 'Pyro', 'buy', 2595),
('IRON', 'Levski', 'Nyx', 'buy', 2505),
('IRON', 'GrimHEX', 'Stanton', 'sell', 2700),
('IRON', 'Patch City', 'Pyro', 'sell', 3200),
('IRON', 'Rat''s Nest', 'Pyro', 'sell', 3200),
('IRON', 'Ruin Station', 'Pyro', 'sell', 3200),
('IRON', 'Starlight Service', 'Pyro', 'sell', 3200),
('IRON', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 3375),
('IRON', 'CBD Lorville', 'Stanton', 'sell', 3400),
('IRON', 'TDD Area 18', 'Stanton', 'sell', 3400),
('IRON', 'TDD Orison', 'Stanton', 'sell', 3400),
('IRON', 'TDD New Babbage', 'Stanton', 'sell', 3400),
('IRON', 'PSS Delta', 'Nyx', 'sell', 3425),
('IRON', 'PSS Alpha', 'Nyx', 'sell', 3467),
('IRON', 'PSS Lambda', 'Nyx', 'sell', 3500),
('IRON', 'PSS Theta', 'Nyx', 'sell', 3500),
('IRON', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 3500),
('IRON', 'Megumi', 'Pyro', 'sell', 3575),
('IRON', 'Rod''s Fuel', 'Pyro', 'sell', 3600),
('IRON', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 3692),
('IRON', 'Endgame', 'Pyro', 'sell', 3850),
('IRON', 'Gaslight', 'Pyro', 'sell', 3871);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('JACO', 'ArcCorp 045', 'Stanton', 'sell', 22000000),
('JACO', 'HDMS-Anderson', 'Stanton', 'sell', 23000000),
('JACO', 'HDMS-Norgaard', 'Stanton', 'sell', 23000000),
('LARA', 'ArcCorp 045', 'Stanton', 'buy', 7831),
('LARA', 'HDMS-Lathan', 'Stanton', 'buy', 7812),
('LARA', 'ARC-L1', 'Stanton', 'buy', 7709),
('LARA', 'HDMS-Bezdek', 'Stanton', 'buy', 7655),
('LARA', 'CRU-L4', 'Stanton', 'buy', 7573),
('LARA', 'ArcCorp 056', 'Stanton', 'buy', 7358),
('LARA', 'CRU-L5 Maintenance', 'Stanton', 'sell', 6500),
('LARA', 'GrimHEX', 'Stanton', 'sell', 7400),
('LARA', 'Levski', 'Nyx', 'sell', 7800),
('LARA', 'Orbituary', 'Pyro', 'sell', 8500),
('LARA', 'Endgame', 'Pyro', 'sell', 8700),
('LARA', 'Gaslight', 'Pyro', 'sell', 8700),
('LARA', 'Patch City', 'Pyro', 'sell', 8700),
('LARA', 'Rat''s Nest', 'Pyro', 'sell', 8700),
('LARA', 'Ruin Station', 'Pyro', 'sell', 8700),
('LARA', 'Starlight Service', 'Pyro', 'sell', 8700),
('LARA', 'TDD Area 18', 'Stanton', 'sell', 9000),
('LARA', 'TDD New Babbage', 'Stanton', 'sell', 9088),
('LARA', 'CBD Lorville', 'Stanton', 'sell', 9100),
('LARA', 'TDD Orison', 'Stanton', 'sell', 9100),
('LARA', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 9150),
('LARA', 'CRU-L1', 'Stanton', 'sell', 9200),
('LARA', 'HUR-L2', 'Stanton', 'sell', 9383),
('LARA', 'Rod''s Fuel', 'Pyro', 'sell', 9425),
('LARA', 'HUR-L1', 'Stanton', 'sell', 9483),
('LIND', 'Levski', 'Nyx', 'sell', 43000),
('LIND', 'Ruin Station', 'Pyro', 'sell', 43000),
('LIND', 'Megumi', 'Pyro', 'sell', 46000),
('LIND', 'TDD Area 18', 'Stanton', 'sell', 51000),
('LIND', 'TDD Orison', 'Stanton', 'sell', 51000),
('LIND', 'TDD New Babbage', 'Stanton', 'sell', 51000),
('MEDS', 'ARC-L2', 'Stanton', 'buy', 4449),
('MEDS', 'Terra Gateway (Stanton)', 'Stanton', 'buy', 4288),
('MEDS', 'MIC-L1', 'Stanton', 'buy', 3936),
('MEDS', 'MIC-L2', 'Stanton', 'buy', 3872),
('MEDS', 'Rayari Anvik', 'Stanton', 'buy', 3870),
('MEDS', 'Rayari Kaltag', 'Stanton', 'buy', 3614),
('MEDS', 'Hickes Research', 'Stanton', 'buy', 3409),
('MEDS', 'Deakins Research', 'Stanton', 'buy', 3376),
('MEDS', 'Reclamation Orinth', 'Stanton', 'sell', 3900),
('MEDS', 'GrimHEX', 'Stanton', 'sell', 3933),
('MEDS', 'ARC-L1', 'Stanton', 'sell', 4486),
('MEDS', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 4720),
('MEDS', 'CBD Lorville', 'Stanton', 'sell', 4750),
('MEDS', 'HUR-L1', 'Stanton', 'sell', 4760),
('MEDS', 'CRU-L4', 'Stanton', 'sell', 4800),
('MEDS', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 4833),
('MEDS', 'HUR-L5', 'Stanton', 'sell', 4850),
('MEDS', 'TDD Orison', 'Stanton', 'sell', 4850),
('MEDS', 'PSS Theta', 'Nyx', 'sell', 4867),
('MEDS', 'TDD New Babbage', 'Stanton', 'sell', 4870),
('MEDS', 'CRU-L1', 'Stanton', 'sell', 4875),
('MEDS', 'Levski', 'Nyx', 'sell', 4889),
('MEDS', 'PSS Lambda', 'Nyx', 'sell', 4900),
('MEDS', 'TDD Area 18', 'Stanton', 'sell', 4900),
('MEDS', 'PSS Alpha', 'Nyx', 'sell', 4920),
('MEDS', 'PSS Delta', 'Nyx', 'sell', 4925),
('MEDS', 'HUR-L4', 'Stanton', 'sell', 4950),
('MEDS', 'HUR-L2', 'Stanton', 'sell', 5029),
('MEDS', 'Orbituary', 'Pyro', 'sell', 5050),
('MEDS', 'ARC-L4', 'Stanton', 'sell', 5058),
('MEDS', 'HUR-L3', 'Stanton', 'sell', 5067),
('MEDS', 'ARC-L5', 'Stanton', 'sell', 5083),
('MEDS', 'Rod''s Fuel', 'Pyro', 'sell', 5100),
('MEDS', 'Starlight Service', 'Pyro', 'sell', 5100),
('MEDS', 'Endgame', 'Pyro', 'sell', 5117),
('MEDS', 'Ruin Station', 'Pyro', 'sell', 5133),
('MEDS', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 5170),
('MEDS', 'Rat''s Nest', 'Pyro', 'sell', 5183),
('MEDS', 'Patch City', 'Pyro', 'sell', 5200),
('MEDS', 'Sacren''s Plot', 'Pyro', 'sell', 5200),
('MEDS', 'Rayari McGrath', 'Stanton', 'sell', 5250),
('MEDS', 'Nyx Gateway (Pyro)', 'Pyro', 'sell', 5275),
('MEDS', 'Gaslight', 'Pyro', 'sell', 5314),
('MEDS', 'Rayari Deltana', 'Stanton', 'sell', 5333),
('MEDS', 'Rayari Cantwell', 'Stanton', 'sell', 5400),
('MERC', 'HUR-L4', 'Stanton', 'buy', 791),
('MERC', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 744),
('MERC', 'Checkmate', 'Pyro', 'buy', 649),
('MERC', 'GrimHEX', 'Stanton', 'sell', 900),
('MERC', 'Levski', 'Nyx', 'sell', 1000),
('MERC', 'Baijini Point', 'Stanton', 'sell', 1000),
('MERC', 'Everus Harbor', 'Stanton', 'sell', 1000),
('MERC', 'CBD Lorville', 'Stanton', 'sell', 1000),
('MERC', 'TDD Area 18', 'Stanton', 'sell', 1000),
('MERC', 'TDD Orison', 'Stanton', 'sell', 1000),
('MERC', 'TDD New Babbage', 'Stanton', 'sell', 1000),
('MERC', 'Ruin Station', 'Pyro', 'sell', 1100),
('METH', 'Rayari Anvik', 'Stanton', 'buy', 3314),
('METH', 'Stanton Gateway (Nyx)', 'Nyx', 'buy', 3312),
('METH', 'Deakins Research', 'Stanton', 'buy', 3312),
('METH', 'Hickes Research', 'Stanton', 'buy', 3312),
('METH', 'Rayari Kaltag', 'Stanton', 'buy', 3308),
('METH', 'CRU-L1', 'Stanton', 'buy', 3181),
('METH', 'HUR-L5', 'Stanton', 'buy', 2992),
('METH', 'Gaslight', 'Pyro', 'buy', 2788),
('METH', 'GrimHEX', 'Stanton', 'sell', 3000),
('METH', 'Endgame', 'Pyro', 'sell', 3500),
('METH', 'Megumi', 'Pyro', 'sell', 3500),
('METH', 'Patch City', 'Pyro', 'sell', 3500),
('METH', 'Rat''s Nest', 'Pyro', 'sell', 3500),
('METH', 'Ruin Station', 'Pyro', 'sell', 3500),
('METH', 'Levski', 'Nyx', 'sell', 3700),
('METH', 'CBD Lorville', 'Stanton', 'sell', 3700),
('METH', 'TDD Area 18', 'Stanton', 'sell', 3700),
('METH', 'TDD Orison', 'Stanton', 'sell', 3700),
('METH', 'TDD New Babbage', 'Stanton', 'sell', 3700),
('METH', 'Terra Mills', 'Stanton', 'sell', 3700),
('METH', 'ARC-L2', 'Stanton', 'sell', 3940),
('METH', 'ARC-L1', 'Stanton', 'sell', 3980),
('METH', 'MIC-L1', 'Stanton', 'sell', 4050),
('METH', 'Starlight Service', 'Pyro', 'sell', 4100);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('NEON', 'Ashland', 'Pyro', 'buy', 16619),
('NEON', 'Rustville', 'Pyro', 'buy', 15923),
('NEON', 'Checkmate', 'Pyro', 'sell', 17000),
('NEON', 'Megumi', 'Pyro', 'sell', 17000),
('NEON', 'Orbituary', 'Pyro', 'sell', 17000),
('NEON', 'Ruin Station', 'Pyro', 'sell', 17000),
('NEON', 'Brio''s Breaker', 'Stanton', 'sell', 18333),
('NEON', 'Fallow Field', 'Pyro', 'sell', 18500),
('NEON', 'Endgame', 'Pyro', 'sell', 19000),
('NEON', 'Gaslight', 'Pyro', 'sell', 19000),
('NEON', 'Patch City', 'Pyro', 'sell', 19000),
('NEON', 'Rat''s Nest', 'Pyro', 'sell', 19000),
('NEON', 'Rod''s Fuel', 'Pyro', 'sell', 19000),
('NEON', 'Starlight Service', 'Pyro', 'sell', 19000),
('NEON', 'The Golden Riviera', 'Pyro', 'sell', 19000),
('NEON', 'GrimHEX', 'Stanton', 'sell', 19000),
('NEON', 'Samson & Son''s', 'Stanton', 'sell', 19000),
('NEON', 'Reclamation Orinth', 'Stanton', 'sell', 20000),
('NEON', 'CRU-L4 Locker', 'Stanton', 'sell', 22500),
('NEON', 'Devlin Scrap', 'Stanton', 'sell', 25000),
('NITR', 'CRU-L5', 'Stanton', 'buy', 2769),
('NITR', 'CRU-L1', 'Stanton', 'buy', 2674),
('NITR', 'HUR-L3', 'Stanton', 'buy', 2629),
('NITR', 'Starlight Service', 'Pyro', 'buy', 2534),
('NITR', 'ARC-L5', 'Stanton', 'buy', 2509),
('NITR', 'Deakins Research', 'Stanton', 'buy', 2439),
('NITR', 'Hickes Research', 'Stanton', 'buy', 2439),
('NITR', 'Rayari Anvik', 'Stanton', 'buy', 2439),
('NITR', 'Endgame', 'Pyro', 'buy', 2434),
('NITR', 'Rayari Kaltag', 'Stanton', 'buy', 2426),
('NITR', 'Gaslight', 'Pyro', 'buy', 2310),
('NITR', 'GrimHEX', 'Stanton', 'sell', 2500),
('NITR', 'Levski', 'Nyx', 'sell', 3000),
('NITR', 'Checkmate', 'Pyro', 'sell', 3000),
('NITR', 'Megumi', 'Pyro', 'sell', 3000),
('NITR', 'Orbituary', 'Pyro', 'sell', 3000),
('NITR', 'Patch City', 'Pyro', 'sell', 3000),
('NITR', 'Rat''s Nest', 'Pyro', 'sell', 3000),
('NITR', 'Rod''s Fuel', 'Pyro', 'sell', 3000),
('NITR', 'Ruin Station', 'Pyro', 'sell', 3000),
('NITR', 'Shepherd''s Rest', 'Pyro', 'sell', 3000),
('NITR', 'CBD Lorville', 'Stanton', 'sell', 3000),
('NITR', 'TDD Area 18', 'Stanton', 'sell', 3000),
('NITR', 'TDD Orison', 'Stanton', 'sell', 3000),
('NITR', 'TDD New Babbage', 'Stanton', 'sell', 3000),
('NITR', 'CRU-L4', 'Stanton', 'sell', 3100),
('NITR', 'Terra Mills', 'Stanton', 'sell', 3100),
('NITR', 'HUR-L2', 'Stanton', 'sell', 3233),
('NITR', 'HUR-L4', 'Stanton', 'sell', 3350),
('NITR', 'MIC-L5', 'Stanton', 'sell', 3380),
('NITR', 'MIC-L1', 'Stanton', 'sell', 3383),
('NITR', 'ARC-L1', 'Stanton', 'sell', 3390),
('NITR', 'ARC-L2', 'Stanton', 'sell', 3391),
('NITR', 'ARC-L4', 'Stanton', 'sell', 3543),
('OMPO', 'Deakins Research', 'Stanton', 'buy', 4036),
('OMPO', 'Patch City', 'Pyro', 'buy', 3237),
('OMPO', 'CRU-L4', 'Stanton', 'sell', 3600),
('OMPO', 'GrimHEX', 'Stanton', 'sell', 3700),
('OMPO', 'Ruin Station', 'Pyro', 'sell', 4200),
('OMPO', 'Checkmate', 'Pyro', 'sell', 4300),
('OMPO', 'Rat''s Nest', 'Pyro', 'sell', 4300),
('OMPO', 'Rod''s Fuel', 'Pyro', 'sell', 4300),
('OMPO', 'Starlight Service', 'Pyro', 'sell', 4300),
('OMPO', 'Ashland', 'Pyro', 'sell', 4300),
('OMPO', 'CBD Lorville', 'Stanton', 'sell', 4500),
('OMPO', 'TDD Area 18', 'Stanton', 'sell', 4500),
('OMPO', 'TDD Orison', 'Stanton', 'sell', 4500),
('OMPO', 'TDD New Babbage', 'Stanton', 'sell', 4500),
('OMPO', 'Levski', 'Nyx', 'sell', 4771),
('OMPO', 'Gaslight', 'Pyro', 'sell', 4771),
('OMPO', 'Orbituary', 'Pyro', 'sell', 4800),
('OMPO', 'ARC-L1', 'Stanton', 'sell', 5000),
('OMPO', 'HUR-L1', 'Stanton', 'sell', 5000),
('OMPO', 'HUR-L3', 'Stanton', 'sell', 5000),
('OMPO', 'MIC-L4', 'Stanton', 'sell', 5000),
('OMPO', 'Seraphim', 'Stanton', 'sell', 5000),
('OMPO', 'ARC-L4', 'Stanton', 'sell', 5373),
('ORGN', 'TDD Orison', 'Stanton', 'buy', 10808),
('ORGN', 'Rustville', 'Pyro', 'buy', 9257),
('ORGN', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 11000),
('ORGN', 'CBD Lorville', 'Stanton', 'sell', 12000),
('ORGN', 'Deakins Research', 'Stanton', 'sell', 12000),
('ORGN', 'Shepherd''s Rest', 'Pyro', 'sell', 13000),
('ORGN', 'PSS Alpha', 'Nyx', 'sell', 13750),
('ORGN', 'PSS Delta', 'Nyx', 'sell', 13750),
('ORGN', 'PSS Lambda', 'Nyx', 'sell', 14000),
('ORGN', 'PSS Theta', 'Nyx', 'sell', 14000),
('OSOH', 'The Golden Riviera', 'Pyro', 'buy', 343073),
('OSOH', 'Devlin Scrap', 'Stanton', 'sell', 870000),
('OURA', 'Levski', 'Nyx', 'sell', 4600),
('OURA', 'Ruin Station', 'Pyro', 'sell', 4600),
('OURA', 'GrimHEX', 'Stanton', 'sell', 4600),
('OURA', 'CBD Lorville', 'Stanton', 'sell', 4600),
('OURA', 'TDD Area 18', 'Stanton', 'sell', 4600),
('OURA', 'TDD Orison', 'Stanton', 'sell', 4600),
('OURA', 'TDD New Babbage', 'Stanton', 'sell', 4600),
('PFOO', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 1208),
('PFOO', 'TDD Area 18', 'Stanton', 'buy', 1203),
('PFOO', 'Ruin Station', 'Pyro', 'buy', 1202),
('PFOO', 'CRU-L4 Locker', 'Stanton', 'sell', 1100),
('PFOO', 'CRU-L5 Maintenance', 'Stanton', 'sell', 1100),
('PFOO', 'Shepherd''s Rest', 'Pyro', 'sell', 1200),
('PFOO', 'GrimHEX', 'Stanton', 'sell', 1200),
('PFOO', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 1400),
('PFOO', 'Checkmate', 'Pyro', 'sell', 1400),
('PFOO', 'Endgame', 'Pyro', 'sell', 1400),
('PFOO', 'Gaslight', 'Pyro', 'sell', 1400),
('PFOO', 'Megumi', 'Pyro', 'sell', 1400),
('PFOO', 'Orbituary', 'Pyro', 'sell', 1400),
('PFOO', 'Patch City', 'Pyro', 'sell', 1400),
('PFOO', 'Rat''s Nest', 'Pyro', 'sell', 1400),
('PFOO', 'Rod''s Fuel', 'Pyro', 'sell', 1400),
('PFOO', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 1400),
('PFOO', 'Starlight Service', 'Pyro', 'sell', 1400),
('PFOO', 'Ashland', 'Pyro', 'sell', 1400),
('PFOO', 'Fallow Field', 'Pyro', 'sell', 1400),
('PFOO', 'Sacren''s Plot', 'Pyro', 'sell', 1400),
('PFOO', 'The Golden Riviera', 'Pyro', 'sell', 1400),
('PFOO', 'CRU-L1', 'Stanton', 'sell', 1400),
('PFOO', 'ArcCorp 045', 'Stanton', 'sell', 1400),
('PFOO', 'ArcCorp 048', 'Stanton', 'sell', 1400),
('PFOO', 'ArcCorp 056', 'Stanton', 'sell', 1400),
('PFOO', 'ArcCorp 061', 'Stanton', 'sell', 1400),
('PFOO', 'HDMS-Ryder', 'Stanton', 'sell', 1400),
('PFOO', 'HDMS-Woodruff', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SAL-2', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SAL-5', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SCD-1', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SM0-10', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SM0-13', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SM0-18', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SM0-22', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SMCa-6', 'Stanton', 'sell', 1400),
('PFOO', 'Shubin SMCa-8', 'Stanton', 'sell', 1400),
('PFOO', 'TDD New Babbage', 'Stanton', 'sell', 1471),
('PFOO', 'ARC-L3', 'Stanton', 'sell', 1481),
('PFOO', 'PSS Alpha', 'Nyx', 'sell', 1500),
('PFOO', 'PSS Delta', 'Nyx', 'sell', 1500),
('PFOO', 'PSS Lambda', 'Nyx', 'sell', 1500),
('PFOO', 'PSS Theta', 'Nyx', 'sell', 1500),
('PFOO', 'Levski', 'Nyx', 'sell', 1500),
('PFOO', 'Nyx Gateway (Pyro)', 'Pyro', 'sell', 1500),
('PFOO', 'ARC-L1', 'Stanton', 'sell', 1500),
('PFOO', 'ARC-L2', 'Stanton', 'sell', 1500),
('PFOO', 'ARC-L4', 'Stanton', 'sell', 1500),
('PFOO', 'ARC-L5', 'Stanton', 'sell', 1500),
('PFOO', 'CRU-L4', 'Stanton', 'sell', 1500),
('PFOO', 'CRU-L5', 'Stanton', 'sell', 1500),
('PFOO', 'Everus Harbor', 'Stanton', 'sell', 1500),
('PFOO', 'HUR-L1', 'Stanton', 'sell', 1500),
('PFOO', 'HUR-L2', 'Stanton', 'sell', 1500),
('PFOO', 'HUR-L3', 'Stanton', 'sell', 1500),
('PFOO', 'HUR-L4', 'Stanton', 'sell', 1500),
('PFOO', 'HUR-L5', 'Stanton', 'sell', 1500),
('PFOO', 'MIC-L1', 'Stanton', 'sell', 1500),
('PFOO', 'MIC-L2', 'Stanton', 'sell', 1500),
('PFOO', 'MIC-L3', 'Stanton', 'sell', 1500),
('PFOO', 'MIC-L4', 'Stanton', 'sell', 1500),
('PFOO', 'MIC-L5', 'Stanton', 'sell', 1500),
('PFOO', 'Seraphim', 'Stanton', 'sell', 1500),
('PFOO', 'ArcCorp 141', 'Stanton', 'sell', 1500),
('PFOO', 'ArcCorp 157', 'Stanton', 'sell', 1500),
('PFOO', 'CBD Lorville', 'Stanton', 'sell', 1500),
('PFOO', 'Rayari Cantwell', 'Stanton', 'sell', 1500),
('PFOO', 'Rayari Deltana', 'Stanton', 'sell', 1500),
('PFOO', 'Rayari McGrath', 'Stanton', 'sell', 1500),
('PFOO', 'TDD Orison', 'Stanton', 'sell', 1500);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('PICE', 'Port Tressler', 'Stanton', 'buy', 4756),
('PICE', 'Ruin Station', 'Pyro', 'buy', 4614),
('PICE', 'Terra Mills', 'Stanton', 'buy', 4536),
('PICE', 'GrimHEX', 'Stanton', 'sell', 4400),
('PICE', 'Levski', 'Nyx', 'sell', 4600),
('PICE', 'CBD Lorville', 'Stanton', 'sell', 5100),
('PICE', 'TDD Area 18', 'Stanton', 'sell', 5100),
('PICE', 'TDD Orison', 'Stanton', 'sell', 5100),
('PICE', 'TDD New Babbage', 'Stanton', 'sell', 5100),
('PICE', 'Checkmate', 'Pyro', 'sell', 5200),
('PICE', 'Megumi', 'Pyro', 'sell', 5200),
('PICE', 'Orbituary', 'Pyro', 'sell', 5200),
('PICE', 'Patch City', 'Pyro', 'sell', 5200),
('PICE', 'Rat''s Nest', 'Pyro', 'sell', 5200),
('PICE', 'Rod''s Fuel', 'Pyro', 'sell', 5200),
('PICE', 'Starlight Service', 'Pyro', 'sell', 5200),
('PICE', 'Bueno Ravine', 'Pyro', 'sell', 5200),
('PICE', 'Shepherd''s Rest', 'Pyro', 'sell', 5200),
('PICE', 'Ashland', 'Pyro', 'sell', 5500),
('PICE', 'Chawla''s Beach', 'Pyro', 'sell', 5500),
('PICE', 'Fallow Field', 'Pyro', 'sell', 5500),
('PICE', 'Rustville', 'Pyro', 'sell', 5500),
('PICE', 'Sacren''s Plot', 'Pyro', 'sell', 5500),
('PICE', 'Seer''s Canyon', 'Pyro', 'sell', 5500),
('PICE', 'The Golden Riviera', 'Pyro', 'sell', 5500),
('PICE', 'Endgame', 'Pyro', 'sell', 5683),
('PICE', 'Baijini Point', 'Stanton', 'sell', 6150),
('POTA', 'Seraphim', 'Stanton', 'buy', 452),
('POTA', 'Ruin Station', 'Pyro', 'buy', 430),
('POTA', 'Orbituary', 'Pyro', 'buy', 396),
('POTA', 'GrimHEX', 'Stanton', 'sell', 450),
('POTA', 'Gaslight', 'Pyro', 'sell', 530),
('POTA', 'Megumi', 'Pyro', 'sell', 530),
('POTA', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 559),
('POTA', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 560),
('POTA', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 560),
('POTA', 'CBD Lorville', 'Stanton', 'sell', 560),
('POTA', 'TDD Area 18', 'Stanton', 'sell', 560),
('POTA', 'TDD Orison', 'Stanton', 'sell', 560),
('POTA', 'TDD New Babbage', 'Stanton', 'sell', 560),
('POTA', 'Port Tressler', 'Stanton', 'sell', 620),
('POTA', 'Levski', 'Nyx', 'sell', 700),
('PRTL', 'Sacren''s Plot', 'Pyro', 'buy', 89074),
('PRTL', 'Ruin Station', 'Pyro', 'sell', 85000),
('PRTL', 'GrimHEX', 'Stanton', 'sell', 85000),
('PRTL', 'Gaslight', 'Pyro', 'sell', 90000),
('PRTL', 'Rat''s Nest', 'Pyro', 'sell', 90000),
('PRTL', 'PSS Delta', 'Nyx', 'sell', 98000),
('PRTL', 'Bueno Ravine', 'Pyro', 'sell', 106733),
('QUAR', 'Terra Gateway (Stanton)', 'Stanton', 'buy', 4006),
('QUAR', 'Port Tressler', 'Stanton', 'buy', 3911),
('QUAR', 'ArcCorp 045', 'Stanton', 'buy', 3712),
('QUAR', 'Shubin SAL-5', 'Stanton', 'buy', 3705),
('QUAR', 'Shubin SAL-2', 'Stanton', 'buy', 3624),
('QUAR', 'Shubin SM0-18', 'Stanton', 'buy', 3460),
('QUAR', 'Shubin SMCa-6', 'Stanton', 'buy', 3417),
('QUAR', 'Shubin SM0-10', 'Stanton', 'buy', 3361),
('QUAR', 'Shubin SM0-13', 'Stanton', 'buy', 3339),
('QUAR', 'Shubin SM0-22', 'Stanton', 'buy', 3316),
('QUAR', 'Shubin SMCa-8', 'Stanton', 'buy', 3120),
('QUAR', 'Reclamation Orinth', 'Stanton', 'sell', 3100),
('QUAR', 'GrimHEX', 'Stanton', 'sell', 3500),
('QUAR', 'Levski', 'Nyx', 'sell', 3700),
('QUAR', 'Deakins Research', 'Stanton', 'sell', 4000),
('QUAR', 'Hickes Research', 'Stanton', 'sell', 4000),
('QUAR', 'Rayari Anvik', 'Stanton', 'sell', 4000),
('QUAR', 'Rayari Kaltag', 'Stanton', 'sell', 4000),
('QUAR', 'Checkmate', 'Pyro', 'sell', 4200),
('QUAR', 'Endgame', 'Pyro', 'sell', 4200),
('QUAR', 'Gaslight', 'Pyro', 'sell', 4200),
('QUAR', 'Orbituary', 'Pyro', 'sell', 4200),
('QUAR', 'Rod''s Fuel', 'Pyro', 'sell', 4200),
('QUAR', 'Ruin Station', 'Pyro', 'sell', 4200),
('QUAR', 'CBD Lorville', 'Stanton', 'sell', 4400),
('QUAR', 'TDD Area 18', 'Stanton', 'sell', 4400),
('QUAR', 'TDD Orison', 'Stanton', 'sell', 4400),
('QUAR', 'TDD New Babbage', 'Stanton', 'sell', 4400),
('QUAR', 'Patch City', 'Pyro', 'sell', 4600),
('QUAR', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 4620),
('QUAR', 'Seraphim', 'Stanton', 'sell', 4683),
('QUAR', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 5470),
('QUAR', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 5500),
('QUAR', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 5500),
('REVE', 'Terra Mills', 'Stanton', 'buy', 1007),
('REVE', 'Ruin Station', 'Pyro', 'buy', 967),
('REVE', 'GrimHEX', 'Stanton', 'sell', 1000),
('REVE', 'Devlin Scrap', 'Stanton', 'sell', 1000),
('REVE', 'Reclamation Orinth', 'Stanton', 'sell', 1000),
('REVE', 'Samson & Son''s', 'Stanton', 'sell', 1000),
('REVE', 'Checkmate', 'Pyro', 'sell', 1200),
('REVE', 'Patch City', 'Pyro', 'sell', 1200),
('REVE', 'Rat''s Nest', 'Pyro', 'sell', 1200),
('REVE', 'Rod''s Fuel', 'Pyro', 'sell', 1200),
('REVE', 'Starlight Service', 'Pyro', 'sell', 1200),
('REVE', 'Brio''s Breaker', 'Stanton', 'sell', 1300),
('REVE', 'CBD Lorville', 'Stanton', 'sell', 1300),
('REVE', 'TDD Area 18', 'Stanton', 'sell', 1300),
('REVE', 'TDD Orison', 'Stanton', 'sell', 1300),
('REVE', 'Levski', 'Nyx', 'sell', 1400),
('REVE', 'TDD New Babbage', 'Stanton', 'sell', 1400);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('RMC', 'Platinum Pyro Gateway (Nyx)', 'Nyx', 'buy', 10710),
('RMC', 'Platinum Stanton Gateway (Nyx)', 'Nyx', 'buy', 10710),
('RMC', 'Platinum Nyx Gateway (Pyro)', 'Pyro', 'buy', 10710),
('RMC', 'Dumper''s Area 18', 'Stanton', 'buy', 10710),
('RMC', 'Dumper''s GrimHEX', 'Stanton', 'buy', 10710),
('RMC', 'Platinum ARC-L1', 'Stanton', 'buy', 10710),
('RMC', 'Platinum Baijini', 'Stanton', 'buy', 10710),
('RMC', 'Platinum CRU-L1', 'Stanton', 'buy', 10710),
('RMC', 'Platinum CRU-L4', 'Stanton', 'buy', 10710),
('RMC', 'Platinum CRU-L5', 'Stanton', 'buy', 10710),
('RMC', 'Platinum Everus', 'Stanton', 'buy', 10710),
('RMC', 'Platinum HUR-L2', 'Stanton', 'buy', 10710),
('RMC', 'Platinum HUR-L3', 'Stanton', 'buy', 10710),
('RMC', 'Platinum HUR-L5', 'Stanton', 'buy', 10710),
('RMC', 'Platinum Nyx Gateway (Stanton)', 'Stanton', 'buy', 10710),
('RMC', 'Platinum Port Tressler', 'Stanton', 'buy', 10710),
('RMC', 'Platinum Pyro Gateway (Stanton)', 'Stanton', 'buy', 10710),
('RMC', 'Platinum Terra Gateway (Stanton)', 'Stanton', 'buy', 10710),
('RMC', 'Dunboro', 'Stanton', 'buy', 7144),
('RMC', 'Pickers Field', 'Stanton', 'buy', 7144),
('RMC', 'Rappel', 'Stanton', 'buy', 7144),
('RMC', 'Sacren''s Plot', 'Pyro', 'buy', 6572),
('RMC', 'Devlin Scrap', 'Stanton', 'sell', 5000),
('RMC', 'Brio''s Breaker', 'Stanton', 'sell', 5500),
('RMC', 'CRU-L5 Maintenance', 'Stanton', 'sell', 5700),
('RMC', 'CBD Lorville', 'Stanton', 'sell', 6000),
('RMC', 'TDD Area 18', 'Stanton', 'sell', 6000),
('RMC', 'TDD New Babbage', 'Stanton', 'sell', 6000),
('RMC', 'Reclamation Orinth', 'Stanton', 'sell', 6200),
('RMC', 'Samson & Son''s', 'Stanton', 'sell', 6400),
('RMC', 'Levski', 'Nyx', 'sell', 6500),
('RMC', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 7100),
('RMC', 'Ruin Station', 'Pyro', 'sell', 7200),
('RMC', 'GrimHEX', 'Stanton', 'sell', 7200),
('RMC', 'TDD Orison', 'Stanton', 'sell', 7600),
('RMC', 'Endgame', 'Pyro', 'sell', 7700),
('RMC', 'Gaslight', 'Pyro', 'sell', 7700),
('RMC', 'Patch City', 'Pyro', 'sell', 7700),
('RMC', 'Rat''s Nest', 'Pyro', 'sell', 7700),
('RMC', 'Rod''s Fuel', 'Pyro', 'sell', 7700),
('RMC', 'Starlight Service', 'Pyro', 'sell', 7700),
('RMC', 'Ashland', 'Pyro', 'sell', 7700),
('RMC', 'Fallow Field', 'Pyro', 'sell', 7700),
('RMC', 'Rustville', 'Pyro', 'sell', 7700),
('RMC', 'The Golden Riviera', 'Pyro', 'sell', 7700),
('RMC', 'Seer''s Canyon', 'Pyro', 'sell', 8400),
('RMC', 'Terra Mills', 'Stanton', 'sell', 8550),
('SADA', 'CBD Lorville', 'Stanton', 'sell', 500000),
('SADA', 'TDD Area 18', 'Stanton', 'sell', 500000),
('SADA', 'TDD Orison', 'Stanton', 'sell', 500000),
('SADA', 'TDD New Babbage', 'Stanton', 'sell', 500000),
('SALD', 'ArcCorp 045', 'Stanton', 'sell', 34000000),
('SAVR', 'Levski', 'Nyx', 'sell', 185000),
('SAVR', 'Ruin Station', 'Pyro', 'sell', 185000),
('SAVR', 'PSS Delta', 'Nyx', 'sell', 215000),
('SAVR', 'TDD Orison', 'Stanton', 'sell', 215000),
('SAVR', 'Bueno Ravine', 'Pyro', 'sell', 310000),
('SAVR', 'Sacren''s Plot', 'Pyro', 'sell', 310000),
('SAVR', 'The Golden Riviera', 'Pyro', 'sell', 345000),
('SCRA', 'Stanton Gateway (Nyx)', 'Nyx', 'buy', 3305),
('SCRA', 'MIC-L5', 'Stanton', 'buy', 3276),
('SCRA', 'ARC-L4', 'Stanton', 'buy', 3268),
('SCRA', 'Terra Gateway (Stanton)', 'Stanton', 'buy', 3210),
('SCRA', 'Port Tressler', 'Stanton', 'buy', 3132),
('SCRA', 'HUR-L2', 'Stanton', 'buy', 3120),
('SCRA', 'Baijini Point', 'Stanton', 'buy', 3119),
('SCRA', 'Seraphim', 'Stanton', 'buy', 3119),
('SCRA', 'Chawla''s Beach', 'Pyro', 'buy', 3109),
('SCRA', 'Rustville', 'Pyro', 'buy', 3109),
('SCRA', 'Seer''s Canyon', 'Pyro', 'buy', 3109),
('SCRA', 'CRU-L1', 'Stanton', 'buy', 3060),
('SCRA', 'HUR-L1', 'Stanton', 'buy', 3051),
('SCRA', 'Everus Harbor', 'Stanton', 'buy', 3025),
('SCRA', 'ARC-L3', 'Stanton', 'buy', 3008),
('SCRA', 'HUR-L5', 'Stanton', 'buy', 2994),
('SCRA', 'ARC-L5', 'Stanton', 'buy', 2990),
('SCRA', 'MIC-L2', 'Stanton', 'buy', 2990),
('SCRA', 'MIC-L3', 'Stanton', 'buy', 2990),
('SCRA', 'MIC-L4', 'Stanton', 'buy', 2970),
('SCRA', 'ARC-L2', 'Stanton', 'buy', 2968),
('SCRA', 'MIC-L1', 'Stanton', 'buy', 2904),
('SCRA', 'CRU-L5', 'Stanton', 'buy', 2827),
('SCRA', 'Brio''s Breaker', 'Stanton', 'sell', 2600),
('SCRA', 'Devlin Scrap', 'Stanton', 'sell', 2600),
('SCRA', 'Reclamation Orinth', 'Stanton', 'sell', 2600),
('SCRA', 'Samson & Son''s', 'Stanton', 'sell', 2600),
('SCRA', 'GrimHEX', 'Stanton', 'sell', 3000),
('SCRA', 'Ruin Station', 'Pyro', 'sell', 3400),
('SCRA', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 3470),
('SCRA', 'Megumi', 'Pyro', 'sell', 3500),
('SCRA', 'Orbituary', 'Pyro', 'sell', 3500),
('SCRA', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 3500),
('SCRA', 'TDD Orison', 'Stanton', 'sell', 3575),
('SCRA', 'CBD Lorville', 'Stanton', 'sell', 3600),
('SCRA', 'TDD Area 18', 'Stanton', 'sell', 3600),
('SCRA', 'TDD New Babbage', 'Stanton', 'sell', 3600),
('SCRA', 'Levski', 'Nyx', 'sell', 3700),
('SCRA', 'Gaslight', 'Pyro', 'sell', 3700),
('SCRA', 'Patch City', 'Pyro', 'sell', 3700),
('SCRA', 'Rat''s Nest', 'Pyro', 'sell', 3700),
('SCRA', 'Starlight Service', 'Pyro', 'sell', 3700),
('SCRA', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 3700),
('SCRA', 'Dunboro', 'Stanton', 'sell', 3700),
('SCRA', 'Pickers Field', 'Stanton', 'sell', 3700),
('SCRA', 'Rappel', 'Stanton', 'sell', 3700),
('SCRA', 'Checkmate', 'Pyro', 'sell', 3800),
('SCRA', 'Endgame', 'Pyro', 'sell', 4133),
('SCRA', 'Rod''s Fuel', 'Pyro', 'sell', 4433);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('SILI', 'Baijini Point', 'Stanton', 'buy', 2020),
('SILI', 'Ruin Station', 'Pyro', 'buy', 1928),
('SILI', 'Megumi', 'Pyro', 'buy', 1789),
('SILI', 'GrimHEX', 'Stanton', 'sell', 2000),
('SILI', 'Endgame', 'Pyro', 'sell', 2300),
('SILI', 'Rod''s Fuel', 'Pyro', 'sell', 2300),
('SILI', 'Starlight Service', 'Pyro', 'sell', 2300),
('SILI', 'Levski', 'Nyx', 'sell', 2400),
('SILI', 'Port Tressler', 'Stanton', 'sell', 2400),
('SILI', 'Seraphim', 'Stanton', 'sell', 2400),
('SILI', 'CBD Lorville', 'Stanton', 'sell', 2400),
('SILI', 'TDD Area 18', 'Stanton', 'sell', 2400),
('SILI', 'TDD Orison', 'Stanton', 'sell', 2400),
('SILI', 'TDD New Babbage', 'Stanton', 'sell', 2400),
('SILI', 'Gaslight', 'Pyro', 'sell', 2571),
('SILI', 'Rat''s Nest', 'Pyro', 'sell', 2600),
('SILI', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 2746),
('SILI', 'Patch City', 'Pyro', 'sell', 2900),
('STEE', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 1735),
('STEE', 'Everus Harbor', 'Stanton', 'buy', 1522),
('STEE', 'CBD Lorville', 'Stanton', 'sell', 1500),
('STEE', 'GrimHEX', 'Stanton', 'sell', 1600),
('STEE', 'Ruin Station', 'Pyro', 'sell', 1800),
('STEE', 'TDD Area 18', 'Stanton', 'sell', 1900),
('STEE', 'TDD Orison', 'Stanton', 'sell', 1900),
('STEE', 'TDD New Babbage', 'Stanton', 'sell', 1900),
('STEE', 'Seraphim', 'Stanton', 'sell', 1967),
('STEE', 'Checkmate', 'Pyro', 'sell', 2000),
('STEE', 'Orbituary', 'Pyro', 'sell', 2000),
('STEE', 'Starlight Service', 'Pyro', 'sell', 2000),
('STEE', 'Levski', 'Nyx', 'sell', 2200),
('STEE', 'Endgame', 'Pyro', 'sell', 2500),
('STIM', 'Rayari McGrath', 'Stanton', 'buy', 4695),
('STIM', 'Rayari Cantwell', 'Stanton', 'buy', 4635),
('STIM', 'Rod''s Fuel', 'Pyro', 'buy', 4591),
('STIM', 'Hickes Research', 'Stanton', 'buy', 4415),
('STIM', 'Deakins Research', 'Stanton', 'buy', 4295),
('STIM', 'Starlight Service', 'Pyro', 'buy', 4138),
('STIM', 'Gaslight', 'Pyro', 'buy', 4046),
('STIM', 'GrimHEX', 'Stanton', 'sell', 4100),
('STIM', 'TDD Area 18', 'Stanton', 'sell', 4800),
('STIM', 'Ruin Station', 'Pyro', 'sell', 4850),
('STIM', 'Everus Harbor', 'Stanton', 'sell', 4871),
('STIM', 'Orbituary', 'Pyro', 'sell', 4900),
('STIM', 'Ashland', 'Pyro', 'sell', 4900),
('STIM', 'Fallow Field', 'Pyro', 'sell', 4900),
('STIM', 'Rustville', 'Pyro', 'sell', 4900),
('STIM', 'Seer''s Canyon', 'Pyro', 'sell', 4900),
('STIM', 'The Golden Riviera', 'Pyro', 'sell', 4900),
('STIM', 'Megumi', 'Pyro', 'sell', 4920),
('STIM', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 4944),
('STIM', 'CBD Lorville', 'Stanton', 'sell', 4950),
('STIM', 'Endgame', 'Pyro', 'sell', 4960),
('STIM', 'Seraphim', 'Stanton', 'sell', 4960),
('STIM', 'Baijini Point', 'Stanton', 'sell', 4967),
('STIM', 'HUR-L1', 'Stanton', 'sell', 4980),
('STIM', 'Checkmate', 'Pyro', 'sell', 5000),
('STIM', 'Patch City', 'Pyro', 'sell', 5000),
('STIM', 'CRU-L4', 'Stanton', 'sell', 5000),
('STIM', 'HUR-L3', 'Stanton', 'sell', 5000),
('STIM', 'ARC-L1', 'Stanton', 'sell', 5007),
('STIM', 'TDD New Babbage', 'Stanton', 'sell', 5022),
('STIM', 'ARC-L3', 'Stanton', 'sell', 5025),
('STIM', 'HUR-L5', 'Stanton', 'sell', 5025),
('STIM', 'ARC-L5', 'Stanton', 'sell', 5033),
('STIM', 'TDD Orison', 'Stanton', 'sell', 5040),
('STIM', 'Port Tressler', 'Stanton', 'sell', 5045),
('STIM', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 5062),
('STIM', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 5100),
('STIM', 'MIC-L4', 'Stanton', 'sell', 5120),
('STIM', 'Levski', 'Nyx', 'sell', 5167),
('STIM', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 5257),
('STIM', 'PSS Delta', 'Nyx', 'sell', 5300),
('STIM', 'Rat''s Nest', 'Pyro', 'sell', 5371),
('STIM', 'Nyx Gateway (Pyro)', 'Pyro', 'sell', 5433),
('STIM', 'PSS Theta', 'Nyx', 'sell', 5467),
('STIM', 'PSS Alpha', 'Nyx', 'sell', 5560),
('STIM', 'PSS Lambda', 'Nyx', 'sell', 5600),
('STIM', 'ArcCorp 045', 'Stanton', 'sell', 5600),
('STIM', 'ArcCorp 048', 'Stanton', 'sell', 5600),
('STIM', 'ArcCorp 056', 'Stanton', 'sell', 5600),
('STIM', 'ArcCorp 061', 'Stanton', 'sell', 5600),
('STIM', 'Shubin SCD-1', 'Stanton', 'sell', 5600),
('STIM', 'Shubin SMCa-6', 'Stanton', 'sell', 5600),
('STIM', 'Shubin SMCa-8', 'Stanton', 'sell', 5600),
('STIM', 'ArcCorp 157', 'Stanton', 'sell', 5633),
('STIM', 'Rayari Deltana', 'Stanton', 'sell', 5700),
('STIM', 'ArcCorp 141', 'Stanton', 'sell', 5720),
('SUNB', 'PSS Theta', 'Nyx', 'buy', 78082),
('SUNB', 'Shepherd''s Rest', 'Pyro', 'buy', 65626),
('SUNB', 'CRU-L4 Locker', 'Stanton', 'sell', 69000),
('SUNB', 'Levski', 'Nyx', 'sell', 79000),
('SUNB', 'GrimHEX', 'Stanton', 'sell', 79000),
('SUNB', 'CBD Lorville', 'Stanton', 'sell', 79000),
('SUNB', 'TDD Area 18', 'Stanton', 'sell', 79000),
('SUNB', 'TDD Orison', 'Stanton', 'sell', 79000),
('SUNB', 'TDD New Babbage', 'Stanton', 'sell', 79000),
('SUNB', 'Ashland', 'Pyro', 'sell', 86000),
('SUNB', 'Fallow Field', 'Pyro', 'sell', 88000),
('SUNB', 'PSS Lambda', 'Nyx', 'sell', 94000),
('SUNB', 'Sacren''s Plot', 'Pyro', 'sell', 97500),
('SUNB', 'Rayari Deltana', 'Stanton', 'sell', 102000);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('TARA', 'HDMS-Ryder', 'Stanton', 'buy', 23611),
('TARA', 'HDMS-Woodruff', 'Stanton', 'buy', 23590),
('TARA', 'Samson & Son''s', 'Stanton', 'buy', 20396),
('TARA', 'Ruin Station', 'Pyro', 'sell', 22000),
('TARA', 'GrimHEX', 'Stanton', 'sell', 22000),
('TARA', 'CRU-L4 Locker', 'Stanton', 'sell', 22000),
('TARA', 'Rod''s Fuel', 'Pyro', 'sell', 25000),
('TARA', 'Ashland', 'Pyro', 'sell', 25000),
('TARA', 'Sacren''s Plot', 'Pyro', 'sell', 25000),
('TARA', 'The Golden Riviera', 'Pyro', 'sell', 25000),
('TARA', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 27000),
('TARA', 'CBD Lorville', 'Stanton', 'sell', 27000),
('TARA', 'TDD Area 18', 'Stanton', 'sell', 27000),
('TARA', 'TDD New Babbage', 'Stanton', 'sell', 27800),
('TARA', 'Levski', 'Nyx', 'sell', 28000),
('TARA', 'Fallow Field', 'Pyro', 'sell', 28000),
('TARA', 'TDD Orison', 'Stanton', 'sell', 28250),
('TIN', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 3486),
('TIN', 'Brio''s Breaker', 'Stanton', 'sell', 2500),
('TIN', 'CRU-L5 Maintenance', 'Stanton', 'sell', 2500),
('TIN', 'Samson & Son''s', 'Stanton', 'sell', 2500),
('TIN', 'Reclamation Orinth', 'Stanton', 'sell', 2900),
('TIN', 'GrimHEX', 'Stanton', 'sell', 3500),
('TIN', 'Checkmate', 'Pyro', 'sell', 3800),
('TIN', 'Endgame', 'Pyro', 'sell', 3800),
('TIN', 'Orbituary', 'Pyro', 'sell', 3800),
('TIN', 'Rat''s Nest', 'Pyro', 'sell', 3800),
('TIN', 'Rod''s Fuel', 'Pyro', 'sell', 3800),
('TIN', 'Ruin Station', 'Pyro', 'sell', 3800),
('TIN', 'Starlight Service', 'Pyro', 'sell', 3800),
('TIN', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 4000),
('TIN', 'Levski', 'Nyx', 'sell', 4000),
('TIN', 'CBD Lorville', 'Stanton', 'sell', 4000),
('TIN', 'TDD Area 18', 'Stanton', 'sell', 4000),
('TIN', 'TDD Orison', 'Stanton', 'sell', 4000),
('TIN', 'TDD New Babbage', 'Stanton', 'sell', 4000),
('TIN', 'Gaslight', 'Pyro', 'sell', 4300),
('TIN', 'Megumi', 'Pyro', 'sell', 4300),
('TIN', 'Baijini Point', 'Stanton', 'sell', 4500),
('TIN', 'Port Tressler', 'Stanton', 'sell', 4500),
('TITA', 'Baijini Point', 'Stanton', 'buy', 7745),
('TITA', 'Everus Harbor', 'Stanton', 'buy', 7497),
('TITA', 'Shubin SAL-5', 'Stanton', 'buy', 7180),
('TITA', 'MIC-L3', 'Stanton', 'buy', 7130),
('TITA', 'HDMS-Bezdek', 'Stanton', 'buy', 7034),
('TITA', 'HDMS-Lathan', 'Stanton', 'buy', 7034),
('TITA', 'Brio''s Breaker', 'Stanton', 'sell', 6200),
('TITA', 'Devlin Scrap', 'Stanton', 'sell', 6200),
('TITA', 'Reclamation Orinth', 'Stanton', 'sell', 6200),
('TITA', 'GrimHEX', 'Stanton', 'sell', 7000),
('TITA', 'Levski', 'Nyx', 'sell', 7400),
('TITA', 'ARC-L5', 'Stanton', 'sell', 8180),
('TITA', 'Gaslight', 'Pyro', 'sell', 8286),
('TITA', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 8300),
('TITA', 'Checkmate', 'Pyro', 'sell', 8300),
('TITA', 'Endgame', 'Pyro', 'sell', 8300),
('TITA', 'Orbituary', 'Pyro', 'sell', 8300),
('TITA', 'Rat''s Nest', 'Pyro', 'sell', 8300),
('TITA', 'Rod''s Fuel', 'Pyro', 'sell', 8300),
('TITA', 'Ruin Station', 'Pyro', 'sell', 8300),
('TITA', 'CBD Lorville', 'Stanton', 'sell', 8300),
('TITA', 'TDD Area 18', 'Stanton', 'sell', 8300),
('TITA', 'TDD Orison', 'Stanton', 'sell', 8300),
('TITA', 'TDD New Babbage', 'Stanton', 'sell', 8300),
('TITA', 'ARC-L3', 'Stanton', 'sell', 8560),
('TITA', 'Starlight Service', 'Pyro', 'sell', 8900),
('TITA', 'Megumi', 'Pyro', 'sell', 9500),
('TORI', 'Levski', 'Nyx', 'sell', 6600),
('TORI', 'Ruin Station', 'Pyro', 'sell', 6900),
('TORI', 'TDD Area 18', 'Stanton', 'sell', 7700),
('TORI', 'TDD Orison', 'Stanton', 'sell', 7700),
('TORI', 'TDD New Babbage', 'Stanton', 'sell', 7700),
('TORI', 'Port Tressler', 'Stanton', 'sell', 8500),
('TRIT', 'Hickes Research', 'Stanton', 'buy', 18983),
('TRIT', 'GrimHEX', 'Stanton', 'sell', 21000),
('TRIT', 'Endgame', 'Pyro', 'sell', 34667),
('TRIT', 'Gaslight', 'Pyro', 'sell', 35000),
('TUNG', 'ArcCorp 061', 'Stanton', 'buy', 9233),
('TUNG', 'ArcCorp 045', 'Stanton', 'buy', 9104),
('TUNG', 'Shubin SMCa-8', 'Stanton', 'buy', 9052),
('TUNG', 'Shubin SCD-1', 'Stanton', 'buy', 9044),
('TUNG', 'Rod''s Fuel', 'Pyro', 'buy', 9025),
('TUNG', 'ArcCorp 056', 'Stanton', 'buy', 8943),
('TUNG', 'Shubin SMCa-6', 'Stanton', 'buy', 8835),
('TUNG', 'CRU-L4 Locker', 'Stanton', 'sell', 8200),
('TUNG', 'Samson & Son''s', 'Stanton', 'sell', 8200),
('TUNG', 'GrimHEX', 'Stanton', 'sell', 8700),
('TUNG', 'Levski', 'Nyx', 'sell', 9200),
('TUNG', 'Ruin Station', 'Pyro', 'sell', 9700),
('TUNG', 'PSS Lambda', 'Nyx', 'sell', 10000),
('TUNG', 'CBD Lorville', 'Stanton', 'sell', 10000),
('TUNG', 'TDD Area 18', 'Stanton', 'sell', 10000),
('TUNG', 'TDD Orison', 'Stanton', 'sell', 10000),
('TUNG', 'TDD New Babbage', 'Stanton', 'sell', 10000),
('TUNG', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 10200),
('TUNG', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 11000),
('TUNG', 'Stanton Gateway (Pyro)', 'Pyro', 'sell', 11000),
('TUNG', 'Nyx Gateway (Stanton)', 'Stanton', 'sell', 11000),
('TUNG', 'Terra Gateway (Stanton)', 'Stanton', 'sell', 11000),
('TUNG', 'Megumi', 'Pyro', 'sell', 12000);

INSERT INTO commodity_prices (commodity_abbr, station, system, direction, price) VALUES
('WAST', 'MIC-L3', 'Stanton', 'buy', 286),
('WAST', 'MIC-L5', 'Stanton', 'buy', 286),
('WAST', 'MIC-L4', 'Stanton', 'buy', 252),
('WAST', 'MIC-L2', 'Stanton', 'buy', 249),
('WAST', 'MIC-L1', 'Stanton', 'buy', 243),
('WAST', 'Area 18 IO Tower', 'Stanton', 'buy', 240),
('WAST', 'MTP New Babbage', 'Stanton', 'buy', 240),
('WAST', 'Orison Providence', 'Stanton', 'buy', 240),
('WAST', 'Nyx Gateway (Stanton)', 'Stanton', 'buy', 232),
('WAST', 'Checkmate', 'Pyro', 'buy', 229),
('WAST', 'Megumi', 'Pyro', 'buy', 229),
('WAST', 'ARC-L1', 'Stanton', 'buy', 229),
('WAST', 'ARC-L2', 'Stanton', 'buy', 229),
('WAST', 'ARC-L3', 'Stanton', 'buy', 229),
('WAST', 'ARC-L4', 'Stanton', 'buy', 229),
('WAST', 'ARC-L5', 'Stanton', 'buy', 229),
('WAST', 'CRU-L1', 'Stanton', 'buy', 229),
('WAST', 'CRU-L4', 'Stanton', 'buy', 229),
('WAST', 'CRU-L5', 'Stanton', 'buy', 229),
('WAST', 'HUR-L1', 'Stanton', 'buy', 229),
('WAST', 'HUR-L2', 'Stanton', 'buy', 229),
('WAST', 'HUR-L3', 'Stanton', 'buy', 229),
('WAST', 'HUR-L4', 'Stanton', 'buy', 229),
('WAST', 'HUR-L5', 'Stanton', 'buy', 229),
('WAST', 'Lorville L19', 'Stanton', 'buy', 229),
('WAST', 'ArcCorp 045', 'Stanton', 'buy', 229),
('WAST', 'ArcCorp 048', 'Stanton', 'buy', 229),
('WAST', 'ArcCorp 056', 'Stanton', 'buy', 229),
('WAST', 'ArcCorp 061', 'Stanton', 'buy', 229),
('WAST', 'Deakins Research', 'Stanton', 'buy', 229),
('WAST', 'HDMS-Hahn', 'Stanton', 'buy', 229),
('WAST', 'HDMS-Perlman', 'Stanton', 'buy', 229),
('WAST', 'HDMS-Ryder', 'Stanton', 'buy', 229),
('WAST', 'HDMS-Woodruff', 'Stanton', 'buy', 229),
('WAST', 'Hickes Research', 'Stanton', 'buy', 229),
('WAST', 'Rayari Anvik', 'Stanton', 'buy', 229),
('WAST', 'Rayari Cantwell', 'Stanton', 'buy', 229),
('WAST', 'Rayari Deltana', 'Stanton', 'buy', 229),
('WAST', 'Rayari Kaltag', 'Stanton', 'buy', 229),
('WAST', 'Rayari McGrath', 'Stanton', 'buy', 229),
('WAST', 'Shubin SAL-2', 'Stanton', 'buy', 229),
('WAST', 'Shubin SAL-5', 'Stanton', 'buy', 229),
('WAST', 'Shubin SCD-1', 'Stanton', 'buy', 229),
('WAST', 'Shubin SM0-10', 'Stanton', 'buy', 229),
('WAST', 'Shubin SM0-13', 'Stanton', 'buy', 229),
('WAST', 'Shubin SM0-18', 'Stanton', 'buy', 229),
('WAST', 'Shubin SM0-22', 'Stanton', 'buy', 229),
('WAST', 'Shubin SMCa-6', 'Stanton', 'buy', 229),
('WAST', 'Shubin SMCa-8', 'Stanton', 'buy', 229),
('WAST', 'Port Tressler', 'Stanton', 'buy', 200),
('WAST', 'CBD Lorville', 'Stanton', 'buy', 199),
('WAST', 'Seraphim', 'Stanton', 'buy', 198),
('WAST', 'Rod''s Fuel', 'Pyro', 'buy', 196),
('WAST', 'ArcCorp 141', 'Stanton', 'buy', 192),
('WAST', 'ArcCorp 157', 'Stanton', 'buy', 190),
('WAST', 'Baijini Point', 'Stanton', 'buy', 189),
('WAST', 'GrimHEX', 'Stanton', 'sell', 200),
('WAST', 'Dunboro', 'Stanton', 'sell', 210),
('WAST', 'Pickers Field', 'Stanton', 'sell', 210),
('WAST', 'Rappel', 'Stanton', 'sell', 210),
('WAST', 'Levski', 'Nyx', 'sell', 240),
('WAST', 'Nyx Gateway (Pyro)', 'Pyro', 'sell', 240),
('WAST', 'TDD Area 18', 'Stanton', 'sell', 240),
('WAST', 'TDD New Babbage', 'Stanton', 'sell', 240),
('WAST', 'TDD Orison', 'Stanton', 'sell', 260),
('WAST', 'Pyro Gateway (Nyx)', 'Nyx', 'sell', 370),
('WAST', 'Stanton Gateway (Nyx)', 'Nyx', 'sell', 380),
('WAST', 'Orbituary', 'Pyro', 'sell', 450),
('WAST', 'Ruin Station', 'Pyro', 'sell', 450),
('WAST', 'Everus Harbor', 'Stanton', 'sell', 450),
('WIDO', 'Rat''s Nest', 'Pyro', 'buy', 6266),
('WIDO', 'Megumi', 'Pyro', 'buy', 6105),
('WIDO', 'CRU-L4 Locker', 'Stanton', 'sell', 5700),
('WIDO', 'Fallow Field', 'Pyro', 'sell', 6400),
('WIDO', 'GrimHEX', 'Stanton', 'sell', 7175),
('WIDO', 'Ashland', 'Pyro', 'sell', 7200),
('WIDO', 'Starlight Service', 'Pyro', 'sell', 7350),
('WIDO', 'Samson & Son''s', 'Stanton', 'sell', 7600),
('WIDO', 'Reclamation Orinth', 'Stanton', 'sell', 8000),
('WIDO', 'Brio''s Breaker', 'Stanton', 'sell', 8300),
('WIDO', 'The Golden Riviera', 'Pyro', 'sell', 8450),
('WIDO', 'Devlin Scrap', 'Stanton', 'sell', 8900),
('XAPY', 'Gaslight', 'Pyro', 'buy', 3782),
('XAPY', 'Fallow Field', 'Pyro', 'buy', 3754),
('XAPY', 'GrimHEX', 'Stanton', 'sell', 4100),
('XAPY', 'Ruin Station', 'Pyro', 'sell', 4600),
('XAPY', 'Levski', 'Nyx', 'sell', 4800),
('XAPY', 'CBD Lorville', 'Stanton', 'sell', 4800),
('XAPY', 'TDD Area 18', 'Stanton', 'sell', 4800),
('XAPY', 'TDD Orison', 'Stanton', 'sell', 4800),
('XAPY', 'TDD New Babbage', 'Stanton', 'sell', 4800),
('XAPY', 'MIC-L3', 'Stanton', 'sell', 6400);
