-- =============================================================================
-- manufacturers_seed.sql
-- Generado por: scripts/import-manufacturers.js
-- Fecha:        2026-04-05
-- Origen:       manufacturers.json (1071 registros totales)
-- Importados:   137  |  Excluidos: 934
-- =============================================================================
--
-- AVISO: 3 colisión/es de code en el dataset origen.
-- code NO tiene UNIQUE constraint. Colisiones a resolver manualmente.
--
--   code="MIS"  →  "Mirai"  vs  "Musashi Industrial & Starflight Concern"
--   code="HRST"  →  "Hurston Dynamics"  vs  "Casaba Outlet"
--   code="ARCC"  →  "ArcCorp"  vs  "Casaba Outlet"

-- Inserción idempotente: filas ya existentes se omiten sin error.
insert into manufacturers (id, name, code, description)
values
  ('587fcede-4fe9-4fb4-85ec-124abc8542b0', 'Talon', 'TALN', 'A Croshaw-based munitions manufacturer that focuses on missiles, bombs, and torpedoes. 

If it exists, there’s a Talon that can blow it up.'),
  ('3909dad3-eab3-4da7-9d90-74d7064d5900', 'GNP', 'GRNP', 'Seeking to stand out in the crowded field of manufacturers and to compete with the more developed “homeworlds,” the governments of four outer systems banded together to subsidize the creation of GNP, an entirely new kind of company that specialized in designing everything from full-range sensor suites to ship engines.'),
  ('4ee4ba50-f4e3-4c54-9f44-9a6c5691c77e', 'Lortell Computing', 'LOCO', 'A manufacturer of affordable computers, computer parts, and accessories. There products don''t have a lot of bells and whistles and often incorporate last gen tech, but because of that, what they do produce is reliable. Produce the Re-Authorized brand cryptokey.'),
  ('2b5ba252-e826-4356-ac0d-8d88007ea386', 'Banu', 'BANU', 'Banu society combines the Human concepts of family and corporations into a single social unit know as a Souli, a cohabitation focused centered around a specific skillset. These Banu guilds do not control an entire market, rather there are always numerous Souli competing for the same market as the guilds are constantly in flux. 

Because of this, the Banu do not market specific brand Soulis. Instead they simply market all their wares to Humans as Banu built.'),
  ('857a8335-65be-491a-b613-2f16cf165289', 'Mirai', 'MIS', 'The Mirai design team is dedicated to pairing the craftsmanship of their parent company MISC with Xi’an technology and traditional Saisei aesthetics to create the next generation of cutting-edge vehicles.'),
  ('23186ec6-28ed-4f2e-a3f9-0c5459202d63', 'Roberts Space Industries', 'RSI', 'The original creators of the engine that kickstarted Humanity’s expansion into space, Roberts Space Industries builds a wide range of spaceships that serve all needs, from basic interstellar travel to deep exploration on the outer edges of the galaxy. The tagline is “Roberts Space Industries: Delivering the Stars since 2075”'),
  ('19fbaf6d-d6dc-4e15-8fdf-67101934ff3c', 'Joker Engineering', 'JOK', 'From the mind of underground engineer Barlowe Elias, Joker Engineering is here to push the boundaries of tech, the foundations of civilization with their wild products.'),
  ('afff101e-eb2c-4f93-960f-cec9936b9f39', 'Nav-E7 Gadgets', 'NAVE', 'In the short time the company has been around, Nav-E7 has become an institution. Manufacturing various pieces of equipment used on a wide range of ships has given them quick renown as most ships in the ''verse feature at least one of their products.'),
  ('0ade6e45-ecdd-42a9-9046-3e96dbe4f5d0', 'ArcCorp', 'ARCC', 'This massive conglomerate owns one of the planets in the Stanton system, but got its start building fusion engines for industrial craft. They also have a division for terraforming that''s diverged into more of a mining consortium.'),
  ('4ecc1a24-d228-4dd5-8857-21ba6145a1d3', 'Esperia', 'ESPR', 'Originally formed as an archive for ship designs, Esperia began to build historically accurate reproductions for collectors, enthusiasts, and even the military.'),
  ('b99ddb18-b325-44de-abfa-ce2e978424e4', 'Aciedo CommRelay', 'ACDO', 'Responsible for building the CommRelay infrastructure around the UEE, Aciedo also developed the technology to allow for system to system communications.'),
  ('d7cc897f-b760-4a73-93c0-27e23c52db0a', 'Juno Starwerk', 'JUST', 'Second only to RSI in terms of longevity in the space industry, Juno Starwerk was founded in the 24th century to build long haul freighters to support the rapid Human expansion into other star systems. Utilitarian above all us, these ships were designed to do one thing: haul as much weight as possible as cheaply as possible. While, over time, as competition increased, their share of the ship market shrank, their components had earned a reputation for dependability and ease of maintenance. Their direct sales of these components soon made up the majority of the companies income and in 2513, the ceased ship manufacture entirely to focus on supplying industrial strength components. In parts of the ’verse there are generations of mechanics who have passed knowledge and techniques for working on Juno power plants like family heirlooms. This long history also means that Juno parts and repairs are easy to come by.'),
  ('31907472-a884-4ebc-86db-cd4f7797e514', 'Gatac Manufacture', 'GAM', 'Responsible for the design and construction of any ships with commercial or industrial applications, Gatac Manufacture has a long-standing reputation as a ‘knowledge-driven’ corporation producing not only cutting edge ships, but extremely reliable ones.'),
  ('ee8b7bb3-d420-435c-924f-561e67e64588', 'Hurston Dynamics', 'HRST', 'Hurston Dynamics Manufacturer placeholder info about company.'),
  ('c4052a24-2547-4ebc-9137-aa9f09a907af', 'Revel & York', 'REYO', NULL),
  ('3ce33ad8-82e7-4d8d-9ad1-bc95b976c17c', 'VFG Industrial', 'VFGI', NULL),
  ('4526be72-2c19-453c-ab43-29cc23f77154', 'Self-Land', 'SELA', NULL),
  ('7b5d1ed3-11e7-49e6-9ed3-9d0cb52a3dc2', 'Kruger Intergalatic', 'KRI', 'Kruger Intergalactic started as a custom machined parts manufacturer on Borea in the Magnus system, eventually expanded into weapon development and finally as a manufacturer of short-range ships like the P-52.'),
  ('5d616e6f-3257-4d19-90c3-11ab974f12e7', 'ACOM', 'ACOM', 'In racing circles, the term ACOM has come to have two meanings. The first is an abbreviation of the phrase ‘a commanding lead’ – meaning to pull so far ahead that the rest of the pack doesn’t stand a chance of catching up. The second is a more recent usage in that it refers to the start-up manufacturing company who took the phrase as their epithet. ACOM focuses on creating ship components that handle as much power as possible as quickly as possible in order to give pilots the all-important extra edge during a race. Founded by the children of famed pit crew chief Garrit Bijarani, siblings Jayce and Zan took four generations of racing knowledge and gave it form in ACOM’s full line of power plants and coolers.'),
  ('2948496b-45d2-41f8-bdff-97587f1e6981', 'Basilisk', 'BASL', 'Defensive system manufacturer who produces shield systems, ship armor and personal armor for both the military and private sector.'),
  ('967cd454-20d9-4cb8-8465-990ff1a1f769', 'WillsOp', 'WLOP', 'WillsOp have products to cover the whole spectrum of electronic analysis from tracking and targeting to scanners and deep-space radar.'),
  ('6cf93625-789a-4e8f-a857-325d64a58c93', 'J-Span', 'JSPN', 'J-Span does only one thing, but does it well. For over a century they have focused on producing quality coolers at a reasonable price. Half the time these days, when you pop the hull of a spacecraft, chances are you’re going to find a J-Span. Plus, their coolers can be found in more than just ships. They have a wide variety of sizes and shapes that can be found in everything from land transports, to computer systems, to refrigerator units. Appealing to the broader consumer market, their units might not have all the bells and whistles as some of the other manufacturer’s lines, but for the most part they avoid their quirks as well.'),
  ('64eef2d9-5d3d-431d-a83b-ae077a16b4e2', 'CBD', 'CBD', 'CBD. They''re clothes. Either buy them or don''t.'),
  ('92b20988-dbf3-4e95-b4a9-7e5e22112516', 'Dyna Lei', 'DYL', '- Dyna Lei Description'),
  ('3b54a8cc-5700-45f1-940a-2436b213926f', '987', '987', 'Known for their more aggressive urban styling. Asymmetrical. Bold graphic prints.'),
  ('5ca8a669-44c2-40e4-89b2-7a5da790b832', 'City Lights', 'CTL', 'City Lights makes timeless, affordable fashion for the entire family.'),
  ('1ddcadf0-7bb0-4fa9-94f0-6af19432631c', 'R6 Pro', 'R6P', 'R6 Pro''s rugged footwear is made to withstand wear and tear in even the most extreme environments, so even if you get knocked down, we''re there to help you get back up again.'),
  ('2ab62815-6273-44b9-bbc6-28d36fed6fd8', 'Derion', 'DRN', 'With their muted colors and classic cuts, Derion has become the definition of high-end business wear for men and women.'),
  ('2d1922e0-f8dc-46d3-a453-6a85711f3771', 'NorthStar', 'NRS', 'NorthStar Description'),
  ('e7489831-23c1-4629-ab36-221bb9bad06f', 'Rambler', 'RMB', 'PH - Rambler Description'),
  ('70ce6432-3a1e-45a1-8179-fe30a3ee54dc', 'Habidash', 'HDH', 'Very simply made clothing that is made for extreme environments. Takes inspiration from middle east and inuit designs.'),
  ('d9179d05-55be-4eed-8b1b-93bb8450ff04', 'CBA', 'CBA', 'Code Blue Apparel produces a wide variety of longwear professional uniforms and jumpsuits that focus on comfort and personality without sacrificing functionality.'),
  ('d7a8b196-8778-4e18-8c8c-38229eef01f1', 'Hawksworth''s', 'HWK', 'When they say that shoes make the man, Hawksworth''s are the shoes they are talking about. Formal, classic, and constructed to the same exacting standards that has made the Hawksworth brand the standard to beat.'),
  ('503b0974-5027-4c69-bce6-a38c42e87ebe', 'Fiore', 'FIO', 'A timeless elegance lends an ease of wear that defines each sophisticated piece in Fiore''s signature collection.'),
  ('f444bb54-a422-44a0-abdb-a0384f0f5593', 'Upsiders', 'UPS', 'Upsiders is a lifestyle footwear brand with excellent options for every member of your family.'),
  ('4a05001d-0511-415f-8e32-618fbd75242b', 'Octagon', 'OCT', 'PH Octagon Description'),
  ('a53bbc2b-aa43-483d-967e-0cebc5600c04', 'DMC', 'DMC', 'Still renowned for their denim, DMC (Denim Manufacture Corporation) has become so much more. From durable outerwear to rugged fashion, DMC knows that feeling good is just as important as looking good.'),
  ('d56a3985-2f29-4095-b2f2-542376cc74f4', 'Gyson Inc.', 'GYS', 'If you need it, Gyson makes it. The company and its subsidiaries produce everything from carpets to cleaning solvents to industrial uniforms and even EVA suits at prices that can''t be beat.'),
  ('cc1731c4-8156-4750-a138-96838df79117', 'MYM', 'MYM', 'MYM description'),
  ('e7c9f9ee-a1db-40ee-bfa8-a8ffead4ac1d', 'Spar Van Miles', 'SPV', 'SPV brings you inventive twists and inspirational detailing for a day to night collection that is whatever you want it to be.'),
  ('6d4b7375-8e0c-445a-a243-21f8f94f99cb', 'GSB', 'GSB', 'GSB description'),
  ('c0635984-4973-41c6-ac27-0c9a39ae051d', 'Evalight', 'EVL', 'They can''t define you. They can''t tell you who you are. EvaLight and let your voice be heard.'),
  ('6f5af1a4-a50d-41e5-8bb0-c1acd89d4b9e', 'OpalSky', 'OPS', 'Classic, simple and timeless, OpalSky creates casual attire. What millionaires wear when lounging on their space yachts.'),
  ('f8efa046-7f79-4e09-b2fc-35d0df2429cf', 'Navy Surplus', 'NVS', 'PH - Navy Surplus Description'),
  ('20121812-97a6-4ce1-a6a4-88a5ed646c58', 'SCU', 'SCU', 'SCU description'),
  ('190a2e0e-6d60-4719-8238-ac7e1c746626', 'Escar Limited', 'ELD', 'Escar Limited takes comfortable casual wear to the next level through interesting textiles and exquisite craftsmanship.'),
  ('7dfff1b9-2bfa-4ace-86d9-30329a2a0f30', 'Vaporwear', 'VPW', 'PH - Vaporwear Description'),
  ('dd14fd7f-eead-4f7d-8057-2d95405a0183', 'Alejo Brothers', 'ALB', 'Reflect your rugged independence and attitude with Alejo Brothers gear.'),
  ('a834198a-3465-4b02-86a5-887e922ec06d', 'Gallenson Tactical Systems', 'GAT', 'This Earth-based company is responsible for hard-hitting array of ship weapons.'),
  ('74b1d2f4-f820-4935-a25c-b11f68d72f55', 'Musashi Industrial & Starflight Concern', 'MIS', 'Mass produces very efficient, modular ships, mostly armored freighters of different sizes that make them the preferred brand for traders and larger corporations. Over thirty years ago, MISC signed a lend-lease agreement to establish a tech trade with Xi’An engineers.'),
  ('d70afa6f-c7aa-4a3f-b222-d2208e6c21a9', 'Aegis Dynamics', 'TRAS', 'Aegis grew to prominence as a manufacturer of military spacecraft during the First Tevarin War. Favored by Ivar Messer, their orbital bombers grew to public prominence after his infamous victory on Idris IV and became synonymous with the ruthless Messer regime that followed. After the Fall of the Imperator, Aegis'' contracts were stripped, their ships fell out of favor with the public, and the company went into a tailspin. They downsized their craft production and turned to manufacturing parts. However, time heals all wounds and today Aegis has risen once again to be a top military contractor of ships and components.'),
  ('40c59850-8fb5-4a0e-ab61-7fd3871a632a', 'Sakura Sun', 'SASU', 'Soft drinks, high end kitchen equipment, children’s toys? Sakura Sun. Rover platforms, terraforming solutions, bioengineered livestock? Sakura Sun. High-tech wave cannons, starship power plants, antimatter ordinance? Sakura Sun! While corporate conglomerates are not uncommon, it’s rare for any company to advertise them all under the same banner. But at Sakura Sun, empire-building is in full effect: you’ll find a little bit of everything branded with a distinctive purple sun-and-cherry-blossom logo, from plastic Hi-Ho Flatcat figurines to top-of-the-line multi-particle/wave cannons. Stranger still, Sakura Sun has successfully gained a reputation as a company that not only does a little bit of everything, but does it well.'),
  ('bb1024bc-b82e-491c-820c-36662c36feb3', 'Tumbril Land Systems', 'TMBL', 'Tumbril Land Systems got its start manufacturing ultra-rugged land vehicles built to explore the strange and dangerous landscapes of newly discovered planets. With the onset of the First Tevarin War, Tumbril expanded their operations when they won a government contract to build tanks and other military vehicles for the UPE military. Over the centuries the company eventually folded. Today, the Tumbril brand has been revived to build land vehicles from tanks to exploration vehicles and personal HOVs in both the civilian and military market.'),
  ('4668760a-d8a1-48d0-be4d-42304b702de0', 'Vanduul', 'VNC', 'Military designations for the various Vanduul ship components.'),
  ('587a3cae-5e66-4f22-b0fc-1a47d41cafef', 'Unknown', 'UNKN', 'PH Unknown Manufacturer Description'),
  ('cf4a74bf-eb2c-462a-9b78-f7f2724c31d2', 'Aegis Dynamics', 'AEG', 'Aegis grew to prominence as a manufacturer of military spacecraft during the First Tevarin War. Favored by Ivar Messer, their orbital bombers grew to public prominence after his infamous victory on Idris IV and became synonymous with the ruthless Messer regime that followed. After the Fall of the Imperator, Aegis'' contracts were stripped, their ships fell out of favor with the public, and the company went into a tailspin. They downsized their craft production and turned to manufacturing parts. However, time heals all wounds and today Aegis has risen once again to be a top military contractor of ships and components.'),
  ('1e47a9ec-a3f0-431d-be0e-377712e1ed84', 'Origin Jumpworks', 'ORIG', 'Known primarily for high-end ship manufacturing, but also provides some custom parts for their ships - particularly maneuvering thrusters. Sleek and elegant fusion of art and engineering'),
  ('65a5d887-3b21-4046-a718-6912c0c7c3be', 'Behring', 'BEH', 'The Behring Research Consortium was founded in 2554 on Terra as the end result of several years of buyouts and consolidation of dozens of small research and development firms by Behring Equity Investments. By having so many different research units focusing on a wide variety of developments, the Behring group hoped to increase the likelihood of expensive research resulting in a marketable product. Their history speaks for itself as the famed laboratory is accredited for the standardization of laser weaponry and dozens of other innovations. Today, Behring is still going strong with their technological forward products featuring straight forward and simple designs, making everything from guns, missiles, sentry drones, to shields and armor.'),
  ('f113387e-0905-489a-829d-8cebfdc19e66', 'NV-TAC', 'NVTC', 'High-end company known for manufacturing technically precise and experimental optics and weapon attachments. Founded in 2811, NV-TAC initially built sensors for long-range scanning stations and surveying operations before shifting operations to the more profitable personal weapon market. Seen by some as too expensive and feature-dense, but beloved by soldiers and security professionals for their durable design, precision adjustments, and reliable performance.'),
  ('da264d7b-755b-48a2-9580-4adc17ff7ad5', 'UltiFlex', 'UTFL', 'Been around for a couple hundred years. Survival company that makes knives. Got their start by making combat knives for the UEE Army. Expanded their operations to the public after decades of proud service.'),
  ('1aa076d5-ac29-4c61-a905-d3ea39cf167a', 'Klaus & Werner', 'KLA', 'Formed in 2893, Klaus & Werner makes guns, and they make them well. This simple philosophy was the brainchild of Hector Klaus, a successful weapons inventor who believed above all else that simplicity of design would triumph in a combat situation.'),
  ('f2ca879c-deb6-49bf-a4b1-dc3a9cf91e7a', 'ArmaMod', 'ARMA', 'ArmaMod'),
  ('b33050cd-6ca9-4c57-baf8-f4114eb85237', 'Gemini', 'GEM', 'Personal weapon manufacturer. Generally makes kinetic weapons, but has recently acquired Octa, a small energy weapon start-up. Weapons are named sequentially.'),
  ('9d3ee727-bb52-4ed2-bacf-47d93d8bb0d5', 'Hedeby Gunworks', 'HDGW', 'Hedeby Gunworks Description'),
  ('ec227ef3-fb08-4897-abdb-579eb4e87c25', 'Consolidated Outland', 'CNOU', 'Founded by maverick trillionaire Silas Koerner, Consolidated Outland is an up-and-coming spacecraft concern, the first ever headquartered on a frontier world. Koerner, who made his sizable fortune in jump-communications, founded the company as an attempt to strike back at what he sees as the overly-regulated spacecraft industry. With facilities established as far from possible from the prying eyes of competing corporations, Outland is quickly becoming one to watch.'),
  ('f4a1ad63-43fb-483c-a90f-33dd50586e3a', 'Curelife', 'CUR', 'Makes medical packs for commercial purposes. Formed by a group of doctors, CureLife was the first company to offer heavy medical solutions to the general public.'),
  ('cdf6ea1e-7de3-4b58-bf9d-13c5fbafc49a', 'Mirai', 'MIS', 'The Mirai design team is dedicated to pairing the craftsmanship of their parent company MISC with Xi’an technology and traditional Saisei aesthetics to create the next generation of cutting-edge vehicles.'),
  ('f91beb30-915c-42f6-9b1f-f5bd74633fd6', 'Seal Corporation', 'SECO', 'One of the earliest companies to begin selling energy based shielding to civilians when the technology was declassified, Seal Corp has been in the industry centuries longer than its current modern day competition. For a while, the term ‘seal’ was ubiquitous with shield and Sammy the Seal Corp seal is still one of the most recognizable mascots across the ’verse. While they have lost some market share to competitors over the years, they are still the most widely used brand of shields and their products can be bought easily in almost every system.'),
  ('a2ba1db6-a7e8-49db-ba52-c61219693531', 'Aegis Dynamics', 'PRAR', 'Aegis grew to prominence as a manufacturer of military spacecraft during the First Tevarin War. Favored by Ivar Messer, their orbital bombers grew to public prominence after his infamous victory on Idris IV and became synonymous with the ruthless Messer regime that followed. After the Fall of the Imperator, Aegis'' contracts were stripped, their ships fell out of favor with the public, and the company went into a tailspin. They downsized their craft production and turned to manufacturing parts. However, time heals all wounds and today Aegis has risen once again to be a top military contractor of ships and components.'),
  ('e441348b-6b41-4d00-a381-5ff20e014c2c', 'Casaba Outlet', 'CNTR', NULL),
  ('dcfca4a3-180e-4190-9a7e-820e747e1ad9', 'Casaba Outlet', 'MITE', NULL),
  ('1b4babeb-5c3d-4c31-a9dd-5f53e0e8893c', 'Casaba Outlet', 'PCDF', NULL),
  ('918384f8-9a35-465a-a515-ba256e96d6e8', 'Casaba Outlet', 'CORD', NULL),
  ('31a695b6-683d-4cd4-a8d1-9d5458327567', 'Casaba Outlet', 'HRST', NULL),
  ('7db7b41d-ff7f-4ed9-9550-7aaaae9fa265', 'Casaba Outlet', 'FTLC', NULL),
  ('9b460be8-0c7c-47fb-a6ac-21aa88a6c09f', 'Casaba Outlet', 'OGPO', NULL),
  ('10d3571e-dd95-4e5d-a644-ccaee0f1fdb9', 'Casaba Outlet', 'CONO', NULL),
  ('a5367701-2bb5-4da2-bfdf-9a025df8f46b', 'Casaba Outlet', 'ARCC', NULL),
  ('c52dc2d9-624c-4722-b63a-33a38ac0039c', 'Casaba Outlet', 'KCTR', NULL),
  ('27e371d2-2dcb-428c-a32a-a17e246f02e8', 'Casaba Outlet', 'APLL', NULL),
  ('db2fdcd3-aa45-4878-bdba-8d6062885f45', 'Casaba Outlet', 'ATRO', NULL),
  ('4f6dafd0-0b7e-4aac-844a-356896049adc', 'Casaba Outlet', 'TDD', NULL),
  ('d73a45ce-6b59-4791-937d-1bd7a0819ee0', 'Casaba Outlet', 'CUBY', NULL),
  ('435366d8-8b47-4cbc-b0cf-688a95a0847d', 'Yorm', 'YORM', 'Gotlieb Yorm was a top racing pilot on the professional circuit, who was known for his willingness to do anything to shave a few more seconds off his lap times. For a short while, before the Safety Commission stepped in, he would race naked, claiming clothes were an unnecessary weight. Another such innovation that was considerably more successful (and modest) was his insistence that the shields being used on his racer were too powerful. He really only needed to be able to fend off a few shots, because after that he would either have maneuvered his ship out of targeting range, or he would have lost the race anyway. Gutting apart an existing shield by hand, Yorm hacked together a lighter shield that would draw less power and only protect him just enough to escape. Soon, many other racers were trying to mimic his efforts, and when Yorm retired, he went on to successfully sell his modified shield design.'),
  ('9e1f5a35-edcc-4d19-bede-08e2730043c5', 'Argo Astronautics', 'ARGO', 'This commercial ship manufacturer focuses on building shuttles, transport vessels and utility vehicles that can be seen around the universe.'),
  ('4835d29c-3cdd-4983-97b2-1af4674c4c00', 'Sakura Sun', 'ROO', 'Soft drinks, high end kitchen equipment, children’s toys? Sakura Sun. Rover platforms, terraforming solutions, bioengineered livestock? Sakura Sun. High-tech wave cannons, starship power plants, antimatter ordinance? Sakura Sun! While corporate conglomerates are not uncommon, it’s rare for any company to advertise them all under the same banner. But at Sakura Sun, empire-building is in full effect: you’ll find a little bit of everything branded with a distinctive purple sun-and-cherry-blossom logo, from plastic Hi-Ho Flatcat figurines to top-of-the-line multi-particle/wave cannons. Stranger still, Sakura Sun has successfully gained a reputation as a company that not only does a little bit of everything, but does it well.'),
  ('ad865899-f5ba-4818-ae8c-fe80a55108b7', 'Broad & Rabiee', 'BRRA', 'Founded by a pair of aerospace engineers, Broad & Rabiee began with a line of computers and components before branching out to turrets.'),
  ('60d0f346-0c22-4869-81d3-1168b526a258', 'Lightning Power Ltd.', 'LPLT', 'Made out of less expensive materials, Lightning Power continues to introduce new aesthetic changes to their ship components while relying on tried and true technology to run them.'),
  ('bcea197e-ac9d-49f4-a692-d77c6927077f', 'Blue Triangle Inc.', 'BLTR', 'Makers of advanced computer and analytic systems, Blue Triangle prides itself on hiring only the best engineers and programmers, many of whom started their careers as black hat hackers.'),
  ('a349d45f-cda5-4fdb-89ea-4ea91804a163', 'Kilgore and Poole', 'KAP', 'Kilgore and Poole caters its armor and image to a high-end clientele. Criticized by some as prioritizing form over function, their eye-catching armor favors ease of movement and agility over heavy defense.'),
  ('b9b97673-c585-4e0a-b229-a0a3c79668c3', 'Flashfire Systems', 'FFSY', 'Failed laser weapon manufacturer. Transformed into an engineering firm that came up with the weapon mount system that''s almost uniformly used.'),
  ('d1a1bf03-89d9-4eae-ac34-11eeb8e45d8f', 'Thermyte Concern', 'THCN', 'Thermyte Concern'),
  ('cfc0122d-5275-415a-a656-3dcb3346feb5', 'Ace Astrogation', 'ACAS', 'Corp focusing on the structural (non-combat) aspects of the ship. Builds sleek, elegant but powerful power plants.'),
  ('de0d3594-9f18-42c0-8a90-6edd723d80f8', 'Aegis Dynamics', 'MXOX', 'Aegis grew to prominence as a manufacturer of military spacecraft during the First Tevarin War. Favored by Ivar Messer, their orbital bombers grew to public prominence after his infamous victory on Idris IV and became synonymous with the ruthless Messer regime that followed. After the Fall of the Imperator, Aegis'' contracts were stripped, their ships fell out of favor with the public, and the company went into a tailspin. They downsized their craft production and turned to manufacturing parts. However, time heals all wounds and today Aegis has risen once again to be a top military contractor of ships and components.'),
  ('7b4402a1-f17f-4125-afcc-4a159dcd29e0', 'KnightBridge Arms', 'KBAR', 'Headquartered in the Kiel system, KnightBridge Arms is there to protect you and yours. With a weapon for every price point, you can rest assured that KnightBridge has your back.'),
  ('a2a97679-2a6e-4e89-80d8-439c88a01427', 'Tyler Design & Tech', 'TYDT', 'Tyler Design & Tech began its life manufacturing generators, air purifiers, and other necessities for planetary settlers. Tyler focused on making products that, while not as powerful as some other brands, were durable and extremely efficient with little heat byproduct which led to the development of low-signature power plants.  It wasn’t long before even the UEE Navy began to outfit some of their own stealth crafts with Tyler parts, and with their new success the company was able to expand their ship component line into what it is today.'),
  ('06370f79-4741-4781-be08-d5acc9e28047', 'Aopoa', 'XNAA', 'Though many attributed their elevation to the sole provider of light craft to audacity and daring, Aopoa cemented their position thanks to the innovative dual-vector thruster technology that has revolutionized their ship design.'),
  ('5f81335d-44e6-4104-841e-c5af9df06829', 'Aegis Dynamics', 'FSKI', 'Aegis grew to prominence as a manufacturer of military spacecraft during the First Tevarin War. Favored by Ivar Messer, their orbital bombers grew to public prominence after his infamous victory on Idris IV and became synonymous with the ruthless Messer regime that followed. After the Fall of the Imperator, Aegis'' contracts were stripped, their ships fell out of favor with the public, and the company went into a tailspin. They downsized their craft production and turned to manufacturing parts. However, time heals all wounds and today Aegis has risen once again to be a top military contractor of ships and components.'),
  ('eccba58a-f6d9-42e8-95c6-d0a65763e583', 'Amon & Reese Co.', 'AMRS', 'Formed early in the Messer era by recent veterans Marcelo Amon and Travis Reese, A&R Co. is one of the oldest energy weapon manufacturers in the UEE. Their designs have always been user focused and they have a well-earned reputation for dependability and ease of use, something the company claims derives from a dedication to field testing that well exceeds what other companies do.'),
  ('d8ef0f35-e196-4d18-affa-750f6cdf8cb4', 'Wen/Cassel Propulsion', 'WCPR', 'Subsidiary of RSI, handles a small percentage of their thruster and ship options construction as well as cooling systems.'),
  ('b922abdb-0634-4358-9eee-60118f3cf3a7', 'Anvil Aerospace', 'ANVL', 'For civilians, Anvil Aerospace produces small fighting craft but with less of the pirate stigma. These ships are more expensive, less spit-and-glue, and built to take more hits than a comparable Drake model. The bulk of Anvil''s income is from its military contracts with the UEE to design and build their warships, especially the iconic Hornet.'),
  ('b28a5c61-63a4-478b-8047-5fba545d5b8a', 'Musashi Industrial & Starflight Concern', 'MIS', 'Mass produces very efficient, modular ships, mostly armored freighters of different sizes that make them the preferred brand for traders and larger corporations. Over thirty years ago, MISC signed a lend-lease agreement to establish a tech trade with Xi’An engineers.'),
  ('0d3e6377-4be0-4c38-8269-3ac5dbd132d8', 'Syang Fabrication', 'SYFB', 'PH Syang Fabrication Description'),
  ('73a6ba90-8f53-423d-ad0b-96e81b7e18a5', 'Roussimoff Rehabilitation Systems', 'RRS', 'Roussimoff Rehabilitation Systems (RRS) is an Earth-based corporation that provides rehabilitation services, personal body armor and defensive systems throughout the UEE. Their arms division is responsible for a groundbreaking series of new weaponry designed to incapacitate opponents without taking lives.'),
  ('8a7bd715-5b97-404f-b02e-0d0cc593f608', 'Clark Defense Systems', 'CDS', 'Ground-combat defensive systems, covers a lot of commercial territory from personal armor to defense systems. Naming convention tend to be pretty straight-forward and logical.

Models: PAB-4 (Personal Ablative/Ballistic Light Armor)

QDB-12 QuiKCade (Quick Deployment Barricade)'),
  ('d133f90d-bc69-4273-9867-6c03631f0c4b', 'UEE Navy', 'NVY', '(PH) UEE Navy - Description'),
  ('be4a26fd-0585-4aaf-bad9-d234091bd02e', 'CC''s Conversions', 'CCC', 'CC''s Conversions Description'),
  ('eddc1a94-7840-4855-9889-544821d4d739', 'Caldera', 'CLDA', 'Caldera Description.'),
  ('b495993e-c10a-41e4-876d-1de96de54e33', 'Doomsday', 'DOOM', 'Extremely aggressive looking homemade armor meant to protect and intimidate. This kind of armor is not only expected to survive the apocalypse, but also dominate its aftermath.'),
  ('0e6d8f1b-ebb8-4773-8ca4-f25d737c8709', 'Virgil', 'VGL', 'High-end Commercial and Personal armor manufacturer. Aside from combat uses, they build systems for heavy commercial and mining applications.

Models: Achilles PDS (Heavy Combat Armor)

Zeus System (Titan Armor)'),
  ('8368a760-84b4-4359-bda1-7b015dc0c884', 'Hardin Tactical', 'HDTC', 'PH Hardin Tactical Desc'),
  ('04ded06f-7862-4771-b40f-aa310b74ee17', 'Universal Body Armor', 'UBA', '- Universal Body Armor Description'),
  ('c0bc7b2d-9c1a-4029-9715-f28b81122863', 'Tehachapi', 'THP', 'PH - Tehachapi Description'),
  ('709e8255-a0b1-4c5e-8b0e-28781be25984', 'Kastak Arms', 'KSAR', 'Kastak Arms makes inexpensive energy weapons with intimidating names like Devastator and Firestorm, and aggressively markets them to distressed parts of the Empire. Even though the company portrays itself as providing weapons for personal defense, the brand has become more readily identified with people who use them for aggressive and unlawful purposes.'),
  ('093e6eba-93fa-4dad-b3dd-38966934e34e', 'Roberts Space Industries', 'RSI', 'The original creators of the engine that kickstarted Humanity’s expansion into space, Roberts Space Industries builds a wide range of spaceships that serve all needs, from basic interstellar travel to deep exploration on the outer edges of the galaxy. The tagline is “Roberts Space Industries: Delivering the Stars since 2075”'),
  ('9f0f7735-d389-4c7d-95f1-c4d0c57f7214', 'microTech', 'MIT', 'Ubiquitous around the Empire, microTech and their range of electronics, datapads, mobile interfaces, handheld sensors and computer software upgrades for starships are used daily by almost everyone. Their line of mobiGlas personal computers have become an integral part of daily life for millions of people.'),
  ('819545f4-18af-49a6-814e-ca4fd08f56e5', 'Greycat Industrial', 'GRIN', 'A trusted manufacturer of industrial tools since 2337, the company’s extensive line of industrial equipment and armor make it one of the most respected brand names around. Greycat has remained a UEE staple for centuries thanks to their streamlined-yet-inventive designs, exacting safety standards, and a diverse product line.'),
  ('63685f47-b0cc-4ebe-8f16-72793a5cd6e0', 'Crusader Industries', 'CRUS', 'Makers of an extensive fleet of cargo, vehicle and data transport ships, and cutting edge shuttles, Crusader Industries is a titan of the aerospace industry. It is a company so powerful and prominent that it purchased a gas giant in the Stanton system to house its current headquarters.'),
  ('d8eca6d3-b40c-46c0-953e-ef5840c1fa63', 'Greycat Industrial', 'GRIN', 'A trusted manufacturer of industrial tools since 2337, the company’s extensive line of industrial equipment and armor make it one of the most respected brand names around. Greycat has remained a UEE staple for centuries thanks to their streamlined-yet-inventive designs, exacting safety standards, and a diverse product line.'),
  ('abca0ae0-a819-4aeb-a1a7-f8f1d7e277cf', 'Ascension Astro', 'ASAS', 'Ascension Astro started off as a boutique specialty company; selling high-end, low IR thrusters to wealthy clients who wanted to fly their luxury ships while avoiding the eyes of greedy pirates. As good as their thrusters were at being low-sig, the effect was often ruined when the engines or shielding made by other manufacturers would be screaming the ship’s presence. Slowly, Ascension began expanding their line to include a whole suite of components that, when working in conjunction, would provide an extremely low profile and a safer journey.'),
  ('768b4380-6486-4187-8c22-bc3deaf80770', 'Grey''s Market', 'GLSN', 'A fleet of mobile marketplaces that caters to high-end clients interested in experiencing the wild side of the ''verse to gain access to unusual and unique items.'),
  ('055fe7c5-2e02-4e3a-aacb-f289563fabbd', 'PH Associated Science and Development', 'ASD', 'PH Associated Science and Development Description'),
  ('0f9ffe57-8542-4d83-a246-72568a5f2f91', 'Wei-Tek', 'WETK', 'Upstart company made by former employees of Ascension Astro.'),
  ('57bfcf3d-13f6-4c2c-b7c7-6bf8eacb8a24', 'Gorgon Defender Industries', 'GODI', 'When Humanity started being attacked by Vanduul, it was often those who lived in the border system who suffered the most. Believing that civilian defensive components were not up to facing this deadly enemy, Gorgon Defender Industries, founded by former inhabitants of Caliban, was established to take military strength products and deliver it the population at large so they could properly protect themselves. With the strength of their designs, Gorgon earned a reputation that soon caught the eye of the military.'),
  ('2e06e775-940b-4c24-8974-31fb5617ea56', 'United Empire of Earth', 'UEE', 'The unified collection of planets and systems under Human control, the UEE strives to create a safe and just empire, championing equality and opportunity for all its inhabitants.'),
  ('8af71a8a-7da0-4e31-afc7-648fc916e387', 'Chimera Communications', 'CHCO', 'A dedicated manufacturer of communication, radar and scan systems. They are the rugged go-to company for miners and explorers alike with their sturdy, well-tested and dependable products.'),
  ('2b25a2dd-47ea-4ab0-8711-03d34be214b1', 'Tarsus', 'TARS', 'Founded by a pair of mechanics who were attempting to make an affordable module that would convert a quantum drive into a jump drive, Tarsus has evolved to become one of the main producers of dependable jump drives in the UEE. Over time they also expanded to build their own quantum drives as well.'),
  ('dd55bc19-5212-4365-bbc8-73474f0257ed', 'Curelife', 'CUR', 'Makes medical packs for commercial purposes. Formed by a group of doctors, CureLife was the first company to offer heavy medical solutions to the general public.'),
  ('bb5a8287-6bb7-4936-a898-4b1850e8112e', 'PH Associated Science and Development', 'ASD', 'PH Associated Science and Development Description'),
  ('f80ab8de-4d04-4a1f-a8f2-ee2bb01fd125', 'Consumable', 'GEND', 'PH Generic Drink Description'),
  ('ab35f85f-919f-4457-8d58-4e885ea6c5c0', 'Shubin Interstellar', 'SHIN', 'Shubin Interstellar Description'),
  ('1b6be99e-f430-459f-ab2a-a912fd6722f8', 'Consumable', 'GENF', 'PH Generic Food Description'),
  ('57432775-b421-45cc-8616-ac2d35018193', 'RAMP Corporation', 'RACO', 'Manufacturer of consumer and pro-grade ship components, RAMP Corp sponsors the Team RAMP M50 racing team.'),
  ('67fd3077-ee8c-4a7c-8bad-91500b2a9509', 'Nova Pyrotechnica', 'NOVP', 'An company out of Terra that offers missiles and rockets at a low price.'),
  ('2a64f92e-8f6d-47ac-a6ed-643465e91d4b', 'Kroneg', 'KRON', 'Kroneg Description'),
  ('77f7999a-b23b-4812-94c2-09b5e15e1b0e', 'Apocalypse Arms', 'APAR', 'Apocalypse Arms produces aggressive, devastating weapons inspired by Messer-Era technology.'),
  ('6116471c-891d-4830-8968-650b6deafc00', 'Drake Interplanetary', 'DRAK', 'Makes affordable, modular ships that have become the go-to manufacturer for anyone looking to get their first ship, but have become associated with criminal elements.')
on conflict (id) do nothing;

-- 137 fabricantes.