-- =============================================================================
-- Migracion: 050_create_mining_material_deposits
-- Modulo:    Mining — Material Finder (donde minar cada material)
-- Fecha:     2026-04-19
-- =============================================================================
--
-- Base de datos de deposits de mineria en Stanton/Pyro/Nyx. Responde:
--   - "Para el material X, donde y con que % lo encuentro?"
--   - "En el location Y, que materiales aparecen por metodo (Ship/ROC/Hand)?"
--   - "Cual es el radar signature / tier / instability / resistance del material?"
--
-- Fuente: gstool.org mining_compiled.json (dataset version 4.7.1-live).
-- El repo referencia es quattrobaje3na-png.github.io/SC-Mining-Material-Finder-2.0
-- (mirror publico no-oficial; data recolectada empiricamente por la comunidad).
--
-- scunpacked NO publica esta dimension (son datos de gameplay observational,
-- no de P4K). Por eso la unica fuente es comunitaria. Cuando cambie el juego,
-- el refresh pasa por bajar el JSON nuevo y re-correr el seed como upsert.
--
-- Schema diseñado como 4 tablas normalizadas para que un cambio en una
-- ubicacion no rompa los enlaces del resto:
--   mining_materials              — diccionario de nombres
--   mining_material_signatures    — 1 fila por (material, method)
--   mining_locations              — 47 locations (Stanton / Pyro / Nyx)
--   mining_location_yields        — 363 filas de location x method x material
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) Diccionario de materiales
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mining_materials (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name              TEXT NOT NULL UNIQUE,
  dataset_version   TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mining_materials_name ON mining_materials(name);

-- -----------------------------------------------------------------------------
-- 2) Signatures (radar + tier + instability + resistance) por metodo
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mining_material_signatures (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  material_name     TEXT NOT NULL,
  method            TEXT NOT NULL CHECK (method IN ('Ship','ROC','Hand')),
  radar_signature   INTEGER,          -- rs: radar signature para detectar el rock
  tier              TEXT,             -- 'Common','Uncommon','Rare','Very Rare'
  instability       NUMERIC,          -- volatilidad del charge
  resistance        NUMERIC,          -- resistencia a rotura (laser power vs mat)
  note              TEXT,             -- texto libre 'Instab: X | Res: Y'
  dataset_version   TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (material_name, method, dataset_version)
);

CREATE INDEX IF NOT EXISTS idx_mms_material ON mining_material_signatures(material_name);
CREATE INDEX IF NOT EXISTS idx_mms_method   ON mining_material_signatures(method);
CREATE INDEX IF NOT EXISTS idx_mms_tier     ON mining_material_signatures(tier);

-- -----------------------------------------------------------------------------
-- 3) Locations
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mining_locations (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name              TEXT NOT NULL,
  system            TEXT NOT NULL,    -- 'Stanton','Pyro','Nyx'
  dataset_version   TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (name, system, dataset_version)
);

CREATE INDEX IF NOT EXISTS idx_mining_locations_system ON mining_locations(system);
CREATE INDEX IF NOT EXISTS idx_mining_locations_name   ON mining_locations(name);

-- -----------------------------------------------------------------------------
-- 4) Yields (location x method x material x chance%)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mining_location_yields (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_name     TEXT NOT NULL,
  system            TEXT NOT NULL,
  method            TEXT NOT NULL CHECK (method IN ('Ship','ROC','Hand')),
  material_name     TEXT NOT NULL,
  chance_pct        NUMERIC NOT NULL CHECK (chance_pct >= 0 AND chance_pct <= 100),
  dataset_version   TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (location_name, system, method, material_name, dataset_version)
);

CREATE INDEX IF NOT EXISTS idx_mly_material ON mining_location_yields(material_name);
CREATE INDEX IF NOT EXISTS idx_mly_location ON mining_location_yields(location_name, system);
CREATE INDEX IF NOT EXISTS idx_mly_method   ON mining_location_yields(method);
CREATE INDEX IF NOT EXISTS idx_mly_chance   ON mining_location_yields(chance_pct DESC);

-- -----------------------------------------------------------------------------
-- RLS: lectura publica, escritura solo service role
-- -----------------------------------------------------------------------------

ALTER TABLE mining_materials              ENABLE ROW LEVEL SECURITY;
ALTER TABLE mining_material_signatures    ENABLE ROW LEVEL SECURITY;
ALTER TABLE mining_locations              ENABLE ROW LEVEL SECURITY;
ALTER TABLE mining_location_yields        ENABLE ROW LEVEL SECURITY;

CREATE POLICY "mm_public_read"   ON mining_materials           FOR SELECT USING (true);
CREATE POLICY "mms_public_read"  ON mining_material_signatures FOR SELECT USING (true);
CREATE POLICY "ml_public_read"   ON mining_locations           FOR SELECT USING (true);
CREATE POLICY "mly_public_read"  ON mining_location_yields     FOR SELECT USING (true);

-- =============================================================================
-- SEED — dataset 4.7.1-live extraido de gstool.org mining_compiled.json
-- =============================================================================

-- =============================================================================
-- Seed de mining material data — auto-generado desde gstool.org mining_compiled.json
-- Version: 4.7.1-live — generado: 2026-04-19
-- =============================================================================

-- 1) Materiales unicos
INSERT INTO mining_materials (name, dataset_version) VALUES
  ('Agricium', '4.7.1-live'),
  ('Aluminum', '4.7.1-live'),
  ('Aphorite', '4.7.1-live'),
  ('Aslarite', '4.7.1-live'),
  ('Beradom', '4.7.1-live'),
  ('Beryl', '4.7.1-live'),
  ('Bexalite', '4.7.1-live'),
  ('Borase', '4.7.1-live'),
  ('Carinite', '4.7.1-live'),
  ('Carinite Pure', '4.7.1-live'),
  ('Copper', '4.7.1-live'),
  ('Corundum', '4.7.1-live'),
  ('Dolivine', '4.7.1-live'),
  ('Feynmaline', '4.7.1-live'),
  ('Glacosite', '4.7.1-live'),
  ('Gold', '4.7.1-live'),
  ('Hadanite', '4.7.1-live'),
  ('Hephaestanite', '4.7.1-live'),
  ('Ice', '4.7.1-live'),
  ('Iron', '4.7.1-live'),
  ('Jaclium', '4.7.1-live'),
  ('Janalite', '4.7.1-live'),
  ('Laranite', '4.7.1-live'),
  ('Lindinium', '4.7.1-live'),
  ('Ouratite', '4.7.1-live'),
  ('Quantainium', '4.7.1-live'),
  ('Quartz', '4.7.1-live'),
  ('Riccite', '4.7.1-live'),
  ('Saldynium', '4.7.1-live'),
  ('Savrilium', '4.7.1-live'),
  ('Silicon', '4.7.1-live'),
  ('Stileron', '4.7.1-live'),
  ('Taranite', '4.7.1-live'),
  ('Tin', '4.7.1-live'),
  ('Titanium', '4.7.1-live'),
  ('Torite', '4.7.1-live'),
  ('Tungsten', '4.7.1-live')
ON CONFLICT (name) DO NOTHING;

-- 2) Signatures (material x method)
INSERT INTO mining_material_signatures (material_name, method, radar_signature, tier, instability, resistance, note, dataset_version) VALUES
  ('Agricium', 'Ship', 3885, 'Uncommon', 350, 0.5, 'Instab: 350.0 | Res: 0.5', '4.7.1-live'),
  ('Agricium', 'ROC', 4000, 'Uncommon', 350, 0.5, 'Instab: 350.0 | Res: 0.5', '4.7.1-live'),
  ('Aluminium', 'Ship', 4285, 'Common', 0, -0.4, 'Instab: 0.0 | Res: -0.4', '4.7.1-live'),
  ('Aluminium', 'ROC', 4000, 'Common', 0, -0.4, 'Instab: 0.0 | Res: -0.4', '4.7.1-live'),
  ('Aphorite', 'Hand', 3000, 'Common', 0, 0, 'Instab: 0.0 | Res: 0.0', '4.7.1-live'),
  ('Aslarite', 'Ship', 3840, 'Uncommon', 700, 0.5, 'Instab: 700.0 | Res: 0.5', '4.7.1-live'),
  ('Beradom', 'ROC', 4000, 'Common', 0, 0, 'Instab: 0.0 | Res: 0.0', '4.7.1-live'),
  ('Beryl', 'Ship', 3540, 'Rare', 350, 0.65, 'Instab: 350.0 | Res: 0.65', '4.7.1-live'),
  ('Beryl', 'ROC', 4000, 'Rare', 350, 0.65, 'Instab: 350.0 | Res: 0.65', '4.7.1-live'),
  ('Bexalite', 'Ship', 3600, 'Rare', 600, 0.6, 'Instab: 600.0 | Res: 0.6', '4.7.1-live'),
  ('Bexalite', 'ROC', 4000, 'Rare', 600, 0.6, 'Instab: 600.0 | Res: 0.6', '4.7.1-live'),
  ('Borase', 'Ship', 3570, 'Rare', 40, 0.3, 'Instab: 40.0 | Res: 0.3', '4.7.1-live'),
  ('Borase', 'ROC', 4000, 'Rare', 40, 0.3, 'Instab: 40.0 | Res: 0.3', '4.7.1-live'),
  ('Carinite', 'ROC', 4000, 'Common', 300, 0.5, 'Instab: 300.0 | Res: 0.5', '4.7.1-live'),
  ('Carinite', 'Hand', 3000, 'Common', 300, 0.5, 'Instab: 300.0 | Res: 0.5', '4.7.1-live'),
  ('Copper', 'Ship', 4240, 'Common', 50, -0.7, 'Instab: 50.0 | Res: -0.7', '4.7.1-live'),
  ('Copper', 'ROC', 4000, 'Common', 50, -0.7, 'Instab: 50.0 | Res: -0.7', '4.7.1-live'),
  ('Corundum', 'Ship', 4225, 'Common', 50, 0.1, 'Instab: 50.0 | Res: 0.1', '4.7.1-live'),
  ('Corundum', 'ROC', 4000, 'Common', 50, 0.1, 'Instab: 50.0 | Res: 0.1', '4.7.1-live'),
  ('Dolivine', 'Hand', 3000, 'Common', 0, 0.1, 'Instab: 0.0 | Res: 0.1', '4.7.1-live'),
  ('Feynmaline', 'ROC', 4000, 'Common', 200, 0, 'Instab: 200.0 | Res: 0.0', '4.7.1-live'),
  ('Glacosite', 'ROC', 4000, 'Common', 0, 0.1, 'Instab: 0.0 | Res: 0.1', '4.7.1-live'),
  ('Gold', 'Ship', 3585, 'Rare', 550, 0.5, 'Instab: 550.0 | Res: 0.5', '4.7.1-live'),
  ('Gold', 'ROC', 4000, 'Rare', 550, 0.5, 'Instab: 550.0 | Res: 0.5', '4.7.1-live'),
  ('Hadanite', 'Hand', 3000, 'Common', 200, 0, 'Instab: 200.0 | Res: 0.0', '4.7.1-live'),
  ('Hephaestanite', 'Ship', 4180, 'Common', 400, -0.3, 'Instab: 400.0 | Res: -0.3', '4.7.1-live'),
  ('Ice', 'Ship', 4300, 'Common', 0, -0.5, 'Instab: 0.0 | Res: -0.5', '4.7.1-live'),
  ('Ice', 'ROC', 4000, 'Common', 0, -0.5, 'Instab: 0.0 | Res: -0.5', '4.7.1-live'),
  ('Iron', 'Ship', 4270, 'Common', 50, -0.4, 'Instab: 50.0 | Res: -0.4', '4.7.1-live'),
  ('Iron', 'ROC', 4000, 'Common', 50, -0.4, 'Instab: 50.0 | Res: -0.4', '4.7.1-live'),
  ('Jaclium', 'Hand', 3000, 'Common', 100, 0.5, 'Instab: 100.0 | Res: 0.5', '4.7.1-live'),
  ('Janalite', 'Hand', 3000, 'Common', 300, 0.3, 'Instab: 300.0 | Res: 0.3', '4.7.1-live'),
  ('Laranite', 'Ship', 3825, 'Uncommon', 400, 0.5, 'Instab: 400.0 | Res: 0.5', '4.7.1-live'),
  ('Laranite', 'ROC', 4000, 'Uncommon', 400, 0.5, 'Instab: 400.0 | Res: 0.5', '4.7.1-live'),
  ('Lindinium', 'Ship', 3400, 'Epic', 1000, 0.95, 'Instab: 1000.0 | Res: 0.95', '4.7.1-live'),
  ('Ouratite', 'Ship', 3370, 'Epic', 600, 0.6, 'Instab: 600.0 | Res: 0.6', '4.7.1-live'),
  ('Quantainium', 'Ship', 3170, 'Legendary', 1000, 0.95, 'Instab: 1000.0 | Res: 0.95', '4.7.1-live'),
  ('Quantainium', 'ROC', 4000, 'Legendary', 1000, 0.95, 'Instab: 1000.0 | Res: 0.95', '4.7.1-live'),
  ('Quartz', 'Ship', 4210, 'Common', 50, -0.7, 'Instab: 50.0 | Res: -0.7', '4.7.1-live'),
  ('Quartz', 'ROC', 4000, 'Common', 50, -0.7, 'Instab: 50.0 | Res: -0.7', '4.7.1-live'),
  ('Riccite', 'Ship', 3385, 'Epic', 850, 0.95, 'Instab: 850.0 | Res: 0.95', '4.7.1-live'),
  ('Sadaryx', 'Hand', 3000, 'Common', 200, 0, 'Instab: 200.0 | Res: 0.0', '4.7.1-live'),
  ('Saldynium', 'Hand', 3000, 'Common', 100, 0, 'Instab: 100.0 | Res: 0.0', '4.7.1-live'),
  ('Savrilium', 'Ship', 3200, 'Legendary', 1000, 0.95, 'Instab: 1000.0 | Res: 0.95', '4.7.1-live'),
  ('Silicon', 'Ship', 4255, 'Common', 50, -0.2, 'Instab: 50.0 | Res: -0.2', '4.7.1-live'),
  ('Silicon', 'ROC', 4000, 'Common', 50, -0.2, 'Instab: 50.0 | Res: -0.2', '4.7.1-live'),
  ('Stileron', 'Ship', 3185, 'Legendary', 870, 0.6, 'Instab: 870.0 | Res: 0.6', '4.7.1-live'),
  ('Taranite', 'Ship', 3555, 'Rare', 700, 0.5, 'Instab: 700.0 | Res: 0.5', '4.7.1-live'),
  ('Taranite', 'ROC', 4000, 'Rare', 700, 0.5, 'Instab: 700.0 | Res: 0.5', '4.7.1-live'),
  ('Tin', 'Ship', 4195, 'Common', 0, -0.2, 'Instab: 0.0 | Res: -0.2', '4.7.1-live'),
  ('Tin', 'ROC', 4000, 'Common', 0, -0.2, 'Instab: 0.0 | Res: -0.2', '4.7.1-live'),
  ('Titanium', 'Ship', 3855, 'Uncommon', 0, 0.1, 'Instab: 0.0 | Res: 0.1', '4.7.1-live'),
  ('Titanium', 'ROC', 4000, 'Uncommon', 0, 0.1, 'Instab: 0.0 | Res: 0.1', '4.7.1-live'),
  ('Torite', 'Ship', 3900, 'Uncommon', 550, 0.25, 'Instab: 550.0 | Res: 0.25', '4.7.1-live'),
  ('Tungsten', 'Ship', 3870, 'Uncommon', 0, -0.4, 'Instab: 0.0 | Res: -0.4', '4.7.1-live'),
  ('Tungsten', 'ROC', 4000, 'Uncommon', 0, -0.4, 'Instab: 0.0 | Res: -0.4', '4.7.1-live')
ON CONFLICT (material_name, method, dataset_version) DO UPDATE SET
  radar_signature = EXCLUDED.radar_signature,
  tier            = EXCLUDED.tier,
  instability     = EXCLUDED.instability,
  resistance      = EXCLUDED.resistance,
  note            = EXCLUDED.note;

-- 3) Locations (47)
INSERT INTO mining_locations (name, system, dataset_version) VALUES
  ('ARC-L3, CRU-L5, MIC-L4', 'Stanton', '4.7.1-live'),
  ('ARC-L5, CRU-L4, MIC-L3', 'Stanton', '4.7.1-live'),
  ('Aaron Halo', 'Stanton', '4.7.1-live'),
  ('Aberdeen', 'Stanton', '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', '4.7.1-live'),
  ('Arial', 'Stanton', '4.7.1-live'),
  ('Asteroid Cluster (Low Yield)', 'Stanton', '4.7.1-live'),
  ('Asteroid Cluster (Medium Yield)', 'Stanton', '4.7.1-live'),
  ('Breaker Stations Large Geode', 'Nyx', '4.7.1-live'),
  ('CRU-L1, CRU-L2, HUR-L3', 'Stanton', '4.7.1-live'),
  ('Calliope', 'Stanton', '4.7.1-live'),
  ('Cellin', 'Stanton', '4.7.1-live'),
  ('Clio', 'Stanton', '4.7.1-live'),
  ('Daymar', 'Stanton', '4.7.1-live'),
  ('Euterpe', 'Stanton', '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', '4.7.1-live'),
  ('HUR-L1, HUR-L4', 'Stanton', '4.7.1-live'),
  ('HUR-L2, ARC-L1, ARC-L2, ARC-L4', 'Stanton', '4.7.1-live'),
  ('HUR-L5, MIC-L1, MIC-L2, MIC-L5', 'Stanton', '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', '4.7.1-live'),
  ('Hurston', 'Stanton', '4.7.1-live'),
  ('Ita', 'Stanton', '4.7.1-live'),
  ('Keeger Belt', 'Nyx', '4.7.1-live'),
  ('Lagrange G', 'Stanton', '4.7.1-live'),
  ('Lyria', 'Stanton', '4.7.1-live'),
  ('Magda', 'Stanton', '4.7.1-live'),
  ('Occupied Lagrange Points', 'Stanton', '4.7.1-live'),
  ('Pyro Belt (Cool 1)', 'Pyro', '4.7.1-live'),
  ('Pyro Belt (Cool 2)', 'Pyro', '4.7.1-live'),
  ('Pyro Belt (Warm 1)', 'Pyro', '4.7.1-live'),
  ('Pyro Belt (Warm 2)', 'Pyro', '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', '4.7.1-live'),
  ('Pyro I', 'Pyro', '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', '4.7.1-live'),
  ('Pyro IV', 'Pyro', '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', '4.7.1-live'),
  ('Wala', 'Stanton', '4.7.1-live'),
  ('Yela', 'Stanton', '4.7.1-live'),
  ('Yela Asteroid Belt', 'Stanton', '4.7.1-live'),
  ('MicroTech', 'Stanton', '4.7.1-live')
ON CONFLICT (name, system, dataset_version) DO NOTHING;

-- 4) Yields (location x method x material x chance%)
INSERT INTO mining_location_yields (location_name, system, method, material_name, chance_pct, dataset_version) VALUES
  ('ARC-L3, CRU-L5, MIC-L4', 'Stanton', 'Ship', 'Agricium', 28.5, '4.7.1-live'),
  ('ARC-L3, CRU-L5, MIC-L4', 'Stanton', 'Ship', 'Beryl', 18, '4.7.1-live'),
  ('ARC-L3, CRU-L5, MIC-L4', 'Stanton', 'Ship', 'Iron', 17.9, '4.7.1-live'),
  ('ARC-L3, CRU-L5, MIC-L4', 'Stanton', 'Ship', 'Ice', 17.8, '4.7.1-live'),
  ('ARC-L3, CRU-L5, MIC-L4', 'Stanton', 'Ship', 'Copper', 17.8, '4.7.1-live'),
  ('ARC-L5, CRU-L4, MIC-L3', 'Stanton', 'Ship', 'Aslarite', 28.5, '4.7.1-live'),
  ('ARC-L5, CRU-L4, MIC-L3', 'Stanton', 'Ship', 'Gold', 18, '4.7.1-live'),
  ('ARC-L5, CRU-L4, MIC-L3', 'Stanton', 'Ship', 'Iron', 17.9, '4.7.1-live'),
  ('ARC-L5, CRU-L4, MIC-L3', 'Stanton', 'Ship', 'Ice', 17.8, '4.7.1-live'),
  ('ARC-L5, CRU-L4, MIC-L3', 'Stanton', 'Ship', 'Copper', 17.8, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Beryl', 18, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Aslarite', 14.2, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Titanium', 14.2, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Ice', 10.4, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Silicon', 10.3, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Aluminum', 10.3, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Iron', 10.3, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Copper', 10.3, '4.7.1-live'),
  ('Aaron Halo', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Ship', 'Corundum', 29.8, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Ship', 'Aluminum', 29.7, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Ship', 'Titanium', 28.5, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Ship', 'Ouratite', 10, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'ROC', 'Feynmaline', 64, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'ROC', 'Glacosite', 32, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'ROC', 'Beradom', 4, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Aberdeen', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', 'Ship', 'Torite', 28.5, '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', 'Ship', 'Ice', 14.9, '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', 'Ship', 'Silicon', 14.9, '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', 'Ship', 'Copper', 14.9, '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', 'Ship', 'Iron', 14.8, '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', 'Ship', 'Riccite', 10, '4.7.1-live'),
  ('Akiro Cluster', 'Pyro', 'Ship', 'Stileron', 2, '4.7.1-live'),
  ('Arial', 'Stanton', 'Ship', 'Aluminum', 22, '4.7.1-live'),
  ('Arial', 'Stanton', 'Ship', 'Tin', 22, '4.7.1-live'),
  ('Arial', 'Stanton', 'Ship', 'Hephaestanite', 22, '4.7.1-live'),
  ('Arial', 'Stanton', 'Ship', 'Corundum', 22, '4.7.1-live'),
  ('Arial', 'Stanton', 'Ship', 'Ouratite', 10, '4.7.1-live'),
  ('Arial', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Arial', 'Stanton', 'ROC', 'Feynmaline', 52, '4.7.1-live'),
  ('Arial', 'Stanton', 'ROC', 'Glacosite', 32, '4.7.1-live'),
  ('Arial', 'Stanton', 'ROC', 'Beradom', 16, '4.7.1-live'),
  ('Arial', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Arial', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Arial', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Asteroid Cluster (Low Yield)', 'Stanton', 'Ship', 'Ice', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Low Yield)', 'Stanton', 'Ship', 'Silicon', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Low Yield)', 'Stanton', 'Ship', 'Aluminum', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Low Yield)', 'Stanton', 'Ship', 'Iron', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Low Yield)', 'Stanton', 'Ship', 'Copper', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Low Yield)', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Asteroid Cluster (Medium Yield)', 'Stanton', 'Ship', 'Ice', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Medium Yield)', 'Stanton', 'Ship', 'Silicon', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Medium Yield)', 'Stanton', 'Ship', 'Aluminum', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Medium Yield)', 'Stanton', 'Ship', 'Iron', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Medium Yield)', 'Stanton', 'Ship', 'Copper', 19.6, '4.7.1-live'),
  ('Asteroid Cluster (Medium Yield)', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Breaker Stations Large Geode', 'Nyx', 'Ship', 'Savrilium', 100, '4.7.1-live'),
  ('CRU-L1, CRU-L2, HUR-L3', 'Stanton', 'Ship', 'Titanium', 28.5, '4.7.1-live'),
  ('CRU-L1, CRU-L2, HUR-L3', 'Stanton', 'Ship', 'Bexalite', 18, '4.7.1-live'),
  ('CRU-L1, CRU-L2, HUR-L3', 'Stanton', 'Ship', 'Iron', 17.9, '4.7.1-live'),
  ('CRU-L1, CRU-L2, HUR-L3', 'Stanton', 'Ship', 'Ice', 17.8, '4.7.1-live'),
  ('CRU-L1, CRU-L2, HUR-L3', 'Stanton', 'Ship', 'Copper', 17.8, '4.7.1-live'),
  ('Calliope', 'Stanton', 'Ship', 'Iron', 32.7, '4.7.1-live'),
  ('Calliope', 'Stanton', 'Ship', 'Ice', 32.6, '4.7.1-live'),
  ('Calliope', 'Stanton', 'Ship', 'Hephaestanite', 32.6, '4.7.1-live'),
  ('Calliope', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Calliope', 'Stanton', 'ROC', 'Glacosite', 84, '4.7.1-live'),
  ('Calliope', 'Stanton', 'ROC', 'Beradom', 12, '4.7.1-live'),
  ('Calliope', 'Stanton', 'ROC', 'Feynmaline', 4, '4.7.1-live'),
  ('Calliope', 'Stanton', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Calliope', 'Stanton', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Calliope', 'Stanton', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Ship', 'Agricium', 28.5, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Ship', 'Silicon', 25.8, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Ship', 'Quartz', 25.7, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Ship', 'Taranite', 18, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Cellin', 'Stanton', 'ROC', 'Beradom', 56, '4.7.1-live'),
  ('Cellin', 'Stanton', 'ROC', 'Glacosite', 32, '4.7.1-live'),
  ('Cellin', 'Stanton', 'ROC', 'Feynmaline', 12, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Cellin', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Clio', 'Stanton', 'Ship', 'Ice', 40, '4.7.1-live'),
  ('Clio', 'Stanton', 'Ship', 'Copper', 40, '4.7.1-live'),
  ('Clio', 'Stanton', 'Ship', 'Taranite', 18, '4.7.1-live'),
  ('Clio', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Clio', 'Stanton', 'ROC', 'Glacosite', 68, '4.7.1-live'),
  ('Clio', 'Stanton', 'ROC', 'Beradom', 20, '4.7.1-live'),
  ('Clio', 'Stanton', 'ROC', 'Feynmaline', 12, '4.7.1-live'),
  ('Clio', 'Stanton', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Clio', 'Stanton', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Clio', 'Stanton', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Daymar', 'Stanton', 'Ship', 'Silicon', 34.8, '4.7.1-live'),
  ('Daymar', 'Stanton', 'Ship', 'Quartz', 34.7, '4.7.1-live'),
  ('Daymar', 'Stanton', 'Ship', 'Agricium', 28.5, '4.7.1-live'),
  ('Daymar', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Daymar', 'Stanton', 'ROC', 'Beradom', 48, '4.7.1-live'),
  ('Daymar', 'Stanton', 'ROC', 'Feynmaline', 40, '4.7.1-live'),
  ('Daymar', 'Stanton', 'ROC', 'Glacosite', 12, '4.7.1-live'),
  ('Daymar', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Daymar', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Daymar', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'Ship', 'Ice', 40, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'Ship', 'Copper', 40, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'Ship', 'Taranite', 18, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'ROC', 'Glacosite', 88, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'ROC', 'Beradom', 12, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'ROC', 'Feynmaline', 0, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Euterpe', 'Stanton', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', 'Ship', 'Torite', 28.5, '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', 'Ship', 'Bexalite', 18, '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', 'Ship', 'Ice', 13.9, '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', 'Ship', 'Aluminum', 13.8, '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', 'Ship', 'Iron', 13.8, '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', 'Ship', 'Lindinium', 10, '4.7.1-live'),
  ('Glaciem Ring', 'Nyx', 'Ship', 'Savrilium', 2, '4.7.1-live'),
  ('HUR-L1, HUR-L4', 'Stanton', 'Ship', 'Laranite', 28.5, '4.7.1-live'),
  ('HUR-L1, HUR-L4', 'Stanton', 'Ship', 'Borase', 18, '4.7.1-live'),
  ('HUR-L1, HUR-L4', 'Stanton', 'Ship', 'Aluminum', 17.9, '4.7.1-live'),
  ('HUR-L1, HUR-L4', 'Stanton', 'Ship', 'Corundum', 17.8, '4.7.1-live'),
  ('HUR-L1, HUR-L4', 'Stanton', 'Ship', 'Hephaestanite', 17.8, '4.7.1-live'),
  ('HUR-L2, ARC-L1, ARC-L2, ARC-L4', 'Stanton', 'Ship', 'Tungsten', 28.5, '4.7.1-live'),
  ('HUR-L2, ARC-L1, ARC-L2, ARC-L4', 'Stanton', 'Ship', 'Taranite', 18, '4.7.1-live'),
  ('HUR-L2, ARC-L1, ARC-L2, ARC-L4', 'Stanton', 'Ship', 'Corundum', 17.9, '4.7.1-live'),
  ('HUR-L2, ARC-L1, ARC-L2, ARC-L4', 'Stanton', 'Ship', 'Aluminum', 17.8, '4.7.1-live'),
  ('HUR-L2, ARC-L1, ARC-L2, ARC-L4', 'Stanton', 'Ship', 'Hephaestanite', 17.8, '4.7.1-live'),
  ('HUR-L5, MIC-L1, MIC-L2, MIC-L5', 'Stanton', 'Ship', 'Torite', 28.4, '4.7.1-live'),
  ('HUR-L5, MIC-L1, MIC-L2, MIC-L5', 'Stanton', 'Ship', 'Aluminum', 23.9, '4.7.1-live'),
  ('HUR-L5, MIC-L1, MIC-L2, MIC-L5', 'Stanton', 'Ship', 'Corundum', 23.9, '4.7.1-live'),
  ('HUR-L5, MIC-L1, MIC-L2, MIC-L5', 'Stanton', 'Ship', 'Hephaestanite', 23.9, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Aphorite', 30.2, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Jaclium', 19.5, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Dolivine', 18.3, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Saldynium', 15.8, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Carinite', 11.6, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Hadanite', 3.2, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Janalite', 1.1, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'Hand', 'Carinite Pure', 0.5, '4.7.1-live'),
  ('Hathor OLP Deposits', 'Stanton', 'ROC', 'Carinite', 100, '4.7.1-live'),
  ('Hurston', 'Stanton', 'Ship', 'Aluminum', 44, '4.7.1-live'),
  ('Hurston', 'Stanton', 'Ship', 'Tin', 44, '4.7.1-live'),
  ('Hurston', 'Stanton', 'Ship', 'Ouratite', 10, '4.7.1-live'),
  ('Hurston', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Hurston', 'Stanton', 'ROC', 'Beradom', 64, '4.7.1-live'),
  ('Hurston', 'Stanton', 'ROC', 'Glacosite', 32, '4.7.1-live'),
  ('Hurston', 'Stanton', 'ROC', 'Feynmaline', 4, '4.7.1-live'),
  ('Hurston', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Hurston', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Hurston', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Ita', 'Stanton', 'Ship', 'Tin', 34.8, '4.7.1-live'),
  ('Ita', 'Stanton', 'Ship', 'Aluminum', 34.7, '4.7.1-live'),
  ('Ita', 'Stanton', 'Ship', 'Aslarite', 28.5, '4.7.1-live'),
  ('Ita', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Ita', 'Stanton', 'ROC', 'Glacosite', 69.2, '4.7.1-live'),
  ('Ita', 'Stanton', 'ROC', 'Feynmaline', 26.9, '4.7.1-live'),
  ('Ita', 'Stanton', 'ROC', 'Beradom', 3.8, '4.7.1-live'),
  ('Ita', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Ita', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Ita', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Keeger Belt', 'Nyx', 'Ship', 'Torite', 28.5, '4.7.1-live'),
  ('Keeger Belt', 'Nyx', 'Ship', 'Bexalite', 18, '4.7.1-live'),
  ('Keeger Belt', 'Nyx', 'Ship', 'Ice', 13.9, '4.7.1-live'),
  ('Keeger Belt', 'Nyx', 'Ship', 'Aluminum', 13.8, '4.7.1-live'),
  ('Keeger Belt', 'Nyx', 'Ship', 'Iron', 13.8, '4.7.1-live'),
  ('Keeger Belt', 'Nyx', 'Ship', 'Lindinium', 10, '4.7.1-live'),
  ('Keeger Belt', 'Nyx', 'Ship', 'Savrilium', 2, '4.7.1-live'),
  ('Lagrange G', 'Stanton', 'Ship', 'Agricium', 28.5, '4.7.1-live'),
  ('Lagrange G', 'Stanton', 'Ship', 'Beryl', 18, '4.7.1-live'),
  ('Lagrange G', 'Stanton', 'Ship', 'Iron', 17.9, '4.7.1-live'),
  ('Lagrange G', 'Stanton', 'Ship', 'Ice', 17.8, '4.7.1-live'),
  ('Lagrange G', 'Stanton', 'Ship', 'Copper', 17.8, '4.7.1-live'),
  ('Lyria', 'Stanton', 'Ship', 'Iron', 34.8, '4.7.1-live'),
  ('Lyria', 'Stanton', 'Ship', 'Copper', 34.8, '4.7.1-live'),
  ('Lyria', 'Stanton', 'Ship', 'Laranite', 28.5, '4.7.1-live'),
  ('Lyria', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Lyria', 'Stanton', 'ROC', 'Beradom', 48, '4.7.1-live'),
  ('Lyria', 'Stanton', 'ROC', 'Glacosite', 48, '4.7.1-live'),
  ('Lyria', 'Stanton', 'ROC', 'Feynmaline', 4, '4.7.1-live'),
  ('Lyria', 'Stanton', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Lyria', 'Stanton', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Lyria', 'Stanton', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Magda', 'Stanton', 'Ship', 'Aluminum', 34.8, '4.7.1-live'),
  ('Magda', 'Stanton', 'Ship', 'Iron', 34.8, '4.7.1-live'),
  ('Magda', 'Stanton', 'Ship', 'Titanium', 14.2, '4.7.1-live'),
  ('Magda', 'Stanton', 'Ship', 'Aslarite', 14.2, '4.7.1-live'),
  ('Magda', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Magda', 'Stanton', 'ROC', 'Glacosite', 59.3, '4.7.1-live'),
  ('Magda', 'Stanton', 'ROC', 'Feynmaline', 37, '4.7.1-live'),
  ('Magda', 'Stanton', 'ROC', 'Beradom', 3.7, '4.7.1-live'),
  ('Magda', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Magda', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Magda', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Occupied Lagrange Points', 'Stanton', 'Ship', 'Agricium', 28.5, '4.7.1-live'),
  ('Occupied Lagrange Points', 'Stanton', 'Ship', 'Beryl', 18, '4.7.1-live'),
  ('Occupied Lagrange Points', 'Stanton', 'Ship', 'Iron', 17.9, '4.7.1-live'),
  ('Occupied Lagrange Points', 'Stanton', 'Ship', 'Ice', 17.8, '4.7.1-live'),
  ('Occupied Lagrange Points', 'Stanton', 'Ship', 'Copper', 17.8, '4.7.1-live'),
  ('Pyro Belt (Cool 1)', 'Pyro', 'Ship', 'Titanium', 28.5, '4.7.1-live'),
  ('Pyro Belt (Cool 1)', 'Pyro', 'Ship', 'Ice', 26.8, '4.7.1-live'),
  ('Pyro Belt (Cool 1)', 'Pyro', 'Ship', 'Silicon', 26.7, '4.7.1-live'),
  ('Pyro Belt (Cool 1)', 'Pyro', 'Ship', 'Borase', 18, '4.7.1-live'),
  ('Pyro Belt (Cool 2)', 'Pyro', 'Ship', 'Aslarite', 28.5, '4.7.1-live'),
  ('Pyro Belt (Cool 2)', 'Pyro', 'Ship', 'Ice', 26.8, '4.7.1-live'),
  ('Pyro Belt (Cool 2)', 'Pyro', 'Ship', 'Silicon', 26.7, '4.7.1-live'),
  ('Pyro Belt (Cool 2)', 'Pyro', 'Ship', 'Taranite', 18, '4.7.1-live'),
  ('Pyro Belt (Warm 1)', 'Pyro', 'Ship', 'Agricium', 28.5, '4.7.1-live'),
  ('Pyro Belt (Warm 1)', 'Pyro', 'Ship', 'Iron', 26.8, '4.7.1-live'),
  ('Pyro Belt (Warm 1)', 'Pyro', 'Ship', 'Copper', 26.7, '4.7.1-live'),
  ('Pyro Belt (Warm 1)', 'Pyro', 'Ship', 'Bexalite', 18, '4.7.1-live'),
  ('Pyro Belt (Warm 2)', 'Pyro', 'Ship', 'Tungsten', 28.5, '4.7.1-live'),
  ('Pyro Belt (Warm 2)', 'Pyro', 'Ship', 'Iron', 26.8, '4.7.1-live'),
  ('Pyro Belt (Warm 2)', 'Pyro', 'Ship', 'Copper', 26.7, '4.7.1-live'),
  ('Pyro Belt (Warm 2)', 'Pyro', 'Ship', 'Gold', 18, '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', 'Ship', 'Torite', 28.5, '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', 'Ship', 'Aluminum', 14.9, '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', 'Ship', 'Corundum', 14.9, '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', 'Ship', 'Quartz', 14.9, '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', 'Ship', 'Tin', 14.8, '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', 'Ship', 'Riccite', 10, '4.7.1-live'),
  ('Pyro RAB, RMB, and Clusters', 'Pyro', 'Ship', 'Stileron', 2, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'Ship', 'Iron', 32.7, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'Ship', 'Copper', 32.6, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'Ship', 'Tin', 32.6, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'Ship', 'Stileron', 2, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro I', 'Pyro', 'ROC', 'Beradom', 100, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'Ship', 'Hephaestanite', 32.7, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'Ship', 'Iron', 32.6, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'Ship', 'Tin', 32.6, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'Ship', 'Stileron', 2, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro II (Monox)', 'Pyro', 'ROC', 'Glacosite', 100, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'ROC', 'Beradom', 100, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Ship', 'Quartz', 35, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Ship', 'Iron', 35, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Ship', 'Borase', 18, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Ship', 'Riccite', 10, '4.7.1-live'),
  ('Pyro III (Bloom)', 'Pyro', 'Ship', 'Stileron', 2, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Ship', 'Laranite', 28.5, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Ship', 'Copper', 25.7, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Ship', 'Iron', 25.7, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Ship', 'Borase', 18, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Ship', 'Stileron', 2, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro IV', 'Pyro', 'ROC', 'Feynmaline', 100, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'ROC', 'Feynmaline', 100, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'Ship', 'Tin', 36, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'Ship', 'Silicon', 36, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'Ship', 'Gold', 18, '4.7.1-live'),
  ('Pyro V-a (Ignis)', 'Pyro', 'Ship', 'Riccite', 10, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'ROC', 'Beradom', 50, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'ROC', 'Glacosite', 50, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'Ship', 'Iron', 36, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'Ship', 'Silicon', 36, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'Ship', 'Gold', 18, '4.7.1-live'),
  ('Pyro V-b (Vatra)', 'Pyro', 'Ship', 'Riccite', 10, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'ROC', 'Glacosite', 100, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'Ship', 'Iron', 43.5, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'Ship', 'Tungsten', 28.5, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'Ship', 'Borase', 18, '4.7.1-live'),
  ('Pyro V-c (Adir)', 'Pyro', 'Ship', 'Riccite', 10, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'ROC', 'Beradom', 100, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Ship', 'Tungsten', 28.5, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Ship', 'Silicon', 26.8, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Ship', 'Iron', 26.7, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Ship', 'Beryl', 9, '4.7.1-live'),
  ('Pyro V-d (Fairo)', 'Pyro', 'Ship', 'Gold', 9, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'ROC', 'Feynmaline', 100, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Ship', 'Aslarite', 28.5, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Ship', 'Iron', 26.8, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Ship', 'Hephaestanite', 26.7, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Ship', 'Borase', 9, '4.7.1-live'),
  ('Pyro V-e (Fuego)', 'Pyro', 'Ship', 'Beryl', 9, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'ROC', 'Glacosite', 100, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Ship', 'Hephaestanite', 26.8, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Ship', 'Iron', 26.8, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Ship', 'Beryl', 18, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Ship', 'Agricium', 14.2, '4.7.1-live'),
  ('Pyro V-f (Vuur)', 'Pyro', 'Ship', 'Aslarite', 14.2, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'ROC', 'Feynmaline', 100, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Ship', 'Ice', 20.8, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Ship', 'Copper', 20.8, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Ship', 'Gold', 18, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Ship', 'Agricium', 14.2, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Ship', 'Titanium', 14.2, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Ship', 'Riccite', 10, '4.7.1-live'),
  ('Pyro VI (Terminus)', 'Pyro', 'Ship', 'Stileron', 2, '4.7.1-live'),
  ('Wala', 'Stanton', 'Ship', 'Laranite', 28.5, '4.7.1-live'),
  ('Wala', 'Stanton', 'Ship', 'Copper', 25.8, '4.7.1-live'),
  ('Wala', 'Stanton', 'Ship', 'Iron', 25.7, '4.7.1-live'),
  ('Wala', 'Stanton', 'Ship', 'Beryl', 18, '4.7.1-live'),
  ('Wala', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Wala', 'Stanton', 'ROC', 'Beradom', 56, '4.7.1-live'),
  ('Wala', 'Stanton', 'ROC', 'Glacosite', 40, '4.7.1-live'),
  ('Wala', 'Stanton', 'ROC', 'Feynmaline', 4, '4.7.1-live'),
  ('Wala', 'Stanton', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('Wala', 'Stanton', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('Wala', 'Stanton', 'Hand', 'Janalite', 2, '4.7.1-live'),
  ('Yela', 'Stanton', 'Ship', 'Agricium', 28.5, '4.7.1-live'),
  ('Yela', 'Stanton', 'Ship', 'Silicon', 25.8, '4.7.1-live'),
  ('Yela', 'Stanton', 'Ship', 'Quartz', 25.7, '4.7.1-live'),
  ('Yela', 'Stanton', 'Ship', 'Taranite', 18, '4.7.1-live'),
  ('Yela', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('Yela', 'Stanton', 'ROC', 'Glacosite', 68, '4.7.1-live'),
  ('Yela', 'Stanton', 'ROC', 'Beradom', 24, '4.7.1-live'),
  ('Yela', 'Stanton', 'ROC', 'Feynmaline', 8, '4.7.1-live'),
  ('Yela', 'Stanton', 'Hand', 'Aphorite', 58.6, '4.7.1-live'),
  ('Yela', 'Stanton', 'Hand', 'Dolivine', 35.4, '4.7.1-live'),
  ('Yela', 'Stanton', 'Hand', 'Hadanite', 6, '4.7.1-live'),
  ('Yela Asteroid Belt', 'Stanton', 'Ship', 'Titanium', 28.5, '4.7.1-live'),
  ('Yela Asteroid Belt', 'Stanton', 'Ship', 'Iron', 20.5, '4.7.1-live'),
  ('Yela Asteroid Belt', 'Stanton', 'Ship', 'Ice', 20.5, '4.7.1-live'),
  ('Yela Asteroid Belt', 'Stanton', 'Ship', 'Copper', 20.5, '4.7.1-live'),
  ('Yela Asteroid Belt', 'Stanton', 'Ship', 'Ouratite', 10, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'Ship', 'Ice', 32.7, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'Ship', 'Hephaestanite', 32.7, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'Ship', 'Iron', 32.6, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'Ship', 'Quantainium', 2, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'ROC', 'Glacosite', 68, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'ROC', 'Beradom', 28, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'ROC', 'Feynmaline', 4, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'Hand', 'Aphorite', 61.1, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'Hand', 'Dolivine', 36.9, '4.7.1-live'),
  ('MicroTech', 'Stanton', 'Hand', 'Janalite', 2, '4.7.1-live')
ON CONFLICT (location_name, system, method, material_name, dataset_version) DO UPDATE SET
  chance_pct = EXCLUDED.chance_pct;
